### ISSUE TITLE
Addon Icon not showing for Firefox Private Windows

### ISSUE THREAD

**Issue by electricmessiah** [gildas-lormeau/SingleFile#358] opened 2020-02-14 17:23 UTC
I have Firefox setup to always use Private Browsing mode, so all of my extensions require the "Enable in Private Windows" setting to be on before they appear in the toolbar. This extension icon refuses to show up. I've tried resetting, re-download, disable all other addons, etc. No dice.

The context menu option is present, and it works fine.

**Comment by gildas-lormeau** [comment] 2020-02-14 19:00
I don't know the cause of this issue and I cannot reproduce it. It might be a bug in Firefox. Here is a screenshot showing the icon SingleFile in a private window. The extension works as expected on my end. Just after starting the browser, do you see any error at the bottom of this page? `about:devtools-toolbox?type=extension&id=%7B531906d3-e22f-4a6c-a102-8057b88a1a63%7D`

![image](https://user-images.githubusercontent.com/396787/74559267-41f32880-4f64-11ea-95ab-c1dd2fb871da.png)

**Comment by gildas-lormeau** [comment] 2020-02-22 18:26
I'm closing this issue because I can't reproduce it and I did not get any response from you. Feel free to reopen it if necessary.

**Closed** 2020-02-22 18:27 UTC
