### ISSUE TITLE
Mootools breaks SingleFile CLI

### ISSUE THREAD

**Issue by nubela** [gildas-lormeau/SingleFile#351] opened 2020-02-05 04:16 UTC
**Describe the bug**
Got an error when crawling via SingleFile CLI (with Chrome Driver)

**To Reproduce**
1. Run this command on a Mac OSX environment (should also be reproduced on any other env with Chrome driveR)

```
$ ./single-file https://forums.hardwarezone.com.sg/eat-drink-man-woman-16/30s-40s-chitchat-club-part-49-a-6189101.html --browser-executable-path /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
```

**Expected behavior**
Page to crawl. (But it does not)

**Screenshots**
```
$ ./single-file https://forums.hardwarezone.com.sg/eat-drink-man-woman-16/30s-40s-chitchat-club-part-49-a-6189101.html --browser-executable-path /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

(node:80807) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'children' of undefined
    at <anonymous>:6596:65
    at Array.map (<anonymous>)
    at Processor.processStylesheets (<anonymous>:6595:51)
    at Runner.executeTask (<anonymous>:5794:39)
    at <anonymous>:5775:18
    at Array.map (<anonymous>)
    at Runner.executeStage (<anonymous>:5767:68)
    at Runner.initialize (<anonymous>:5687:32)
    at async SingleFileClass.run (<anonymous>:5543:4)
    at async Object.getPageData (<anonymous>:60:4)
    at ExecutionContext._evaluateInternal (/Users/nubela/Workspace/edmw-crawler/SingleFile/cli/node_modules/puppeteer-core/lib/ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/nubela/Workspace/edmw-crawler/SingleFile/cli/node_modules/puppeteer-core/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/nubela/Workspace/edmw-crawler/SingleFile/cli/node_modules/puppeteer-core/lib/DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/nubela/Workspace/edmw-crawler/SingleFile/cli/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Page.evaluate (/Users/nubela/Workspace/edmw-crawler/SingleFile/cli/node_modules/puppeteer-core/lib/Page.js:858:43)
    at Page.<anonymous> (/Users/nubela/Workspace/edmw-crawler/SingleFile/cli/node_modules/puppeteer-core/lib/helper.js:112:23)
    at getPageData (/Users/nubela/Workspace/edmw-crawler/SingleFile/cli/back-ends/puppeteer.js:91:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:80807) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:80807) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Environment**
 - Mac OSX
 - Chrome
 - node v10.15.2

**Comment by gildas-lormeau** [comment] 2020-02-05 14:44
I confirm I can reproduce the issue. This is due to the library [MooTools](https://github.com/mootools/mootools-core) included in this page. The library overrides the native method `Array.from` but is unable to implement it properly. The behavior is invalid when a `Map` or and `Iterator` object is passed as parameter. 
Currently, I don't know how to circumvent this bug introduced by MooTools... I would hope developers would stop developing and using this kind of library in 2020.

**Comment by gildas-lormeau** [comment] 2020-02-05 15:15
the issue is fixed in the latest update.

**Closed** 2020-02-05 15:14 UTC
