### ISSUE TITLE
Wikipedia page cannot open under self-extracting ZIP format (Cent browser)

### ISSUE THREAD

**Issue by gghrgr** [gildas-lormeau/SingleFile#1252] opened 2023-10-05 02:28 UTC
Seems something wrong with the 3rd step while saving, it was complete after step 2, and the file cant open, just blank

**Comment by gildas-lormeau** [comment] 2023-10-05 04:53
I cannot reproduce the issue. Did you change any option in SingleFile?

You can export your settings in the options page and post the file here if necessary.

**Comment by gildas-lormeau** [comment] 2023-10-07 23:58
Thank you, unfortunately I was not able to reproduce the issue. Could you try to reset your settings to see if it helps? You can import them again after the test.

**Comment by gghrgr** [comment] 2023-10-10 20:19
Thanks, I tried reset, and disable all other extensions, still didn't work, I wonder whats so special about the wikipedia page in my chrominium based "Cent browser", anyway, it works fine with edge, I would go with edge to save wikipedia page

**Comment by gildas-lormeau** [comment] 2023-10-10 20:50
This might be due to the encoding of the page. The HTML content of universal self-extracting ZIP uses "windows-1252" as encoding (instead of utf-8 for example). This is needed in order to read the binary content in the page from the DOM. Maybe "Cent browser" does not support this encoding.

**Comment by gildas-lormeau** [comment] 2024-07-11 21:34
I'm closing this issue because it looks like it was specific to Cent browser and I'm not sure it's still relevant.

**Closed by gildas-lormeau** 2024-07-11 21:34 UTC
