### ISSUE TITLE
Enrichment with browser history visit data

### ISSUE THREAD

**Issue by mpeteuil** [gildas-lormeau/SingleFile#608] opened 2021-02-03 01:03 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to tie browser history with a SingleFile archive file, but I'm struggling to do so in a more exact way. What I'd love is to be able to match a `visitId` ([firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history/VisitItem), [chrome](https://developer.chrome.com/docs/extensions/reference/history/#type-VisitItem), etc.) to an archive without ambiguity. It seems like by the time SingleFile is archiving the page the `visitId` is already known and it would be great to expose that somehow.

**Describe the solution you'd like**
Ideally SingleFile would have the option of putting the history `visitId` or other history visit information in the [template variables](https://github.com/gildas-lormeau/SingleFile/blob/a48e037754fb7874a7bf1013bd619e7a2620a24d/extension/ui/pages/help.html#L571-L644) or an option to write it into the archive itself.

**Describe alternatives you've considered (optional)**
Right now since I'm using the default SingleFile archive naming scheme in a sub-directory of downloads (`SingleFile/{page-title} ({date-iso} {time-locale}).html`) I do fuzzy matching on the archive page title (filename minus the timestamp) with the visit page title and look within a small time window. The problem is a lot of pages have the same title even though the content changes. For example this Github issues page is always called **Issues • gildas-lormeau/SingleFile** even if you're looking at open tickets or closed tickets or on page 5 or 10 or anything like that. It's possible I could switch to urls somehow, but tying visits to an archive directly via something like the `visitId` I believe is the best solution in my case. I'm open to hearing other alternatives though.

Currently using SingleFile 1.18.66

**Comment by gildas-lormeau** [comment] 2021-02-03 23:37
Thank you for the detailed explanation of why you would need a way to get the `visitId` in filenames. I understand the problem and the fact that this field is the most appropriate to dissociate the pages for you. The only problem, not blocking however, is that in order to get this information, SingleFile must ask for additional permission. This permission can be optional but requires a little development. I'll have to detect the use of the variable in the template and trigger the display of a consent popup to get the required permission. I just want to say that it's going to take some time.

**Comment by mpeteuil** [comment] 2021-02-04 13:23
Thanks for being open to the change, it would help me out a lot. I completely understand the permissions being a tricky issue to deal with. In the meantime I'm going to try switching to pulling the `url` and `saved date` out of the comment that SingleFile writes into each archive and see how that improves my matching of visits to archived files.

**Comment by gildas-lormeau** [comment] 2021-02-16 22:00
@mpeteuil Wouldn't a timestamp (time in ms) do the job?

**Comment by mpeteuil** [comment] 2021-02-20 22:59
Do you mean a more precise timestamp for when the archive is created? That would help, but I'm not sure it solves the problem completely. Since by nature there is a delay between the visit time and the archive time and the difference between those can be quite variable from my experience. For example, here is a distribution of the time difference between when a visit occurs and when it was archived (according to the timestamp in the SingleFile archive):

![singlefile-distribution-visit-to-archive-time](https://user-images.githubusercontent.com/459756/108610110-1689f180-73a1-11eb-811b-9e32993607a1.png)

Most of the time it's within 10 seconds after the visit, but there's a long tail on this (I capped it off at 60 for this). Related to this, since there aren't any guarantees about ordering it could be entirely possible that you have `visit_1`, `visit_2` and the timestamps end up such that `visit_2`'s timestamp is before `visit_1`s. If the URLs are the same in a case like that then you can't tell which archive belongs to which visit.

If it's simple enough to add though it certainly couldn't hurt to test. I'd have to start using it and get samples of what it looks like in practice to say for sure. If I'm missing the question intent here let me know and I'm happy to expand on this.

**Comment by gildas-lormeau** [comment] 2021-02-23 19:17
I did not think about the visit time actually. I think I could add a template variable returning its value in ms. i would also probably add a bunch of variables to get formatted values.

**Comment by gildas-lormeau** [comment] 2021-02-23 21:53
The version `1.18.68` I just uploaded on the stores includes some new variables to get the visit date/time info. The variables names are the same as the names defined for the saved time but prefixed with `visit-` (e.g. `visit-date-iso`). The new version also includes the variables `time-ms` and `visit-time-ms` to get, respectively,  the saved time and the visit time in ms since the Unix Epoch.

**Comment by xstnztk** [comment] 2021-02-24 11:02
Is it possible that this modification broke the existing date/time templates? I just got an update to 1.18.68 and now at least {date-iso} and {time-iso} are no longer replaced in the template, i.e. they are included literally as "{date-iso}" and "{time-iso}" in the filename. {page-title} is still replaced correctly, so it only seems to affect date/time templates. I can see that this commit moved the date/time templates into a separate function, so this seems plausible.

This happens on Firefox 85.0.1 on Linux (Fedora 33).

**Comment by xstnztk** [comment] 2021-02-24 11:17
I just made an attempt to replace `{date-iso}` and `{time-iso}` with the new `{visit-date-iso}` and `{visit-time-iso}`. The new ones work as expected, so it seems the commit broke indeed the old templates without the "visit-" prefix.

I am not much of a Javascript programmer but maybe it is necessary to pass an empty string "" as the prefix parameter to the `evalDate()` function at line 1468 in single-file-core.js instead of leaving it undefined?

**Comment by gildas-lormeau** [comment] 2021-02-24 11:34
Thank you for the test. The regression is very unfortunate. I uploaded a new version to fix it.

**Comment by gildas-lormeau** [comment] 2021-02-26 13:47
I'm closing this issue because I consider it as fixed. Feel free to reopen it if necessary.

**Closed by gildas-lormeau** 2021-02-26 13:47 UTC
Labels: feature request

**Comment by mpeteuil** [comment] 2021-02-26 16:01
Thanks! I'll have to use this for a little while to get an idea of how well it solves my problem, but I can report back on that later.

Is there a way to add this to the comment that SingleFile writes into the archive?

**Comment by gildas-lormeau** [comment] 2021-02-26 16:12
@mpeteuil Yes, you can use template variables in the comment as well.
