### ISSUE TITLE
cli can get stuck on some urls

### ISSUE THREAD

**Issue by user471** [gildas-lormeau/SingleFile#292] opened 2019-10-19 12:19 UTC
```
single-file https://til.cybertec-postgresql.com/post/2019-10-11-Object-preventExtension-vs-seal-vs-freeze/
```
just hangs and do nothing

**Comment by gildas-lormeau** [comment] 2019-10-19 20:42
I did some tests and I can conclude this is a bug in puppeteer. I can indeed reproduce this issue without executing any code related to SingleFile. However the option `browser-load-max-time` was not taken into account until now. I fixed this. It means that after waiting 60s, the capture of the page will be forced.

**Comment by gildas-lormeau** [comment] 2019-10-23 12:33
I'm closing this issue because it should be fixed now, even though there issue exists in puppeteer. Feel free to re-open it if, for example, you know another URL where the CLI could get stuck.

**Comment by user471** [comment] 2019-12-14 09:14
@gildas-lormeau another example
https://blog.soshace.com/building-a-telegram-bot-with-node-js/

**Comment by user471** [comment] 2019-12-14 12:16
also 
https://qio.netlify.com/docs/core/installation

**Comment by user471** [comment] 2019-12-14 12:18
also
https://qio.netlify.com/docs/core/installation

**Comment by gildas-lormeau** [comment] 2019-12-14 13:25
I could not reproduce your issue with https://blog.soshace.com/building-a-telegram-bot-with-node-js/ and https://qio.netlify.com/docs/core/installation by running `single-file <url>`. Did you pass any additional parameter? 

The value of `browser-load-max-time` is passed to [`page.goto`](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagegotourl-options) as the option `timeout` in Puppeteer. The documentation says that "page.goto will throw an error if [...] the timeout is exceeded during navigation.". So, the cli process should stop with an error when this delay is exceeded, otherwise I would be tempted to think it's a bug in Puppeteer.

**Comment by gildas-lormeau** [comment] 2019-12-14 13:32
My bad, I was wrong about `browser-load-max-time`. I don't know why, I was ignoring the timeout error. It's fixed now.

**Comment by user471** [comment] 2019-12-14 14:29
Thanks. Now i get TimeoutError, but something cli still can get stuck. The url is https://blog.soshace.com/building-a-telegram-bot-with-node-js/ I only use browser-executable-path. Maybe there is another place when it can get stuck or maybe page.goto timeout sometime doesn't work? Could you force process to exit after timeout without depend on page.goto?

**Comment by gildas-lormeau** [comment] 2019-12-14 14:41
Can you try to pass the option `--browser-wait-until=networkidle2` and tell me if helps. Did you update your npm packages?

**Comment by gildas-lormeau** [comment] 2019-12-14 14:59
If the "page.goto timeout" does not work, it may be a bug in SingleFile. I would prefer to fix it instead of using a max timeout if possible.

**Comment by user471** [comment] 2019-12-14 15:26
`--browser-wait-until=networkidle2` doesn't help.

**Comment by gildas-lormeau** [comment] 2019-12-14 22:37
Can you please go into the `cli` folder, run `npm update` and tell me if it helps.

**Comment by user471** [comment] 2019-12-16 16:37
npm update didn't help. Also `try` from puppeteer.js doesn't catch any errors after one minute, so it looks like page.goto timeout doesn't work.

**Comment by gildas-lormeau** [comment] 2019-12-16 18:34
Thank you for the update. Out of curiosity, do you think you could debug /cli/back-ends/puppeteer.js? If not, I'll try to implement a verbose mode in order to get more info about this strange issue.

**Comment by user471** [comment] 2019-12-18 16:28
There isn't much to debug. page.evaluate is called but its callback never executed and there isn't any error.

**Comment by gildas-lormeau** [comment] 2019-12-18 17:38
Thank you, that's interesting... If you can, please try to set `DEBUG = true` at line 26 in `lib/single-file/single-file-core`, run the cli tool with the option `--browser-debug=true` and paste here the content of the logs in the developer tools.

**Comment by user471** [comment] 2019-12-18 18:01
```
S-File <core>    **** STARTED STAGE 0 ****
VM6:7485 S-File <core>      -- STARTED task = preProcessPage
VM6:7485 S-File <core>      -- ENDED   task = preProcessPage delay = 2
VM6:7485 S-File <core>      -- STARTED task = replaceStyleContents
VM6:7485 S-File <core>      -- ENDED   task = replaceStyleContents delay = 1
VM6:7485 S-File <core>      -- STARTED task = resetCharsetMeta
VM6:7485 S-File <core>      -- ENDED   task = resetCharsetMeta delay = 1
VM6:7485 S-File <core>      -- STARTED task = insertFaviconLink
VM6:7485 S-File <core>      -- ENDED   task = insertFaviconLink delay = 1
VM6:7485 S-File <core>      -- STARTED task = replaceCanvasElements
VM6:7485 S-File <core>      -- ENDED   task = replaceCanvasElements delay = 0
VM6:7485 S-File <core>      -- STARTED task = insertFonts
VM6:7485 S-File <core>      -- ENDED   task = insertFonts delay = 0
VM6:7485 S-File <core>      -- STARTED task = insertShadowRootContents
VM6:7485 S-File <core>      -- ENDED   task = insertShadowRootContents delay = 0
VM6:7485 S-File <core>      -- STARTED task = setInputValues
VM6:7485 S-File <core>      -- ENDED   task = setInputValues delay = 3
VM6:7485 S-File <core>      -- STARTED task = removeScripts
VM6:7485 S-File <core>      -- ENDED   task = removeScripts delay = 17
VM6:7485 S-File <core>      -- STARTED task = removeUnselectedElements
VM6:7485 S-File <core>      -- ENDED   task = removeUnselectedElements delay = 1
VM6:7485 S-File <core>      -- STARTED task = insertVideoPosters
VM6:7485 S-File <core>      -- ENDED   task = insertVideoPosters delay = 3
VM6:7485 S-File <core>      -- STARTED task = removeFrames
VM6:7485 S-File <core>      -- ENDED   task = removeFrames delay = 1
VM6:7485 S-File <core>      -- STARTED task = removeVideoSources
VM6:7485 S-File <core>      -- ENDED   task = removeVideoSources delay = 2
VM6:7485 S-File <core>      -- STARTED task = removeAudioSources
VM6:7485 S-File <core>      -- ENDED   task = removeAudioSources delay = 1
VM6:7485 S-File <core>      -- STARTED task = removeDiscardedResources
VM6:7485 S-File <core>      -- ENDED   task = removeDiscardedResources delay = 3
VM6:7485 S-File <core>      -- STARTED task = removeHiddenElements
VM6:7485 S-File <core>      -- ENDED   task = removeHiddenElements delay = 3
VM6:7485 S-File <core>      -- STARTED task = resolveHrefs
VM6:7485 S-File <core>      -- ENDED   task = resolveHrefs delay = 5
VM6:7485 S-File <core>      -- STARTED task = resolveStyleAttributeURLs
VM6:7485 S-File <core>      -- ENDED   task = resolveStyleAttributeURLs delay = 61
VM6:7485 S-File <core>      // STARTED task = resolveStylesheetURLs
VM6:7485 S-File <core>      // STARTED task = resolveFrameURLs
VM6:7485 S-File <core>      // STARTED task = resolveHtmlImportURLs
VM6:7485 S-File <core>      // ENDED task = resolveHtmlImportURLs delay = 1
VM6:7485 S-File <core>      // ENDED task = resolveFrameURLs delay = 11
VM6:7485 S-File <core>      // ENDED task = resolveStylesheetURLs delay = 758
VM6:7485 S-File <core>    **** ENDED   STAGE 0 ****
VM6:7485 S-File <core>    **** STARTED STAGE 1 ****
VM6:7485 S-File <core>      -- STARTED task = removeUnusedStyles
VM6:7485 S-File <core>      -- ENDED   task = removeUnusedStyles delay = 2062
VM6:7485 S-File <core>      -- STARTED task = removeAlternativeMedias
VM6:7485 S-File <core>      -- ENDED   task = removeAlternativeMedias delay = 6
VM6:7485 S-File <core>      -- STARTED task = removeUnusedFonts
VM6:7485 S-File <core>      -- ENDED   task = removeUnusedFonts delay = 47
VM6:7485 S-File <core>      // STARTED task = processStylesheets
VM6:7485 S-File <core>      // STARTED task = processStyleAttributes
VM6:7485 S-File <core>      // STARTED task = processPageResources
VM6:7485 S-File <core>      // STARTED task = processScripts
VM6:7485 S-File <core>      // ENDED task = processScripts delay = 14
VM6:7485 S-File <core>      // ENDED task = processStyleAttributes delay = 80
VM6:7485 S-File <core>      // ENDED task = processPageResources delay = 4928
VM6:7485 S-File <core>      // ENDED task = processStylesheets delay = 11506
VM6:7485 S-File <core>    **** ENDED   STAGE 1 ****
VM6:7485 S-File <core>    **** STARTED STAGE 2 ****
VM6:7485 S-File <core>      -- STARTED task = removeAlternativeImages
VM6:7485 S-File <core>      -- ENDED   task = removeAlternativeImages delay = 3
VM6:7485 S-File <core>      // STARTED task = removeAlternativeFonts
VM6:7485 S-File <core>      // STARTED task = processFrames
VM6:7485 S-File <core>      // STARTED task = processHtmlImports
VM6:7485 S-File <core>      // ENDED task = processHtmlImports delay = 1
VM6:7485 S-File <core>      // ENDED task = processFrames delay = 6
VM6:7485 S-File <core>      // ENDED task = removeAlternativeFonts delay = 1425
VM6:7485 S-File <core>    **** ENDED   STAGE 2 ****
VM6:7485 S-File <core>    **** STARTED STAGE 3 ****
VM6:7485 S-File <core>      -- STARTED task = replaceStylesheets
VM6:7485 S-File <core>      -- ENDED   task = replaceStylesheets delay = 42
VM6:7485 S-File <core>      -- STARTED task = replaceStyleAttributes
VM6:7485 S-File <core>      -- ENDED   task = replaceStyleAttributes delay = 6
VM6:7485 S-File <core>      -- STARTED task = insertVariables
VM6:7485 S-File <core>      -- ENDED   task = insertVariables delay = 0
VM6:7485 S-File <core>      -- STARTED task = compressHTML
VM6:7485 S-File <core>      -- ENDED   task = compressHTML delay = 77
VM6:7485 S-File <core>      -- STARTED task = cleanupPage
VM6:7485 S-File <core>      -- ENDED   task = cleanupPage delay = 1
VM6:7485 S-File <core>      // STARTED task = insertMAFFMetaData
VM6:7485 S-File <core>      // STARTED task = setDocInfo
VM6:7485 S-File <core>      // ENDED task = insertMAFFMetaData delay = 2
VM6:7485 S-File <core>      // ENDED task = setDocInfo delay = 2
VM6:7485 S-File <core>    **** ENDED   STAGE 3 ****
```
It looks like it works with --browser-debug=true

**Comment by gildas-lormeau** [comment] 2019-12-18 18:37
Thank you. These logs show SingleFile was able to execute all the code without any error. I was not expecting this since you said the promise returned by `page.evaluate` is never resolved. I'm really wondering what's happening. Right now it's not clear for me at all. If you remove `return pageData;` at line 96 in `puppeteer.js`, is the promise resolved?

**Comment by gildas-lormeau** [comment] 2019-12-18 18:40
Sorry, I did not see your last comment. I think I need to write something to dump the logs into the terminal and see if it makes any difference when running the browser in headless mode.

**Comment by gildas-lormeau** [comment] 2019-12-20 15:37
@user471, I just fixed a similar issue. Could you please try to reproduce the issue with the latest version of SingleFile please?

**Comment by user471** [comment] 2019-12-20 17:10
this fix didn't help. You could try https://scala.monster/ as another example

**Comment by gildas-lormeau** [comment] 2019-12-20 20:54
Unfortunately, I was able to save https://scala.monster/ without any particular issue. Do you use some "low-level" content blockers like DNS blockers?

**Comment by gildas-lormeau** [comment] 2019-12-20 22:31
I have some news. It looks like I am able to reproduce the issue on an older computer (haswell core i7).

**Comment by gildas-lormeau** [comment] 2019-12-20 22:47
My bad, the old computer was on Win 10 Pro 1903. I updated it to 1909, installed again the NPM packages (not sure it's needed) and the issue disappeared...

**Comment by user471** [comment] 2019-12-21 09:34
>Do you use some "low-level" content blockers like DNS blockers or anything similar?

No I don't. 
I tried to downgrad puppeteer to 1.20 and it seems to fix the problem with these urls.

**Comment by gildas-lormeau** [comment] 2019-12-21 09:45
Thank you. Feel free to open an issue in the  Puppeteer repository if you can reproduce the issue without relying on SingleFile. I'm closing this one.

**Closed by gildas-lormeau** 2019-12-21 09:45 UTC
