### ISSUE TITLE
Some pages are blanked when saved with SingleFile (not with SavePage ME)

### ISSUE THREAD

**Issue by abolibibelot1980** [gildas-lormeau/SingleFile#283] opened 2019-10-02 14:23 UTC
**Describe the bug**
On a few websites, when I try to save a page with SingleFile, the page suddenly goes blank, or grey, or an error message appears, and the resulting saved page is erroneous. For the same page, saving with SavePage ME works normally (on some other websites the situation is reversed : SavePage hangs indefinitely while SingleFile manages to finish the process and save the page as intended).

**To Reproduce**
This page turned to grey when I tried to save it (on 2019/10/02) :
https://bleacherreport.com/articles/2838876-ric-flair-its-a-miracle-im-alive-after-medical-emergency-cites-18m-bill
On this website, when running a search for a car sharing trip between two cities on a particular date, then trying to save the result, it displayed an error message “Une erreur est survenue” (on 2019/09/26) :
https://www.blablacar.fr/search-car-sharing
See the provided sample files (same page saved with both SingleFile and SavePage ME).

**Expected behavior**
It should save the page as it is without touching it whatsoever.

**Screenshots**
See HTML samples in the attached ZIP file.

**Environment**
 - Windows 7
 - Firefox 69

**Additional context**
-

[SingleFile bug report.zip](https://github.com/gildas-lormeau/SingleFile/files/3681544/SingleFile.bug.report.zip)

**Comment by gildas-lormeau** [comment] 2019-10-02 16:43
The issue is related to the "load deferred images" option. I'll try to see what I can do to circumvent the issue on these particular websites. Meanwhile, you can disable this option but you may need to scroll down when saving pages. You can also create a profile without the option enabled and associate it to these domains.

**Comment by gildas-lormeau** [comment] 2019-10-02 18:29
Please let me know if the version 1.11.58 I just published fixes your issues. You need to reset your options before testing the fix and you don't need to disable the "save deferred images" option.

**Comment by gildas-lormeau** [comment] 2019-10-03 09:41
I was able to reproduce the issue on https://www.blablacar.fr and I confirm this was the same type of issue. It's also fixed now. The only thing you have to do is resetting your settings of SingleFile.

**Closed by gildas-lormeau** 2019-10-03 09:41 UTC

**Comment by gildas-lormeau** [comment] 2020-01-30 16:10
Please make sure that your options are reset.
