### ISSUE TITLE
Support Scrolling in iFrame or Code Content

### ISSUE THREAD

**Issue by devKshitijJain** [gildas-lormeau/SingleFile#383] opened 2020-03-27 06:34 UTC
Currently if there is code present and horizontal and vertical scrolling is present. It won't capture that code.

**Comment by gildas-lormeau** [comment] 2020-03-27 13:02
Can you please give me an example of URL illustrating this issue?

**Comment by devKshitijJain** [comment] 2020-03-27 20:17
https://www.educative.io/courses/grokking-the-object-oriented-design-interview/RMlM3NgjAyR . You can check here. I am talking about the code blocks

**Comment by gildas-lormeau** [comment] 2020-03-27 23:59
Thank you. The problem is that the code blocks are not displayed into iframes. These are pseudo-iframe divs dependent on JavaScript. That's why the scrolling behavior is broken when saving the page. However, if the page was using real iframes, that would work fine.

**Comment by devKshitijJain** [comment] 2020-03-29 17:59
Is there any way to fix it?

**Comment by gildas-lormeau** [comment] 2020-03-29 19:43
It depends on what library is used to format the code. Your example is using [Monaco](https://microsoft.github.io/monaco-editor/). It looks like Monaco does not offer an API accessible from SingleFile to resize the editor or to retrieve the content displayed in the editor. So, I don't see how to fix the issue.

**Comment by devKshitijJain** [comment] 2020-03-29 20:23
Got it. Thanks for taking time to dig it in.

**Comment by gildas-lormeau** [comment] 2020-04-01 10:28
You're welcome! I'm closing this issue since I cannot fix it.

**Closed by gildas-lormeau** 2020-04-01 10:28 UTC

**Comment by devKshitijJain** [comment] 2020-04-11 00:29
@gildas-lormeau Hey, was thinking is there anyway to block js or something that loads up this editor?

**Comment by gildas-lormeau** [comment] 2020-04-11 11:20
@devKshitijJain Indeed, this should be possible via a user script.

For this, you must install an extension like TamperMonkey or GreaseMonkey and add the userscript below. You have also to enable the hidden option `userScriptEnabled` by exporting the settings from the options page of SingleFile, editing the JSON file, replacing `userScriptEnabled: false` with `userScriptEnabled: true`, and importing the modified file in SingleFile. Make also sure the userscript  is enabled.

Note that it will work if and only if the editors are not visible without scrolling the page. You will also need to disable the option "Images > save deferred images" in SingleFile. Finally, make sure the userscript extension is enabled.

```
// ==UserScript==
// @name         Remove Monaco editor instances
// @namespace    https://github.com/gildas-lormeau/SingleFile
// @version      1.0
// @description  [SingleFile] Remove Monaco editor instances
// @author       Gildas Lormeau
// @match        *://*/*
// @noframes
// @grant        none
// ==/UserScript==


(() => {

  dispatchEvent(new CustomEvent("single-file-user-script-init"));

  addEventListener("single-file-on-before-capture-request", () => {
    document.querySelectorAll(".code-container")
      .forEach(containerElement => 
        containerElement.parentNode.replaceChild(containerElement.cloneNode(true), containerElement));
  });

})();
```

**Comment by devKshitijJain** [comment] 2020-04-11 13:55
Thanks I will try it. And yes the editor loads up only when I scroll to code block and not before that.

**Comment by devKshitijJain** [comment] 2020-04-11 17:51
@gildas-lormeau Amazing that worked like charm. Although I have seen that above script only work after I click on SingleFile and even after I scroll down the editor won't load. Is there any way that this can be done by default? I mean just load the page and it works out of the box.

**Comment by gildas-lormeau** [comment] 2020-04-11 21:27
Maybe this script would be okay for you?  It replaces the editors as soon as possible.

```
// ==UserScript==
// @name         Remove Monaco editor instances
// @namespace    https://github.com/gildas-lormeau/SingleFile
// @version      1.0
// @description  Remove Monaco editor instances
// @author       Gildas Lormeau
// @match        *://*/*
// @noframes
// @runt-at      document-end
// @grant        none
// ==/UserScript==


(() => {

    const observer = new MutationObserver(mutations => {
        const containerElements = mutations
            .map(mutation => mutation.target.querySelector(".code-container:not(.code-container-processed)"))
            .filter(containerElement => containerElement);
        if (containerElements.length) {
            containerElements.forEach(containerElement => {
                const newContainerElement = containerElement.cloneNode(true);
                newContainerElement.classList.add("code-container-processed");
                if (containerElement.parentNode) {
                    containerElement.parentNode.replaceChild(newContainerElement, containerElement);
                }
            });
        }
    });
    observer.observe(document.body, { subtree: true, childList: true });

})();
```

**Comment by devKshitijJain** [comment] 2020-04-11 22:29
@gildas-lormeau Amazing that worked. Thanks a lot for putting your time in it :)

**Comment by gildas-lormeau** [comment] 2020-04-11 22:58
@devKshitijJain You're welcome :)

**Comment by devKshitijJain** [comment] 2020-04-20 11:40
Hey @gildas-lormeau . It's me again bothering you for something :) It worked for other part but there is something where it doesn't work. On this page https://www.educative.io/courses/python-3-an-interactive-deep-dive/xV9Kjm0m26n  if this script is enabled it will show blank space

![image](https://user-images.githubusercontent.com/13154652/79747648-ae562380-8329-11ea-9317-a1cc31d0d095.png)

**Comment by devKshitijJain** [comment] 2020-05-02 00:21
Hey @gildas-lormeau. How are you? There is functionality in this plugin that converts `xlink:href` link to `data url` for svg's. Could you please help me getting abstract of that code?
