### ISSUE TITLE
SingleFile v1.10.68 break redirect on VirusTotal.com

### ISSUE THREAD

**Issue by XX-J** [gildas-lormeau/SingleFile#219] opened 2019-05-22 20:49 UTC
**Describe the bug**
 After check hash or upload the file on https://www.virustotal.com/gui/ , site VirusTotal.com don't redirect to summary page (i.e. virus check does not occur).

**To Reproduce**
1. Go to https://www.virustotal.com/gui/
2. Click on 'Choose file' and choose any file
3. After 'Checking hash...' appear 'Confirm upload'
4. Push 'Confirm upload' and wait uploading
5. After uploading file appear 'Uploading 100%' and end (without redirection)

**Expected behavior**
 After check hash or upload the file on https://www.virustotal.com/gui/ , site VirusTotal.com automatically redirect to summary page.

**Screenshots**
![2019 05 22-1](https://user-images.githubusercontent.com/17948007/58206351-2ca8e080-7ce9-11e9-9fc0-bdf3c483643c.png)

**Environment**
 - OS: Win7 SP1 x64
 - Browser: Mozilla Firefox v53.0.3
 - SingleFile: v1.10.68

**Comment by gildas-lormeau** [comment] 2019-05-22 21:34
I cannot reproduce this issue on the latest versions of Firefox and Chrome. I did not do the test on Firefox 53.0.3 yet. Could you please confirm that if you disable the extension before doing this test, this issue does not occur?

**Comment by gildas-lormeau** [comment] 2019-05-22 22:11
I was able to reproduce the issue in Firefox 50.0.3. I should be fixed in the version 1.10.69 I just published.

**Closed by gildas-lormeau** 2019-05-22 22:11 UTC

**Comment by XX-J** [comment] 2019-05-22 22:31
Thanks a lot. All working.
Your extension is super!

**Comment by gildas-lormeau** [comment] 2019-05-22 22:40
Thanks :)
