### ISSUE TITLE
SingleFile extension freezes browser when you minimized the window

### ISSUE THREAD

**Issue by yuis-ice** [gildas-lormeau/SingleFile#778] opened 2021-09-11 14:33 UTC
**Describe the bug**
SingleFile extension freezes browser when you minimized the window while SingleFile is saving the page. 
When it happens the window turns to a white header-less window inaccessible that apparently you can tell it is freezing, and it affects other windows of the same browser instance, making the browser useless unless force killing of the process. 

**Environment**
Windows 10 Pro; Brave, latest

**Comment by gildas-lormeau** [comment] 2021-09-11 22:28
I cannot reproduce the issue. Do you know how to reproduce it?

**Comment by yuis-ice** [comment] 2021-09-12 00:39
I don't know.. The only things I knew at that moment are as described above and additionally, maybe some high CPU, many tabs (300+), minimizing the window relatively immediately (<1000ms or so) using the shortcut key win-down arrow, at that moment.

**Comment by yuis-ice** [comment] 2021-09-13 23:15
I think I've found the issue. I used the extension and reproduced the issue on "amazon.co.jp" , example url "https://www.amazon.co.jp/dp/B007PAFFLM" , and clicking something like "New (8) From" on the page, showing the list of sellers of the item, and did the save using the extension. 

Now, you should be able to see it freezes browser after some steps (like on the step 2/3). minimizing is not relevant. It freezes the browser if you tried to save that page.

**Comment by gildas-lormeau** [comment] 2021-09-13 23:57
I performed the test you described in the latest version of Brave and was able to save the page without any problems. I did the same test in Firefox and "step 2/3" took a little longer but the page was saved correctly in the end. Step 2 is the downloading the external resources. Sometimes this can take a while if the server is slow or down.

**Comment by gildas-lormeau** [comment] 2021-09-17 22:52
@yuis-ice I fixed this issue https://github.com/gildas-lormeau/SingleFile/issues/780 which could be maybe fix this one as well. Please let me know if you can still reproduce this issue once the extension updated (version `1.19.9`)

**Comment by gildas-lormeau** [comment] 2021-09-27 21:36
This issue should be fixed now. Feel free to reopen the issue if this is not the case.

**Closed by gildas-lormeau** 2021-09-27 21:36 UTC
