### ISSUE TITLE
The addon icon is changed to gray, I can't click to use it.

### ISSUE THREAD

**Issue by nomosaic** [gildas-lormeau/SingleFile#128] opened 2019-01-06 01:49 UTC
OS: win7 x64
browser: Waterfox x64 56.2.6
addon version: 1.9.29

**Comment by gildas-lormeau** [comment] 2019-01-06 12:13
Thanks for reporting the issue. I tested the version 1.9.29 of SingleFile on Waterfox 56.2.6 (64 bits)/Win 10 Pro and I cannot reproduce the issue. I can for example save https://github.com/gildas-lormeau/SingleFile without any particular issue. Can you confirm you tried to troubleshoot the issue as described here: https://github.com/gildas-lormeau/SingleFile#troubleshooting-unknown-issues?

**Comment by gildas-lormeau** [comment] 2019-01-06 16:20
I can reproduce the issue actually. I'm looking what's wrong.

**Comment by gildas-lormeau** [comment] 2019-01-06 16:42
The issue should be fixed in version 1.9.31. Please confirm it works for you.

**Closed** 2019-01-07 18:05 UTC
