### ISSUE TITLE
Looks like Brave has broken SingleFile

### ISSUE THREAD

**Issue by rgnixon** [gildas-lormeau/SingleFile#174] opened 2019-03-16 00:24 UTC
I'm using Brave (Dev version). Version 0.63.9 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
SingleFile goes ERR on every site now. Was fine a week ago,

![singlefile_broken](https://user-images.githubusercontent.com/28893310/54468156-c8503900-47ee-11e9-8851-18b4fa27895e.jpg)

**Comment by gildas-lormeau** [comment] 2019-03-16 00:43
@rgnixon Thanks for reporting the issue. I did not know SingleFile could run on Brave. I'll do some tests to see what's wrong.

**Comment by gildas-lormeau** [comment] 2019-03-16 00:48
@rgnixon I did a quick test and it works fine for me. Did you change any option?

**Comment by rgnixon** [comment] 2019-03-16 03:08
No options changed. Tried rebooting. Tried turning off shields etc.
Note that this is the Brave (Dev) version.

**Comment by gildas-lormeau** [comment] 2019-03-16 17:36
@rgnixon I just did another test with Brave Dev (0.63.11 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)) and it works fine for me. Can go to https://example.com/, save the page, press F12 and tell me if you see an error message in the debugger console (click on "Console" tab)?

**Comment by rgnixon** [comment] 2019-03-16 18:13
Console has this:

DomDistiller debug level: 0
                   VM72:140
2 Failed to load resource: the server responded with a status of 404 ()
 /favicon.ico:1

Ross

**Comment by rgnixon** [comment] 2019-03-16 18:19
UPDATE:

I've successfully saved a page that wouldn't save yesterday. I can't
explain that. Have done no updates of anything.

Ross

**Comment by gildas-lormeau** [comment] 2019-03-16 18:25
That's weird... Since it cannot be reproduced anymore, I'm closing the issue. Feel free to re-open it if the problem comes back.

**Closed by gildas-lormeau** 2019-03-16 18:25 UTC
