### ISSUE TITLE
Question about cli parameter "browser-load-max-time" behavior

### ISSUE THREAD

**Issue by beefdrifter** [gildas-lormeau/SingleFile#592] opened 2021-01-13 14:51 UTC
Hi there, I'm noticing that the time it takes for the cli to save a page is affected by the args.js parameter "browser-load-max-time".

For example, the page below takes about 5 secs to save if I use the firefox browser extension, but if my browser-load-max-time is set to 10 minutes, that's how long it will take the cli to save it

https://www.ssh.com/ssh/windows/

My understanding of the parameter's description is that it sets the maximum amount of time it should wait for a page to load, so if the page loads sooner, it will not wait the full amount of time specified.

Is there any way I can save a page as soon as possible, while preventing the cli to give up too soon if a big page takes longer to load? Here's my args.js if that helps! Thanks!

![2021_0105_0520  args js](https://user-images.githubusercontent.com/49841893/104467725-a0e87400-55f1-11eb-8995-3111ccba3ecc.png)

**Comment by gildas-lormeau** [comment] 2021-01-19 21:39
Did you try to set the option `--browser-wait-until` to `load`? I guess this might help to capture pages. Actually `networkidle0` is broken today in webdriver. I should ignore it.

**Comment by beefdrifter** [comment] 2021-01-24 19:19
Hi, sorry I had a busy week! I did some testing today, but ended up with a slightly different issue. I'll try to describe what happened.

I first tried using `load` and it quickly saved the page without waiting for 10 mins, but the page looked different from the one saved with `networkidle0`.

Because it's been a while, I wasn't sure if this had something to do with the `browser-wait-until` setting, or if there were other variables involved. So I downloaded the latest SingleFile master archive, and used puppeteer instead.

After switching to puppeteer, I tried multiple pages, and the results were quick and accurate. However, I still don't quite understand what `browser-load-max-time` does.

For example, using the same page I posted [before](https://www.ssh.com/ssh/windows/), if I set `browser-load-max-time` to 6000, it saves fine, but clearly takes longer than 6 seconds. However, if I set it to 1000, it would throw a timeout error.

Another [example](https://twitter.com/spoiler4you/status/1353393501136855040). If I set `browser-load-max-time` to 300, it would throw a timeout. However, if I set it to 600, it would save, but take around 60 seconds.

Final [example](https://twitter.com/doctorow/status/1352667082614132737). Again, 300 would throw a timeout, but this time, if I set it to 600, it completely hangs.

Is there a way to put a hard stop on how long SingleFile takes to save a page? I'm basically wondering if I can prevent it from hanging. I'll attach my current args.js below.

Thanks!

![2021_0125_0317  ](https://user-images.githubusercontent.com/49841893/105640931-14289a80-5ebc-11eb-836f-a3399a4fb8c5.png)

**Comment by gildas-lormeau** [comment] 2021-01-25 22:44
It was a bug. A timeout error should be ignored. I fixed it.

 The value you can pass is in ms and indicates the maximum time you want to wait. Note that SingleFile will try to wait until the state defined by `--browser-wait-until`, so if you pass a low value (< 3000), it will be ignored. A recommended value would be `30000` (30s). You should also maybe set `--browser-wait-until-fallback` to `false` if you really want to pass a low value, otherwise SingleFile will think it cannot load the page and will reload it but a lower `--browser-wait-until` value (e.g. it will try "networkidle0", then "networkidle2", then "load").

**Comment by beefdrifter** [comment] 2021-01-30 18:13
Ah, sorry I should have clarified that.
I was passing such a low value to see how `browser-load-max-time` worked
like I mentioned, it didn't seem to stop pages from taking longer to save.

> The value you can pass is in ms and indicates the maximum time you want to wait
So if I understand correctly, the parameter sets the limit for how long SingleFile will wait for a page to **_load_**
but there are no parameters that limit how long a page will take to **_save_**, correct?

If that's the case, is there any chance to add such a limit? I do remember going through earlier issues and reading that you would rather not have a hard limit?

Thanks!

**Comment by gildas-lormeau** [comment] 2021-01-31 21:27
> If that's the case, is there any chance to add such a limit? I do remember going through earlier issues and reading that you would rather not have a hard limit?
Do you mean that you are trying to save pages that are very large or very complicated and they take too much time to be processed by SingleFile? The time it takes to save the page should be acceptable, like in the extension. If not, this is a bug.

**Comment by beefdrifter** [comment] 2021-02-01 18:21
Yes, that's what I was trying to avoid. Strangely, I was going to mention the [example above](https://twitter.com/doctorow/status/1352667082614132737), which causes the CLI to hang when I save it, but after trying to save it again just now, it worked.

I guess if any irregular lengths of time should be treated as bugs, my question is a non issue then. I'll let you know if I come across any other page that takes longer than usual. Thanks again!

**Comment by gildas-lormeau** [comment] 2021-02-12 00:48
I confirm I was not able to reproduce the issue with the example you mentioned. Twitter is anyway very CPU intensive and I'm not really surprised it could cause some issues. The new option `--browser-wait-delay` I added in the last version might help though.

**Comment by gildas-lormeau** [comment] 2021-08-12 00:12
I'm closing this issue because I think it's fixed. Feel free to reopen it if necessary.

**Closed by gildas-lormeau** 2021-08-12 00:12 UTC
