### ISSUE TITLE
stretched images on reddit, only capturing first image of a album, and if there is a way to get thumbnails for html files or a html preview.

### ISSUE THREAD

**Issue by yellowbikewithbluehandles** [gildas-lormeau/SingleFile#1587] opened 2024-10-08 07:17 UTC
I have been going to reddit more often and have notice a couple things:
-stretched images on reddit images in the html that are saved with singlefile
-when there are multiple images in a album on a reddit thread it will only capture the first image.
-is there a way to get a thumbnail for html files or html preview to get thumbnails to know what I am clicking better?
-are there any good bookmarking solutions for tagging and using singlefile automatically that you might know of? I tried to use linkding but was running into reddit blocking and very hard to use because it doesn't allow for clicking local files to quickly go to the html file that is locally archived.

Also thank you so much for singlefile I have been using it for a while and I can say my life would be worse without it. There have been multiple times were I needed to save something like a website a very old person used to blog on about computer science and the person passed away and I used singlefile to save it so I can look at it forever and remember them and its the same for a family member which was something similar. So thank you so much for creating this it means so much to me!

**Comment by gildas-lormeau** [comment] 2024-10-10 14:02
Could you give me an example of page on reddit illustrating the issue(s) you're describing?

> Is there a way to get a thumbnail for html files or html preview [...]?

You could save pages as self-extracting files and enable "Embeb > page screenshot" (see the "File format" section). This will produce files that can be viewed in PNG. However, I do not know any software (e.g. a file explorer) which supports this feature. IIRC, Google Drive can generate thumbnails so uploading pages on it could be an intereting alternative.
 
> Are there any good bookmarking solutions for tagging and using singlefile automatically that you might know of? [...]

Did you try Zotero and its web-extension Zotero Connector? Here is a list of tools using or compatible with SingleFile: https://github.com/gildas-lormeau/SingleFile?tab=readme-ov-file#projects-usingcompatible-with-singlefile

**Comment by yellowbikewithbluehandles** [comment] 2024-10-11 02:02
https://www.reddit.com/r/aww/comments/1g0jpux/my_new_friend_chuckie
if you got to this and use singlefile you will see the image gets stretched out for some reason. There are other weird cases where even if no blackbars it will still stretch it, I will find them and post more examples but I want to post this for now for you to be able to see a example. 

Also zotero is fine but their connector I've been trying to make work for months and what happens is that reddit for example blocks it or doesn't capture the images or doesn't capture the whole and its been so frustrating. So I've been drag and dropping the singlefiles but its so tedious I wish there was a way to automatically do this but zotero was saying they wouldn't allow a watch a folder function because its not part of their philosophy. So I'm just trying to figure out what is even possible and would work for my use case. But other then that thank you so much!

**Comment by yellowbikewithbluehandles** [comment] 2024-10-11 02:11
this is the page
![image](https://github.com/user-attachments/assets/b39e0e5e-449d-4661-b820-fcb9854e64fe)
this is after singlefile
![image](https://github.com/user-attachments/assets/67eac3d2-d6bf-47c6-a03c-eb428f989c61)

**Comment by gildas-lormeau** [comment] 2024-10-11 07:40
Thank you, I was able to reproduce and fix the issue in the example. The fix will be available in the next version. Regarding Zotero, I guess the issue is that they haven't updated the SingleFile code in their extension. There have been quite a few changes to make saving pages on Reddit faster recently.

**Comment by yellowbikewithbluehandles** [comment] 2024-10-11 20:43
1.Wow that was so fast haha. I am seeing the last release was in march? Would the next release take a couple more months?
2. Is there a solution in the horizon for reddit multiple image albums?

3.Also I am pretty much computer code illiterate and I am getting extreme anxiety looking at all your amazing tools and same with others tools and scared that one day you all will stop fixing or maintaining these things. For things like singlefile can you give me advice what I should be learning to be able to maintain something like that? Because without it I think my life would be 20,000% harder. Even if its not to maintain but at least if I see some problems if I could test for things myself and explain myself to you what would your recommendations for learning specifically for singlefile? Thank you!

**Comment by gildas-lormeau** [comment] 2024-10-14 14:54
Could you please provide a link illustrating the (2) issue?

If you want to be able to maintain SingleFile, you have to know quite well the HTML and the CSS specifications actually. See for example :
 - https://developer.mozilla.org/en-US/docs/Web/HTML
 - https://developer.mozilla.org/en-US/docs/Web/CSS

You also need to know how to use the Developer tools in the browser in order to test and debug issues.

**Comment by yellowbikewithbluehandles** [comment] 2024-10-15 02:16
https://www.reddit.com/r/aww/comments/1g3rncn/my_god_you_look_like_a_hot_dog/
This link has a album and is the problem I'm talking about. It only captures the first image but not the whole album.

And also for the maintaining singlefile thing so I should be learning html and css and javascript?

And thanks again for everything!

**Comment by gildas-lormeau** [comment] 2024-10-30 14:53
Sorry for the late reply. I confirm unfortunately that albums cannot be saved with SingleFile because they rely on JavaScript. Regarding the maintenance of an extension, you need indeed to have a good knowledge of JavaScript (and the DOM API). I'm closing the issue because i fixed what I could. Feel free to comment it though.

**Closed by gildas-lormeau** 2024-10-30 14:53 UTC
Labels: feature request
