### ISSUE TITLE
Page too big to be downloaded?

### ISSUE THREAD

**Issue by tchflws** [gildas-lormeau/SingleFile#126] opened 2018-12-28 10:02 UTC
**Describe the bug**
I have a page that does not get saved by Single File.

**To Reproduce**
Go to
https://steamcommunity.com/sharedfiles/filedetails/?id=1413523717

and wait till the page has loaded completely. Save this page with single file

**Expected behavior**
The page should be saved to my designated folder as has worked already with countless other pages.

**Environment**
 - OS: Win10 Pro
 - Browser: Firefox
 - Version: 64.0

**Additional context**
I've saved the page successfully to PDF but the layout gets messed up. The PDF has 200 MB, maybe that's the problem for Single File? I also was unable to save it entirely as an imgage with the Screengrab extension...

**Comment by gildas-lormeau** [comment] 2018-12-28 11:38
Thanks for reporting the issue, indeed the weight of the page seems to make the download of the page impossible when done in background. However, I was able to save the page by unchecking "misc > save pages in background". The saved page weights 268MB.

**Comment by tchflws** [comment] 2018-12-29 10:51
Thanks for looking in to this but unfortunately even with  "misc > save pages in background" unchecked it does not work for me. I do see Step 3 / 3 being ticked and also an OK over the SingeFile icon but there's no file saved to the folder. The file is there when I save another page like this one.

**Comment by gildas-lormeau** [comment] 2018-12-29 21:40
You're right. I forgot to mention I was using [Firefox Developer Edition](https://www.mozilla.org/fr/firefox/developer/) (65). With Firefox 64, I can't save the page but I was able to save it on 2 different machines with the option "save pages in background" unchecked. I would be great if you could do the same test and confirm me it works with Firefox 65 on your end.

**Comment by gildas-lormeau** [comment] 2018-12-29 23:50
update : since the version 1.9.22, you don't need to uncheck "Misc > save pages in background".

**Comment by tchflws** [comment] 2018-12-30 15:36
I've just tried it with 1.9.22 on my regular Firefox but it still does not work. Again, I do see Step 3 / 3 being ticked and also an OK over the SingeFile icon but there's no file saved to the folder. I've installed Firefox Developer Edition and saving from it does work. Weird.

**Comment by gildas-lormeau** [comment] 2018-12-30 16:38
Thank you very much for taking the time to do these tests. The issue on Firefox 64 is due to a lack of (RAM) memory when the extension tries to retrieve the whole page content. Unfortunately, I cannot do anything to fix it without altering the page itself (e.g. removing images). It looks like Mozilla improved things meanwhile though, and this issue does not exist anymore in Firefox 65. I keep this issue open until the official release of Firefox 65.

**Comment by tchflws** [comment] 2018-12-31 05:55
Thanks for taking the time to look into this and for fixing my typo ;) So far this page has been an outlier, I'll test this again once the regular version reaches 65.

**Comment by gildas-lormeau** [comment] 2019-01-06 21:50
I found the info that confirms the issue on Firefox 64, see https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/65#JavaScript.

`Strings now have a maximum length of 2**30 - 2 (~1GB) instead of 2**28 - 1 (~256MB) (bug 1509542).`

**Comment by tchflws** [comment] 2019-01-07 19:54
Nice!

**Comment by gildas-lormeau** [comment] 2019-01-29 14:41
I confirm the issue is fixed in Firefox 65 stable.

**Closed by gildas-lormeau** 2019-01-29 14:41 UTC
Labels: firefox bug
