### ISSUE TITLE
Tooltips don't displayed in saved page

### ISSUE THREAD

**Issue by alekssmitt** [gildas-lormeau/SingleFile#227] opened 2019-06-09 10:06 UTC
One of the reasons why I use "save raw page" option is because it can save tooltips.
here the example:
[#66 - Français ou européen _.zip](https://github.com/gildas-lormeau/SingleFile/files/3269408/66.-.Francais.ou.europeen._.zip)
and here the example with turned off option:
[#66 - Français ou européen _ (3).zip](https://github.com/gildas-lormeau/SingleFile/files/3269410/66.-.Francais.ou.europeen._.3.zip)

**Comment by gildas-lormeau** [comment] 2019-06-10 20:27
You mean the banner at the bottom of the page?

**Comment by gildas-lormeau** [comment] 2019-06-10 22:54
I forgot to mention that enabling "save raw page" disables also "remove hidden elements". This might explain why tooltips disappear.

**Comment by alekssmitt** [comment] 2019-06-11 07:11
> You mean the banner at the bottom of the page?

No



> I forgot to mention that enabling "save raw page" disables also "remove hidden elements". This might explain why tooltips disappear, and this is a feature in fact.

Quite the contrary - enabling "save raw page" enables "hidden elements"!!

**Comment by alekssmitt** [comment] 2019-06-11 07:23
Here's what's in the example above (# 66 - Français ou européen _ (3) .zip):

![Untitled 1](https://user-images.githubusercontent.com/36442471/59251475-8c344500-8c32-11e9-8085-559748f5e1d5.jpg)

Tooltips is there and they poping-up at the saved page!

**Comment by alekssmitt** [comment] 2019-06-11 07:43
If you are intrigued, you could have a better look at the code.

```html
<span class=tooltips title="a shortcut"><strong>un raccourci</strong></span> 

and without tooltip's title filled in:

<span class=tooltips title><strong>poser les bases</strong></span>

**Comment by gildas-lormeau** [comment] 2019-06-11 09:48
> > I forgot to mention that enabling "save raw page" disables also "remove hidden elements". This might explain why tooltips disappear, and this is a feature in fact.
> 
> Quite the contrary - enabling "save raw page" enables "hidden elements"!!

Indeed, I was meaning the opposite. I guess the JavaScript removes the tooltips. I don't know why because I cannot test this page.

**Comment by gildas-lormeau** [comment] 2019-06-11 22:09
By the way, I think you made the good choice. This is a good example where "save raw page" works as intended by disabling JavaScript. That's why I'm closing this issue. Thanks again!

**Closed by gildas-lormeau** 2019-06-11 22:09 UTC

**Comment by alekssmitt** [comment] 2019-06-12 08:47
> I guess the JavaScript removes the tooltips


JavaScript shows the tooltips. Anyway your app manage to convert quite complicated JavaScript into simple HTML retrieving data from cashed page!  And yet your app can't manage to do the same online?
I think this is the main reason for why it is failing on some websites like http://www.un4seen.com/
You will laugh, but this site does not want to be saved by "SingleFile" at all.

**Comment by gildas-lormeau** [comment] 2019-06-12 09:07
I was meaning JavaScript transforms title attributes to tooltips, I guess.
