### ISSUE TITLE
Websites using virtual scrollable lists are partially saved (e.g. Twitter)

### ISSUE THREAD

**Issue by yerlincaicedo** [gildas-lormeau/SingleFile#440] opened 2020-07-07 06:47 UTC
**Describe the bug**
My name is Yerlin Caicedo, I live in Colombia.
Initially I want to thank you for this wonderful tool.
I want to tell you that I am a police officer in my country, I am specifically dedicated to working in the cyber center that is dedicated to everything related to cybersecurity in my country.
Well, he used his tool in my daily activities to save information from social networks that can be deleted at any time, with this I can have the information available when I want it and it is very useful for my investigations.
Lately I have been presenting an error and that is that when I save the page with the extension, when I open it, it appears completely blank ...
I would like to know if it is due to the amount of information in the profiles.

**Expected behavior**
The whole page should appear and not blank as it is in my case.

**Screenshots**
Attached the screenshots of the error.

**Environment**
I always use windows 10 operating system.
I have tried in every

 possible way but I could not.
W10.

**Additional context**
![imagen 1 original](https://user-images.githubusercontent.com/67943931/86727581-2b23a000-bff1-11ea-85dd-7f6c4422b8a4.png)
![Imagen 2  error](https://user-images.githubusercontent.com/67943931/86727596-2e1e9080-bff1-11ea-9e63-9f2622210c7b.png)

PLEASE WATCH THIS VIDEO
https://drive.google.com/file/d/1AQ_hapKjupQG6u43aljQPCMiTOrUfNR2/view?usp=sharing

**Comment by gildas-lormeau** [comment] 2020-07-07 13:52
Hello Yerlin,

Thank you very much for your testimony and the detailed report. I am sincerely flattered to see that SingleFile is a tool that can help in the fight against cybercrime. 

The bug on Twitter is related to a recent modification which makes that only the last "n" tweets visible are actually present on the page. This way of doing things is often called "virtual list" or "virtual table". It is so called because, virtually, this list can be infinite without consuming too much RAM.

I have thought about this problem and I think I have a solution. It is not sexy but it seems to work. The principle is to apply a zoom factor so that all the content is displayed and save the page like this. This is similar to what the option "Images > save deferred images" does but the zoom factor remains while saving the page. Once saved, SingleFile removes this zoom factor so that the saved page is displayed normally.

I attached to this post a test version that implements this technique. Could you test it by installing it manually as described [here](https://github.com/gildas-lormeau/SingleFile#install) (cf 2nd paragraph) and tell me if it works as you would like (make sure "Images > save deferred images" is enabled)? If so, I will add an option in SingleFile.

[singlefile-extension-chromium.zip](https://github.com/gildas-lormeau/SingleFile/files/4885230/singlefile-extension-chromium.zip)

**Comment by gildas-lormeau** [comment] 2020-07-07 18:17
After doing some additional tests, I think the implementation is okay. A new option "Images > save deferred images > zoom out the page" will be added in the version 1.17.51. Enabling it should fix this issue.

**Comment by yerlincaicedo** [comment] 2020-07-08 01:05
Hello Gildas-Lormeau. 

I am sorry to tell you that we were practicing with the entire team the procedure that envies us and it was not possible to obtain the desired results, it only saves one part, clearly this is much better compared to the previous version.

When carrying out the conservation with this tool (https://github.com/gildas-lormeau/SingleFile/archive/master.zip.) We see that it zooms out and preserves a part of it, (NOT ALL), we try to do the I exercise by manually zooming out and preserving a bit more but NOT ALL.

The Browser only lets us zoom out up to 25%, with my team we believe that it may be the inconvenience, we ask you to help us try to correct this error.

I will send you a video executing all the steps, it may also be that we are not doing things right.

We are very grateful for the help you have given us so far, we would like to get to know you a little more.

You can get my phone number so that we can talk on WhatsApp +57 3214466028 or email yerlincaicedo@gmail.com, clearly if you want, attentive to your comments.

With my team we are evaluating and studying the possibility of making a videoconference regarding this topic, we are looking for the person who will translate for us from English to Spanish. So that we can understand each other.

Thank you so so so so so so so so so so so so much!

At the moment I am in the office, in a few hours I will arrive at the house to record the screen of my computer and send you a recording of how we are doing it.

Clearly you must forgive our English, we are using the google translator.

The person who speaks the language is on an office trip.

again thank you very much.

god bless you eternally.

**Comment by yerlincaicedo** [comment] 2020-07-08 03:51
https://drive.google.com/file/d/1K9MjahUd7I6hNhdZ6U7vLcejhRAXcLz7/view?usp=sharing

here is the video as I promised, I hope you can help us

**Comment by frostblazergit** [comment] 2020-07-08 08:09
Technically, similar to the way web content is rendered on Twitter, I don’t think it’s easy to solve this problem fundamentally.

If you want to save evidence, you can use screen recording or screenshot software to record tweets.

If the user deletes a tweet, how do you prove that the tweet is the user's? HTML, videos, and photos are easy to forge.

In addition, letting people use chat software or clicking on links (although drive.google.com is safe) is not a safe act and can easily be hacked.

**Comment by gildas-lormeau** [comment] 2020-07-08 08:34
Thank you for the feedback. That's strange, I cannot reproduce what I see in your video. You should see the page zooming out when you click on the SingleFile button. I'm wondering if you have a conflict with another extension or something else. Could you do the same test with a new profile in Chrome?

Regarding the tweet deletion, I agree with you. It's more or less impossible to prove the HTML has not been changed. You can compute a hash to prove you did not change the HTML content after you saved it but this does not prove you did not change the content just before saving it. The same kind of issues apply to screenshots though.

Here is an example of trending tweets I saved: [_Amber Heard_ - Recherche sur Twitter _ Twitter (2020-07-08 10_26_54 AM).zip](https://github.com/gildas-lormeau/SingleFile/files/4889464/_Amber.Heard_.-.Recherche.sur.Twitter._.Twitter.2020-07-08.10_26_54.AM.zip)

**Comment by gildas-lormeau** [comment] 2020-07-08 09:02
@yerlincaicedo I did another test and it looks like the first tweets in the thread are saved now (unlike before) but not all last tweets. I'll try to see if I can fix that.

**Comment by gildas-lormeau** [comment] 2020-07-17 23:06
@yerlincaicedo Did you test the new option?

**Comment by gildas-lormeau** [comment] 2020-07-20 16:33
I'm closing this issue because it's fixed. To save twitter threads, you can enable the option "Images > save deferred images > zoom out the page" in SingleFile. Feel free to comment the issue or reopen it if necessary.

**Closed by gildas-lormeau** 2020-07-20 16:33 UTC

**Comment by yerlincaicedo** [comment] 2020-07-20 23:58
hello how are you, excuse my delay.

Couldn't solve the problem trying what you were saying.

(Allow "Pictures> save lazy pictures> zoom out" option in SingleFile. However, they will still have to scroll down the page manually.)

**Comment by gildas-lormeau** [comment] 2020-07-21 16:19
No problem for the delay.

Here is a video in the first zip that shows what you should see when you enable "Images > save deferred images > zoom out the page" and set a value like `10000` for the setting "Images > save deferred images> max idle time". I also attached in the 2nd zip file the page saved in this video. As you can see, there are no blanks in the upper part of the thread.

[video-save-twitter-thread.zip](https://github.com/gildas-lormeau/SingleFile/files/4954782/video-save-twitter-thread.zip)
[#COVID19 - Twitter Search _ Twitter (2020-07-21 4_59_36 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/4954794/COVID19.-.Twitter.Search._.Twitter.2020-07-21.4_59_36.PM.zip)

What happens when you try to do the same thing on your end?

**Comment by gildas-lormeau** [comment] 2020-08-03 12:17
@yerlincaicedo any news?

**Comment by gildas-lormeau** [comment] 2020-11-13 18:51
@yerlincaicedo FYI, this issue is now fixed (see https://github.com/gildas-lormeau/SingleFile/issues/542). You should be able to save twitter pages with the default settings in SingleFile.

**Comment by yerlincaicedo** [comment] 2020-11-14 14:55
I'm going to try it, thank you very much.
I will be commenting on you.
