### ISSUE TITLE
code blocks is not saved

### ISSUE THREAD

**Issue by zhaohui0923** [gildas-lormeau/SingleFile#1029] opened 2022-08-29 09:04 UTC
Please ensure that you do not find an answer before reporting the issue:
 - in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md
 - in the list of known issues: https://github.com/gildas-lormeau/SingleFile#known-issues
 - in the help page embedded in the extension

**Describe the bug**
code blocks is not saved

**To Reproduce**
1. Got to page "https://itnext.io/searching-and-min-max-the-114-c-algorithms-series-8a6ed951ad40"
2. Save the page with SingleFile

**Expected behavior**
Full page with the code block is saved

**Screenshots**

**Environment**
 - OS: Win10 
 - Browser: Chrome
 - Version:104

**Additional context**

**Comment by gildas-lormeau** [comment] 2022-08-30 23:02
Thank you for reporting the issue. This is a site hosted on Medium and handling lazy loaded contents is complicated. I'm closing this report because it's a duplicate of https://github.com/gildas-lormeau/SingleFile/issues/779. Too circumvent this issue, you can to scroll down to the bottom of the page before saving it.

**Closed by gildas-lormeau** 2022-08-30 23:02 UTC
