### ISSUE TITLE
Private browsing mode breaks SingleFile in Firefox Nightly

### ISSUE THREAD

**Issue by cy7yz2rj** [gildas-lormeau/SingleFile#435] opened 2020-06-30 09:49 UTC
**Describe the bug**
Setting `browser.privatebrowsing.autostart` to **true** breaks SingleFile in current Firefox Nightly. The issue is not present in Firefox ESR or in older Nightlies.

**To Reproduce**
1. Create new profile
2. Install SingleFile from AMO and allow working in prviate windows
3. Capture -> success
4. Set private browsing mode to always on
5. Capture -> SingleFile goes through the motions but fails at creating the capture file on disk, icon on toolbar displays `ERR` red box on corner

**Expected behavior**
SingleFile should work regardless of `browser.privatebrowsing.autostart` state, and it did until recently.

**Environment**
 - OS: Debian buster
 - Browser: Firefox Nightly
 - Version: 80.0a1 (2020-06-29) (64-bit)

**Additional context**
I do not know the exact Nightly version where it began, but it's not exclusive to Firefox 80, it was already present in at least some of the 79 Nightlies.

**Comment by gildas-lormeau** [comment] 2020-06-30 14:40
Thank you for reporting this issue. I did some tests and I was able to isolate the bug. I confirm this is a regression in recent versions of Firefox. 
I created an issue on the bug tracker of Mozilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1649463.

I guess disabling "Misc. > Save pages in background" in SingleFile should help to circumvent this issue.

**Comment by cy7yz2rj** [comment] 2020-06-30 16:03
> I guess disabling "Misc. > Save pages in background" in SingleFile should help to circumvent this issue.

Confirmed, thanks!

What else does disabling that setting affect besides filename templates?

**Comment by gildas-lormeau** [comment] 2020-06-30 16:26
> What else does disabling that setting affect besides filename templates?

The native "save as" dialog will be displayed if and only if you configured the browser to do so. 

From a theoretical point of view, saving in background should also be more secure in case the browser is under a low level attack (e.g. related to Spectre/Meltdown etc.) because the process that will get access to the content of the entire page will not be related to the process displaying the tab.

Finally, for technical reasons, the auto-save feature ignores this option and will always try to download the page in background. It means the auto-save is broken in Firefox Nightly if `browser.privatebrowsing.autostart` is set to `true` today.

**Comment by gildas-lormeau** [comment] 2020-07-19 15:41
This issue has been fixed by Mozilla in Firefox 80.

**Closed by gildas-lormeau** 2020-07-19 15:41 UTC
Labels: firefox bug
