### ISSUE TITLE
infobar dialog not visible when clicking the extension button

### ISSUE THREAD

**Issue by wizzard0** [gildas-lormeau/SingleFile#143] opened 2019-01-27 17:59 UTC
**Describe the bug**
I've finally seen the dialog! xD

Ctrl+Shift+Y: Dialog **visible** (OK)
Click extension button: **Not visible** (Bug)
Auto-save: **Not visible** (Makes sense but would be great if this was documented under the checkbox in options)

**To Reproduce**
Goto any page such as this
2. Click on extension button, see page saved
3. Refresh page
4. Press Ctrl-Shift-Y, see dialog, then page saved
5. Refresh page
6. Click on extension button, see no dialog and page saved.

(going back-and-forth to verify it isn't the page or first/second load)

**Expected behavior**
Dialog after clicking icon too; 
OR multiple options (on hotkey, on button, on autosave)

**Environment**
 - OS: Win10Pro, Chromium 72 x64, uBlock Origin

**Additional context**
Related: #140

**Comment by gildas-lormeau** [comment] 2019-01-27 19:01
Are you talking about the dialog that should appear when you check the option "user interface > open a prompt dialog..."?

**Comment by gildas-lormeau** [comment] 2019-02-05 18:45
@wizzard0 I'm closing this issue because I cannot reproduce it and I need more info. Feel free to re-open it if you have more details on how to reproduce this issue.

**Closed by gildas-lormeau** 2019-02-05 18:45 UTC
Labels: need more info
