### ISSUE TITLE
"Save deferred images" influences on displaying images on saved pages

### ISSUE THREAD

**Issue by iG8R** [gildas-lormeau/SingleFile#367] opened 2020-02-27 12:09 UTC
**Describe the bug**
While "save deferred images" is ON some images on saved pages have displaying issue.
Also some issues with other elements on the page (see on screenshots).

**To Reproduce**
1. Go to https://www.nexusmods.com/pillarsofeternity2/mods/32
<details>
  <summary>Click to view screenshot</summary>
  
<img width="1025" alt="PoE2_original_2020-02-27_130403" src="https://user-images.githubusercontent.com/11407417/75441886-22e29680-5967-11ea-9f5d-a743e062606f.png">

</details>

2. With "save deferred images" ON
<details>
  <summary>Click to view screenshot</summary>
<img width="994" alt="PoE2_DefferedON_2020-02-27_130403" src="https://user-images.githubusercontent.com/11407417/75442252-bc11ad00-5967-11ea-9170-00357444c75d.png">
</details>

3. With "save deferred images" OFF
<details>
  <summary>Click to view screenshot</summary>
<img width="999" alt="PoE2_DefferedOFF_2020-02-27_130403" src="https://user-images.githubusercontent.com/11407417/75442266-c469e800-5967-11ea-96bf-38881830c8a2.png">
</details>

4. Also despite having all images in the saved file they are loading from external sources (turn off "remove scripts" to be able to display big images and beholding what is in the screenshot below).
<details>
  <summary>Click to view screenshot</summary>
<img width="1613" alt="PoE2_ExternalImage_2020-02-27_130403" src="https://user-images.githubusercontent.com/11407417/75443296-c3d25100-5969-11ea-92ee-3b8d75ae54aa.png">
</details>

**Environment**
 - OS: Win10 Pro
 - Browser: Firefox
 - Version: 73.0.1 (64-bit)

**Comment by gildas-lormeau** [comment] 2020-02-27 13:33
Thanks for having reporting these 3 issues.

Only the first issue is related to the "Save deferred images" option. I just committed a fix for this. This issue is due to a JavaScript timer that does a fade-in/fade-out as soon as the screen is resized. In the past SingleFile was waiting 100ms after it detected the lazy images were loaded. To fix the issue, I replaced this value with the delay defined in the options / 2.

The second issue, related to the malformed list, is due to the fact that the page is not valid in HTML. I don't know the exact reason for this problem but there is a good chance I won't be able to fix it. I need to investigate this further to find out more precisely what the cause of the problem is.

The third issue, related to the "remove scripts" option cannot be fixed. It's a limitation in SingleFile. That's also why the option is disabled. From my point of view, scripts should always be removed from saved pages and this option should not exist. That's how I would fix this issue but that would make some users angry.

**Comment by iG8R** [comment] 2020-02-27 14:10
@gildas-lormeau many thanks for so detailed answer :)
I agree with you concerning removing scripts from the saved pages, but another issue is arising - how one does have access to images in the saved pages? E.g. https://www.nexusmods.com/pillarsofeternity2/mods/32 has the size almost 10Mb due to many images but I don't have access to them :(
One more question since you mentioned MHTML pages -  so far as MHTML is an archive format it's very easy to extract images, css etc. Does exist some method to do the same with SingleFile's saved pages?

**Comment by gildas-lormeau** [comment] 2020-02-27 15:04
I might be wrong but it looks like the large images are not saved at all because they are loaded and displayed on the fly when you click on a thumbnail. Generally speaking, you could use SingleFileZ and extract images from the page (see the screenshot below). Unfortunately, in this instance, it won't work.

![image](https://user-images.githubusercontent.com/396787/75456297-9fcb3b80-597a-11ea-8dcd-de130d11c7df.png)

**Comment by iG8R** [comment] 2020-02-27 15:49
Thanks a lot! I didn't know about SingleFileZ

**Comment by gildas-lormeau** [comment] 2020-02-27 15:58
You're welcome :)

SingleFileZ is almost identical to SingleFile however it does not have the annotation editor yet, because it's a bit more complicated to implement it. Note that I just deployed the new version of SingleFileZ (0.5.111) which should fix the thumbnails displaying issue when 
the option "Save deferred images" is enabled.

**Comment by iG8R** [comment] 2020-02-27 16:13
Thanks again! It works :)
But there is a difference between saved pages of SingleFile and SingleFileZ.
SingleFile:
<img width="994" alt="PoE2_SingleFile_2020-02-27_130403" src="https://user-images.githubusercontent.com/11407417/75462268-abbff900-598c-11ea-83bd-16b955b80ac4.png">

SingleFileZ:
<img width="1010" alt="PoE2_SingleFileZ_2020-02-27_130403" src="https://user-images.githubusercontent.com/11407417/75462294-b67a8e00-598c-11ea-8868-f383564dc766.png">

**Comment by gildas-lormeau** [comment] 2020-02-27 16:18
I cannot reproduce this issue. On my end, the 2 pages look the same. Are you sure you're using the same settings?

**Comment by iG8R** [comment] 2020-02-27 16:57
Sure, the settings are the same.
I understood, with SingleFile's saved page uBlock folds the upper frame in that I marked with red rectangle, but with SingleFileZ' saved page - uBlock for some unknown reason doesn't fold it in.
But issues with other elements (marked with red arrows) differ on SingleFile's and SingleFileZ's saved pages.

PS. You are welcome :)

**Comment by gildas-lormeau** [comment] 2020-02-27 17:49
I'll do some additional tests with uBlock installed to understand why you're seeing differences between the two pages.

**Comment by iG8R** [comment] 2020-02-27 18:19
Thank you :)
I found a command line program that can extract/embed inline images from/to HTML files -  https://landenlabs.com/cs-inlinehtmlimages/inlinehtmlimages.html

**Comment by gildas-lormeau** [comment] 2020-02-27 19:04
Thank you for the information too :)

Some days ago, I stumbled upon this video on Youtube: https://www.youtube.com/watch?v=cpvBuxHBJYE
I did not understand it but it looks like this tool also allows you to extract images with a GUI.

**Comment by iG8R** [comment] 2020-02-27 19:58
Alas, this program (VkD) only parses SingleFile's saved html for external links on images and downloads them from there.

**Comment by gildas-lormeau** [comment] 2020-02-27 21:43
Okay! Thank you,for the information

**Comment by gildas-lormeau** [comment] 2020-03-09 16:14
I'm closing this issue since it should be fixed now. Feel free to reopen it if necessary.

**Closed by gildas-lormeau** 2020-03-09 16:14 UTC
