### ISSUE TITLE
firefox not adhearing to download location

### ISSUE THREAD

**Issue by nakinigit** [gildas-lormeau/SingleFile#1095] opened 2023-01-24 04:17 UTC
Please ensure that you do not find an answer before reporting the issue:
 - in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md
 - in the list of known issues: https://github.com/gildas-lormeau/SingleFile#known-issues
 - in the help page embedded in the extension

**Describe the bug**
Despite firefox download location "prompt" location is not an option

**To Reproduce**
1. click download
2. Click on there is no option
3. Scroll down to to where?
4. No error

**Expected behavior**
previous versions of ff prompted for save to location. Not so anymore

**Screenshots**

**Environment**
 - linux mint20.xx
 - Browser: firefox
 - Version: 102+

**Additional context**
Firefox: to update is to break

**Comment by gildas-lormeau** [comment] 2023-01-25 23:33
You have to enable `File name > open the "Save as" dialog to confirm the file name` in the options page of SingleFile. For the record, it's a duplicate of #1080.

**Closed by gildas-lormeau** 2023-01-25 23:33 UTC
