### ISSUE TITLE
Facebook and m.facebook.com don't work

### ISSUE THREAD

**Issue by thibaultmol** [gildas-lormeau/SingleFile#900] opened 2022-03-21 16:31 UTC
**Describe the bug**
When trying to save a page of a facebook group, on facebook.com itself, it doesn't capture any of the useful part of the page

**To Reproduce**
1. Go to  facebook.com or m.facebook.com and go to a group 
2. Press the Singlefile extension's icon 

**Expected behavior**
Capture the entire page, including the feed itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/1010226/159308519-654e9067-e85f-42db-9dd5-b752dcf5601d.png)

![image](https://user-images.githubusercontent.com/1010226/159308665-be929900-6f48-4e6c-afd9-36ad21022326.png)

**Environment**
Firefox 98.0
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.2
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.16.11-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2

**Comment by falcorr** [comment] 2022-03-30 10:29
Presumably relevant: I've found SingleFile can't capture a user page on Facebook. Scroll a while and capture - it'll only capture the feed on the right within a certain scroll range up and down of the current position. This is the Chrome extension.

**Comment by gildas-lormeau** [comment] 2022-03-30 10:46
@falcorr  I don't have any account on Facebook. Could you do the same test and scroll up to the top of the page just before saving it. Does this help?

**Comment by attarian001** [comment] 2022-03-30 22:10
Where would you like to test

**Comment by gildas-lormeau** [comment] 2022-04-06 22:59
@attarian001This test would have to be done on the user page (see @falcorr message).

**Comment by gildas-lormeau** [comment] 2022-05-12 23:27
I'm closing this issue because I do not have enough info to work on it. Feel free to reopen it if necessary.

**Closed by gildas-lormeau** 2022-05-12 23:27 UTC

**Comment by grantbacon** [comment] 2023-10-10 00:26
So I was getting this issue, it seems it can be done with a sufficiently long page that uses an infinite scroll design. I think it's only keeping what is in the viewport and some area around that. Some things like the side bars will still be present but the post content from the user's wall is not.


Steps to reproduce:
1. Visit a facebook user's page that has enough content to create several pages in the 'infinite scroll' pattern used on the page
2. Save as single file

Expected:
All content that is fetched during pagination is present in result

Actual:
Only some content that is paged at the time of running SingleFile is contained in result
