### ISSUE TITLE
More locales are not included in the Edge store

### ISSUE THREAD

**Issue by yfdyh000** [gildas-lormeau/SingleFile#634] opened 2021-03-15 08:03 UTC
**Describe the bug**
As of now the extension is only available in English from the Edge store.

**To Reproduce**
1. Open the https://microsoftedge.microsoft.com/addons/detail/singlefile/efnbkdcfmcmnhlkaijjjmhjjgladedno
2. Install it with Edge browser.

**Expected behavior**
1. Like installing from the Chrome store.
2. 10 languages ​​available instead of 1 languages ​​available on the page.

**Environment**
 - OS: Win10
 - Browser: Edge 
 - Version: x64.

**Comment by gildas-lormeau** [comment] 2021-03-15 09:55
This is done on purpose. Microsoft wants me to translate all the content of the description page. If I can't, then I have to remove the translations from the extension. Otherwise they refuse to publish SingleFile ¯\_(ツ)_/¯.

**Comment by gildas-lormeau** [comment] 2021-03-17 11:39
I asked again the question to the MDN support because they told me in the past this rule could change. They confirmed nothing changed, and that the description page must also be translated if I want to publish a locale.

**Comment by yfdyh000** [comment] 2021-03-18 02:21
> I asked again the question to the MDN support because they told me in the past this rule could change. They confirmed nothing changed, and that the description page must also be translated if I want to publish a locale.

Then I suggest you submit the translatable content to a file in the repo, like html, json or just text.
Also, I'm not sure anyone has ever tried machine translation of a description, even though the quality is unpredictable. I also saw some untranslated descriptions like Tampermonkey. Or even provide simplified or empty descriptions for other languages? Although neither is optimal, only if no translator is interested in the translated description.

**Comment by gildas-lormeau** [comment] 2023-07-23 00:17
I'm closing this issue, but I keep https://github.com/gildas-lormeau/SingleFile/issues/1162 open to make it more visible in my task list :p.

**Closed by gildas-lormeau** 2023-07-23 00:17 UTC
