### ISSUE TITLE
Filename extensions are not properly handled when --filename-conflict-action is set to "uniquify"

### ISSUE THREAD

**Issue by andrewdbate** [gildas-lormeau/SingleFile#802] opened 2021-10-19 00:56 UTC
When I run the following command:
```
single-file --urls-file=urls.txt --output-directory=outdir --filename-template="{url-pathname-flat}.html" --filename-conflict-action=uniquify
```
where the contents of the `urls.txt` file is:
```
https://en.wikipedia.org/wiki/1956_Olympic_Flame_hoax
https://en.wikipedia.org/wiki/1956_Olympic_flame_hoax
```

The URLs are the same except for the lowercase `f` in `flame` in the second URL.

I get the following files in the `outdir` directory:
```
'_wiki_1956_Olympic_flame_hoax (2.html)'
_wiki_1956_Olympic_Flame_hoax.html
```

The file extension on the first file is `html)` instead of `html`.

**Comment by andrewdbate** [comment] 2021-10-19 21:02
NTFS is a case sensitive file system. The above command was run on Windows, yes.

In any case, the file extension should have been `html` and not `html)`.

**Comment by gildas-lormeau** [comment] 2021-10-19 21:08
Thank you, I fixed the parenthesis issue. Feel free to give me some hints on how to create case sensitive file names in Windows with Node.

**Comment by gildas-lormeau** [comment] 2021-10-19 21:14
It should work in WSL though.

**Comment by scruel** [comment] 2021-11-15 00:51
@andrewdbate Check here: https://docs.microsoft.com/en-us/windows/wsl/case-sensitivity
@gildas-lormeau plugin works fine, this is an OS based issue, there is nothing you can do to solve this problem, unless provide a filename-conflict strategy which can compare the case of filename of existing file, then rename it just like the issue mentioned(add "(2)").

**Comment by gildas-lormeau** [comment] 2021-12-27 00:42
I'm closing this issue because I cannot fix it.

**Comment by andrewdbate** [comment] 2021-12-27 00:49
I am disappointed to see this issue closed. I disagree that you cannot fix it. You could provide improved filename conflict handling so that when a file already exists it is given a sensible name instead of messing up the file extension. The file extension should always be preserved.

Of course you are free to close this (it is your project after all), but then the reason for closing the issue should be that you are unwilling to fix the bug, rather than that it cannot be fixed.

**Comment by scruel** [comment] 2021-12-27 00:54
@andrewdbate I do think he had fixed the “extension won't be preserved” issue(If not, feel free to open a new issue), I think he closed this issue for the case-insensitive part of your issue title.

**Comment by gildas-lormeau** [comment] 2021-12-27 00:55
I closed the issue because the I did not notice there were 2 issues actually.

**Comment by andrewdbate** [comment] 2021-12-27 00:56
Okay, thanks. I understand that the case insensitivity issue on Windows is annoying, but it would be good if we could preserve the file extension.

**Comment by gildas-lormeau** [comment] 2021-12-27 01:09
Actually, I cannot reproduce the issue. On my end, I get two files named:
`_wiki_1956_Olympic_flame_hoax.html`
`_wiki_1956_Olympic_Flame_hoax (2).html`

**Comment by andrewdbate** [comment] 2021-12-27 01:11
Do you know in which commit it was fixed? Are you running this on Command Prompt, PowerShell, Bash on Windows?

**Closed** 2021-12-27 01:11 UTC

**Comment by scruel** [comment] 2021-12-27 01:13
@andrewdbate https://github.com/gildas-lormeau/SingleFile/commit/4fa9c3fd9ad6bc1cc687257106fe803bd9e73746
![image](https://user-images.githubusercontent.com/16933298/147424847-b7bacf30-1e2a-4965-bd2e-8f27dc18a657.png)

**Comment by gildas-lormeau** [comment] 2021-12-27 01:13
This is the commit that fixes this issue: https://github.com/gildas-lormeau/SingleFile/commit/4fa9c3fd9ad6bc1cc687257106fe803bd9e73746.
