### ISSUE TITLE
The HTTP header "Accept" must be set according to the type of resource being downloaded

### ISSUE THREAD

**Issue by testyusers** [gildas-lormeau/SingleFile#822] opened 2021-11-17 00:31 UTC
Working with forum posts I noticed that linked images are not saved. Same applies to gifs. Both leave blanks in saved files. No even space reserved. 

Sample of such image https://www.tradingview.com/x/v2Ljifal/

Sample of GIF https://i.gifer.com/IKS.gif 

Both URLs obtained by Open image in new tab option in context menu.

**Comment by gildas-lormeau** [comment] 2021-11-17 00:39
I'm sorry, I can't follow you. Could you describe more precisely the issue please?

**Comment by testyusers** [comment] 2021-11-21 00:49
I refer to images embedded inline into forum posts. The images are displayed correctly when reading forums live. However, no images are found when SingleFile produced archive pages from the forum are opened.  

Only some images are affected. Thus, I started looking into sources of those images and their types. I do not know what is abut gifs, but the TV URL offers HTML file when Save Image As is clicked. When Open in New Tab is chosen, the URL opens whcih is an HTML page rather than single png or jpg file. 

Apparently, SF does not pick images linked such way. This makes its use problematic as some visual information may not be retained. Until a workaround is found, I have been saving such images from the page which opens, but that is tedious and will be inconvenient when reviewing the saved pages.

**Comment by gildas-lormeau** [comment] 2021-12-23 01:14
Thank you for the details and sorry for the late answer. I think the issue is due to the fact that SingleFile does not provide the expected value for the `Accept` header (cf. https://developer.mozilla.org/docs/Web/HTTP/Headers/Accept) when downloading images. I tried to implement this feature in the past but it introduced some regressions if I remember correctly. I'll try to do some tests again.

**Comment by gildas-lormeau** [comment] 2021-12-27 01:21
This issue should be fixed in the version 1.19.24. Feel free to comment or reopen it if this is not the case.

**Closed by gildas-lormeau** 2021-12-27 01:21 UTC
