### ISSUE TITLE
SingleFile downloads tabs multiple times

### ISSUE THREAD

**Issue by krosola** [gildas-lormeau/SingleFile#92] opened 2018-11-11 08:41 UTC
Hello,

I am a really big fan of this powerful extension coming from Chrome, and I was really glad to find it on Firefox. However, I have been unfortunately encountering a bug where the extension downloads the tabs I open in the background multiple times. This is happening on Firefox 63.0 (64-bit) on a macOS Mojave. I am relying on this extension to download lots of webpages and I would be really grateful if you can manage to solve the issue. I especially would love to use the Auto-save unpinned tabs feature.

It even works for websites where the default "save  page as" for chrome and Firefox doesn't. 

Best Regards

**Comment by gildas-lormeau** [comment] 2018-11-11 10:12
Hi,

Thanks for reporting the issue. At first sight, it seems specific to macOS. Does it happen with any page you want to save? Could you try to disable the "save page in background" option and tell me if it helps to fix this issue or change somewhat its behavior? Do you see the same issue with Chrome?

**Comment by gildas-lormeau** [comment] 2018-11-11 21:58
Thanks a lot for your detailed response. Regarding the multiple download issue, I just committed some code that could help to fix it. Could you please download the [zip file](https://github.com/gildas-lormeau/SingleFile/archive/master.zip) of the extension, unzip it somewhere, follow [this procedure](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#Installing) and tell me if it changes anything?
Regarding the fact that pinned tabs are saved whereas they should not, it's another bug. I need to do some tests.

**Comment by krosola** [comment] 2018-11-11 22:11
I'm very glad to hear back from you so soon. I have attempted to install the updated extension but I may be doing something wrong as I receive the error "There was an error during installation: File /Users/Krosola/Downloads/SingleFile-master/extension does not contain a valid manifest". I'm also not sure which of the js files to install but I assumed it would be either single-file-browser.js or single-file-core.js, but both produce the same error.

**Comment by gildas-lormeau** [comment] 2018-11-11 22:12
Select the manifest file itself.

**Comment by krosola** [comment] 2018-11-11 22:29
OK, you've done a wonderful job, the extension functions like a dream for me now. I will rely on this app to download lots of pages overnight and I couldn't be more pleased. I will make sure to leave a positive review on the add-on store. Your work is truly appreciated, thanks a bunch.

**Comment by gildas-lormeau** [comment] 2018-11-11 22:47
You're welcome and thanks for your help and the kind words too. I'll update the extension on the store ASAP :).

**Comment by gildas-lormeau** [comment] 2018-11-11 23:01
The fix is published (version 1.8.24). I let the issue open for the other bug you mentioned.

**Comment by gildas-lormeau** [comment] 2018-11-12 13:05
I was not able to reproduce the other issue you mentioned. When I select "auto-save all unpinned tabs" and configure the auto-save to save the page just before being unloaded, the pinned tabs are never auto-saved. I'm closing the issue. If I misinterpreted the issue, feel free to reopen it.

**Closed by gildas-lormeau** 2018-11-12 13:05 UTC
