### ISSUE TITLE
Singlefile not saving / partially saving / hangs while saving Twitter pages (or sites with many 'Click to expand' replies in Firefox Android Nightly

### ISSUE THREAD

**Issue by noto10** [gildas-lormeau/SingleFile#765] opened 2021-08-31 18:50 UTC
I have Singlefile installed in the latest Firefox Android Nightly. It works well enough most of the time with 'conventional' sites and pages.

However, on sites with long scrolling content which auto refreshes as you scroll down and which contain many collapsed nested replies that require the user to 'Click to expand', Singlefile will often fail either during saving, usually before Step 1 or during Step 2. Twitter is the most problematic site to date. The following screenshot shows Singlefile hanging at Step 2:

![single1](https://user-images.githubusercontent.com/13828004/131552877-0037d22f-fe3c-473c-92fe-142101778d96.jpg)

Even when Singlefile saves the page, the saved page often does not include the replies which I had 'Clicked to expand'. At other times, it would save only a partial portion of the page, leaving blank areas preceding and after the saved portion. (Example below)

![single2](https://user-images.githubusercontent.com/13828004/131558589-30de0e30-1ab0-4656-a453-fe8cd981d3bf.jpg)
 
While I understand that Singlefile is not officially supported by Firefox Android and I am thankful that it works most of the time, it would be wonderful if a workaround could be found for this problem.

**Comment by gildas-lormeau** [comment] 2021-08-31 22:18
Did you change any setting? I did a test with a tweet of The New York Times and I was not able to reproduce the issue. I attached the saved page in the zip file.

[The New York Times on Twitter_ _Entergy, the largest electric utility in New Orleans, is struggling to restore service to hundreds of thousands of customers who have been without electric….zip](https://github.com/gildas-lormeau/SingleFile/files/7087069/The.New.York.Times.on.Twitter_._Entergy.the.largest.electric.utility.in.New.Orleans.is.struggling.to.restore.service.to.hundreds.of.thousands.of.customers.who.have.been.without.electric.zip)

**Comment by noto10** [comment] 2021-09-03 20:01
> Did you change any setting? I did a test with a tweet of The New York Times and I was not able to reproduce the issue. I attached the saved page in the zip file.
> 
> Edit: I did the test with the latest version of Firefox Nightly (Android 11)
> 
> [The New York Times on Twitter_ _Entergy, the largest electric utility in New Orleans, is struggling to restore service to hundreds of thousands of customers who have been without electric….zip](https://github.com/gildas-lormeau/SingleFile/files/7087069/The.New.York.Times.on.Twitter_._Entergy.the.largest.electric.utility.in.New.Orleans.is.struggling.to.restore.service.to.hundreds.of.thousands.of.customers.who.have.been.without.electric.zip)

No, I did not change any setting. Having looked at your test result, I think I should explain. If my assumption is correct, you saved the page 'as-is' without showing any replies or further replies:

![show1](https://user-images.githubusercontent.com/13828004/132059009-8cdb9560-83ac-4a0c-ac54-b6a6453a6e4b.jpg)

![show3](https://user-images.githubusercontent.com/13828004/132059146-98e196df-898f-4aec-9fcb-f2cd482d92bd.jpg)

Like you, I find that Singlefile usually has no issues with just a simple save of the default view. But if I were to click 'Show replies' and 'Show further replies' for several page lengths, it somehow affects Singlefile. For example, if the NYT page you saved had 200 comments with 25 of the 200 containing their own sub-threaded replies while the main thread had 5 'Show further replies' to fully expand, chances are Singlefile would botch the job.

Is there a debug option to log errors while saving?

**Comment by gildas-lormeau** [comment] 2021-09-03 20:24
I clicked on the link "Show more replies" at the end of the thread, that's why "More Replies" is displayed.

![image](https://user-images.githubusercontent.com/396787/132061703-54939ef8-3681-4120-af0d-fd0c7a535991.png)

I'll do another test with the "Show replies" button.

**Comment by gildas-lormeau** [comment] 2021-09-05 18:15
I did again the test with the same tweet, I clicked on all the "Show more replies" links and I was not able to reproduce the issue, see the HTML file in the attached zip file (best viewed with a window width of 480px).

[The New York Times on Twitter_ _Entergy, the largest electric utility in New Orleans, is struggling to restore service to hundreds of thousands of customers who have been without electric….zip](https://github.com/gildas-lormeau/SingleFile/files/7112128/The.New.York.Times.on.Twitter_._Entergy.the.largest.electric.utility.in.New.Orleans.is.struggling.to.restore.service.to.hundreds.of.thousands.of.customers.who.have.been.without.electric.zip)

**Comment by najloa** [comment] 2021-09-08 13:35
**Option: zoom out the page**
Check this option to save the entire content of a page by zooming out the page. This can help saving pages using infinite virtual lists for example.

**Comment by gildas-lormeau** [comment] 2021-10-10 22:22
I'm closing this issue because I cannot reproduce it. Feel free to comment and/or reopen it if necessary.

**Closed by gildas-lormeau** 2021-10-10 22:22 UTC
