### ISSUE TITLE
Allow auto-save-all-tabs as default option?

### ISSUE THREAD

**Issue by ejayaraman** [gildas-lormeau/SingleFile#187] opened 2019-04-12 11:43 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to use SingleFile plugin with Selenium with auto-save-all-tabs option. But since selenium launches a new Browser instance/profile every time, it always starts with the default settings of SingleFile i.e AutoSave disabled. Is there a way I can include the plugin with custom options as default?  

**Describe the solution you'd like**
I would like to be able to set some custom configuration like auto-save-all-tabs by default when launching the browser via Selenium. 

If this is something that is already possible, then any documentation would be helpful.

**Comment by gildas-lormeau** [comment] 2019-04-12 22:43
The CLI tool I developed allows you to set any option and would maybe solve this issue. You can find more info here: https://github.com/gildas-lormeau/SingleFile/tree/master/cli.
Please let me know if that fulfill your needs.

**Comment by gildas-lormeau** [comment] 2019-04-12 23:11
I deleted my previous answer because it was irrelevant. I need to do some tests but I think I can give you a procedure to follow in order to activate the auto-save just after launching the browser. Alternatively, you could rely on the CLI tool (https://github.com/gildas-lormeau/SingleFile/tree/master/cli) and write a script (e.g. a bash script) that would capture several URLs.

**Comment by gildas-lormeau** [comment] 2019-04-13 19:26
@ejayaraman: 
Here is what to do in order to activate the auto-save on Firefox:
 - Launch Firefox through Selenium and go to about:debugging#addons
 - Note the Internal UUID of SingleFile, e.g. f225e3dc-b07b-49da-a28d-9b8a9a3e2732

Then, in your Selenium script, you have to add these steps:
 - open the URL: moz-extension://f225e3dc-b07b-49da-a28d-9b8a9a3e2732/_generated_background_page.html (replace "f225e3dc-b07b-49da-a28d-9b8a9a3e2732" with your internal UUID),
 - and run the script below to activate the auto-save.
```
(async () => {
    const tabsData = await singlefile.tabsData.get();
    tabsData.autoSaveAll = true;
    await singlefile.tabsData.set(tabsData);
})();
```

**Comment by gildas-lormeau** [comment] 2019-04-13 20:11
Actually, I don't see how to establish a communication between Selenium and the background page of SingleFile. This is a requirement in order to activate the auto-save programmatically trough Selenium. The problem is that I need to know the UUID of the extension (generated by Firefox) in order to open the background page of SingleFile but I'm unable to find thsi UUID with the Selenium API.

**Comment by gildas-lormeau** [comment] 2019-04-13 22:26
Actually, if you're forking the code. You just have to add the following code for example in `/extension/core/bg/data/tabs-data.js` :

```
(async () => {
    const tabsData = await singlefile.tabsData.get();
    tabsData.autoSaveAll = true;
    await singlefile.tabsData.set(tabsData);
})();

**Comment by ejayaraman** [comment] 2019-04-15 08:31
Thank you Gildas. I will give this a try and update you. 
Appreciate your time on this.

**Comment by gildas-lormeau** [comment] 2019-04-15 17:28
@ejayaraman you're welcome!

**Comment by gildas-lormeau** [comment] 2019-04-19 23:39
I'm closing this issue. I guess the code I proposed works. Feel free to re-open the issue if it doesn't.

**Comment by ejayaraman** [comment] 2019-04-23 14:42
Thanks Gildas. I am still testing. I will keep you updated.

**Comment by gildas-lormeau** [comment] 2019-04-23 21:46
Okay :)

**Comment by ejayaraman** [comment] 2019-04-24 16:30
Hi Gildas. We have stumbled upon an issue while testing the above changes and would like to run it through you. 

**This is what we are trying to do:**
We have selenium tests that accesses our application using ChromeDriver. 
As selenium accesses each of these pages, we want to download every HTML pages as a Single File. This is where we use the SingleFile plugin. 
We launch the Chrome browser with the SingleFile plugin via the ChromeDriver. The above code enables auto-save-all by default and starts downloading the page as the test navigates to various pages. 
The issue we are noticing is, the SingleFile plugin, when used along with the selenium tests, is either _corrupting_ or _replacing_ the cookie. This results in the tests to fail as the cookie is not valid anymore. We are trying to understand why and how, downloading the HTML file would interfere with session cookie. Does SingleFile plugin touches the cookie data during the process of downloading the HTML file? Any inputs on this would be very helpful. Thanks.

**Comment by gildas-lormeau** [comment] 2019-04-24 17:40
Hi @ejayaraman. Indeed, SingleFile blocks access to cookies when trying to load deferred contents (e.g. images, frames). The idea is to prevent the page displaying a "subscribe to our newsletter" popup by blocking the access to persistent storage temporarily. To disable this feature, you can edit `extension/core/bg/data/config.js` and change the default value of the the `loadDeferredImages` property in the `DEFAULT_CONFIG` object. Setting it to `false` should fix your issue.

**Comment by dannyprok** [comment] 2019-04-25 14:42
Hi @gildas-lormeau ,
I'm working alongside @ejayaraman on the above issue.

We've updated the plugin to set loadDeferredImages to false, however it hasn't resolved the issue - our applications continue to report missing session information when the SingleFile plugin is present, and, the plugin is configured to autosave.  We've not been able to reproduce the issue by using SingleFile page saving in manual mode.

We've also noticed that this issue appears when the tests run for the first time against a fresh chrome profile.  Chromedriver creates a new profile on every run so we're seeing this each time we trigger a test.  When I step through a test manually against a given profile directory, the issues appears the first time after a page is autosaved, however subsequently running the same test manually with autosave on succeed.  

Is there any other functionality in SingleFile that may interfere with the session?  
Does SingleFile store any session information in the profile directory that prevents the error from occurring on subsequent runs?

Thanks again for your help!

**Comment by gildas-lormeau** [comment] 2019-04-25 15:19
@dannyprok Do you see any warnings or errors related to SingleFile in the developer console when you reproduce the issue? 

FYI, note that you could also run SingleFile from the command line as described here: https://github.com/gildas-lormeau/SingleFile/tree/master/cli. Do you reproduce the issue in this case?

**Comment by dannyprok** [comment] 2019-04-26 15:43
SingleFile produces no errors or warnings in the developer console when the browser loses it's session info.

We've just confirmed that this issue is only reproducible when autosaving pages being served on localhost.  We've executed several test suites against hosted test environments without reproducing it.  For now we'll limit the scope of what we're trying to do test suites running against hosted test environments.

I may take a look at the cli as an alternative, however the browser plugin better suits our needs as we're capturing pages by piggy backing on several webdriver test suites (we don't own these).  If we go down the route of using the CLI we'd have to re-write those tests to achieve the coverage we're after (from what I can tell).

@gildas-lormeau thanks again for your help on this.

**Comment by gildas-lormeau** [comment] 2019-04-26 16:13
@dannyprok Thanks for the info. That's really really weird... I'm really wondering what is happening. I mean that if you set `loadDeferredImages` to false then I confirm SingleFile should not interfer with cookies, localStorage, sessionStorage, indexedDB... 

I would suggest you to change autosave settings in `config.js` in order to try understanding what's going on. For example, you can you set `autoSaveLoad` to true  and `autoSaveLoadOrUnload` to `false` to make sure you won't save the page just before being unloaded. Maybe, you could also increase the `autoSaveDelay` to a higher value than 1 (second).

Can you confirm your session info is stored into a cookie, and thus sent via the corresponding HTTP header natively (and not the localStorage for example)?

**Comment by gildas-lormeau** [comment] 2019-04-26 16:58
It could be also interesting to see what's happening in the network panel. Maybe you could identify the requests where the cookie is not present in the HTTP headers, for example.

**Comment by gildas-lormeau** [comment] 2019-04-27 23:16
I'm closing this issue because the issue "Allow auto-save-all-tabs as default option?" is somewhat fixed. I mean that I showed a procedure to fix it. Please create post issue(s) or contact me by email to help you debugging for example the session problem.

**Closed by gildas-lormeau** 2019-04-27 23:16 UTC

**Comment by dannyprok** [comment] 2019-04-28 09:18
Cheers @gildas-lormeau , will do a little more digging and get in touch.
