### ISSUE TITLE
Impossible to save multiple tabs reliably in parallel in Chrome (regression)

### ISSUE THREAD

**Issue by doplu** [gildas-lormeau/SingleFile#314] opened 2019-11-23 08:40 UTC
Hello,

First, thank you for this great addon. ;)
Since a few days, the behaviour of this auto-close feature (""auto-close the tab after the page is saved"" has changed in Google Chrome :
I open many tabs. Then I save a tab [ALT+S], and by the time it is saved by itself, I move to another tab, which I also save, ...etc.. .
Before, all tabs would be saved by themselves (which is great as I don't have to wait that each tab is saved). Now, I need to wait that the last tab is saved so I can save another one. This is very annoying.

Thank you in advance ;)
Win8.1 64bits home 
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by doplu** [comment] 2019-11-23 09:41
Here is my settings if I export them :
```
{
  "profiles": {
    "__Default_Settings__": {
      "autoClose": true,
      "autoOpenEditor": false,
      "autoSaveDelay": 1,
      "autoSaveLoad": false,
      "autoSaveLoadOrUnload": true,
      "autoSaveRepeat": false,
      "autoSaveRepeatDelay": 10,
      "autoSaveUnload": false,
      "backgroundSave": true,
      "browserActionMenuEnabled": true,
      "compressCSS": true,
      "compressHTML": true,
      "confirmFilename": false,
      "confirmInfobarContent": false,
      "contextMenuEnabled": true,
      "credentials": "include",
      "displayInfobar": true,
      "displayStats": false,
      "extractAuthCode": true,
      "filenameConflictAction": "uniquify",
      "filenameMaxLength": 192,
      "filenameReplacedCharacters": [
        "~",
        "\\\\",
        "?",
        "%",
        "*",
        ":",
        "|",
        "\"",
        "<",
        ">",
        "\u0000-\u001f",
        ""
      ],
      "filenameReplacementCharacter": "_",
      "filenameTemplate": "{day-locale}/({date-iso} {time-locale})_{url-hostname}.html",
      "forceWebAuthFlow": false,
      "groupDuplicateImages": true,
      "includeInfobar": false,
      "infobarTemplate": "",
      "loadDeferredImages": true,
      "loadDeferredImagesBlockCookies": true,
      "loadDeferredImagesBlockStorage": false,
      "loadDeferredImagesMaxIdleTime": 1500,
      "logsEnabled": true,
      "maxParallelWorkers": 4,
      "maxResourceSize": 10,
      "maxResourceSizeEnabled": false,
      "openEditor": false,
      "progressBarEnabled": true,
      "referrerPolicy": "origin-when-cross-origin",
      "removeAlternativeFonts": true,
      "removeAlternativeImages": true,
      "removeAlternativeMedias": true,
      "removeAudioSrc": true,
      "removeFrames": false,
      "removeHiddenElements": true,
      "removeImports": true,
      "removeScripts": true,
      "removeUnusedFonts": true,
      "removeUnusedStyles": true,
      "removeVideoSrc": true,
      "resolveFragmentIdentifierURLs": false,
      "saveRawPage": false,
      "saveToClipboard": false,
      "saveToGDrive": false,
      "shadowEnabled": true,
      "tabMenuEnabled": true,
      "userScriptEnabled": false
    }
  },
  "rules": [],
  "maxParallelWorkers": 4
}
```

**Comment by gildas-lormeau** [comment] 2019-11-23 10:54
Hi,

I indeed fixed some issues related to the pending saves and may I have broken something. Unfortunately, I do not understand how to reproduce the issue. If I open multiple tabs, go to the first tab, save the page, go to the second tab, save the page, and so on, I don't see any particular issue, the tabs are saved in parallel and auto-closed as expected. Please give me more details or a precise scenario to be able to understand how to reproduce this issue. I think I'm missing something.

If that's possible on your end to do the test with the latest version, please download it here: https://github.com/gildas-lormeau/SingleFile/archive/master.zip. Unzip it somewhere and follow that procedure to install it manually (start at step 1): https://developer.chrome.com/extensions/getstarted#manifest. Can you reproduce the issue with this version?

**Comment by doplu** [comment] 2019-11-23 11:52
Hi,
Thanks. ;)
I have tried to follow your instructions and when I "load unpacked" and chose the correct directory (C:\prog\SingleFile-master) it has somes errors (see this :
https://www.cjoint.com/c/IKxlxECFaLD ).
Just in case, I have removed many of my opened tabs (200+) and restarted Google Chrome. I also removed the addon and installed your version and got the same errors.
Anyway, I have tried to save several tabs and I have still the error :
Here is a video :
https://www.cjoint.com/c/IKxlMgc7QjD
and a screenshot
https://www.cjoint.com/c/IKxlM0qwjcD

Now watch this video : https://gofile.io/?c=lKYqRj
Then watch it again and keep your eye on the top of the third tab (counting from the left) : it disappeared but it should not ! (not in the video but it also closed alone my first tab later on!)

Thanks in advance ;)

**Comment by gildas-lormeau** [comment] 2019-11-23 15:13
Thank you very much for your detailed answer. 

The warnings you're seeing are normal. They are displayed because the extension has not specifically been built for Chrome when you use the master.zip file.

Your issue is really weird. I tried to do exactly what you did in your second video but I was never able to reproduce the issue. BTW, I usually do my tests on the same site ;). On my end, the closed tabs are the ones that I just saved. Just to make sure I'm doing my tests right, can you tell me what action you associated Alt-S with? This shortcut is not defined by default by SingleFile. You can find the info here: chrome://extensions/shortcuts.

As I said, your issue is weird. From a theoretical point of view, it almost makes no sense when I read my code and compare it to the behavior in your video. Right now, it's hard for me to understand what's going on. That's why I'm proposing you to test the code attached to this issue. I tried to apply some changes in the code that could maybe fix it. Install it like the previous master.zip file. You should not see any warning this time. Can you please tell me if this version of the extension makes any difference?

[singlefile-extension-chromium.zip](https://github.com/gildas-lormeau/SingleFile/files/3882595/singlefile-extension-chromium.zip)

**Comment by doplu** [comment] 2019-11-23 16:38
Hi,

My pleasure. thank you to you. ;)

I restarted my computer. I removed the addon. Then added your last one. It then added errors : https://www.cjoint.com/c/IKxqDEnkNxD
I did not add the shortcut ALT+S. I did not load my old settings. I just added the "auto-close" feature. 
I have run Glary utilities to clean my computer (clear some cache but not my big browsing history). I have checked if Avast has not blocked something (but no).
I have put in "off mode" all my other Google Chrome addons. And I did some tests in incognito mode see video : https://gofile.io/?c=MLfupY

Thanks in advance ;)

**Comment by gildas-lormeau** [comment] 2019-11-23 16:56
Thank for the screenshots. I'm sorry, these warnings are normal and not related to the issue.

By looking more closely at your previous video, it seems that the Alt-S shortcut is associated with "Save all tabs". Can you please verify this or show me the screenshot of the Shortcuts screen chrome://extensions/shortcuts? What makes me think this is that at 0:36, the SingleFile icon is the default icon on the options page. But at 0:45, the icon went to the state you can see when you try to save a page that is not allowed to be saved by the browser. It also looks like the tab just before the last one is already saving itself when you click on it at 0:46. In this case, the second video would show correct behavior as long as the last tabs also close too.

I can reproduce the issue you show in the last video when using the incognito mode. I don't think it's the same issue because it does not work at all. I'm going to see what's the cause of it.

**Comment by doplu** [comment] 2019-11-23 17:03
chrome://extensions/shortcuts :
For the last video it was this default behavior CTRL+Shift+U : https://www.cjoint.com/c/IKxrarXBnbD
Previously it was ALT+S. I have never used the option "Save all tabs", I always used save one tab.
Thanks. ;)

**Comment by doplu** [comment] 2019-11-23 17:04
No alt+s in the second video. As you can see I click on the addon button.

**Comment by gildas-lormeau** [comment] 2019-11-23 17:08
I don't know what Alt-S is supposed to do. It does not appear in your last screenshot so it's not really related to the shortcuts of SingleFile. Can you please try to know how this shortcut has been configured? On my end, Alt-S does nothing in Chrome with SingleFile installed by default.

**Comment by gildas-lormeau** [comment] 2019-11-23 17:11
In the last video, did you use the last zip file I attached to the issue?

**Comment by doplu** [comment] 2019-11-23 17:12
alt+s is what I use normally for saving webpages with Singlefile. ;) I have added it myself before. ;) Right now for tests I use the default behaviour so I am sure this is not what is causing the bug. ;)
>In the last video, did you use the last zip file I attached to the issue?
yes the last one : C:\prog\singlefile-extension-chromium 
Thanks ;)

**Comment by gildas-lormeau** [comment] 2019-11-23 17:16
FYI, "CTRL+Shift+U" *is* associated to "save all tabs" in your settings (see your screenshot). I don't know if this was the same for "alt-S".

**Comment by gildas-lormeau** [comment] 2019-11-23 17:18
You also have to know that if you press the shortcut "CTRL+Shift+U" multiple times then you're actually saving all tabs, cancelling all (remaining) tabs, saving all (remaining) tabs and so on each time you press the shortcut.

**Comment by doplu** [comment] 2019-11-23 17:30
You're right for saving all tabs. I did the error today when I have removed your addon fully. Sorry. ;(

I have removed any shortcuts and I did a new video (incognito mode + only click on addon button + the only option beside the default one - reset - is auto close feature ON). Please see video :
https://filebin.net/wgujctljrj0sh8oo/20191123182216.mp4?t=l48tuqq7

**Comment by gildas-lormeau** [comment] 2019-11-23 17:33
I don't know if the incognito mode does not introduce its own issues right now. Can you do the same test in normal conditions and make sure you use the zip I attached?

**Comment by gildas-lormeau** [comment] 2019-11-23 17:41
It looks like I can finally reproduce the issue in incognito mode \o/. I'm checking what's wrong.

**Comment by doplu** [comment] 2019-11-23 17:42
I did a new video (not in incognito mode) for you with all settings ! ;)
https://filebin.net/zyu2uh5bduvcdrvw/20191123183731.mp4?t=57uf1238

**Comment by gildas-lormeau** [comment] 2019-11-23 18:06
Thank you very much and sorry for all the tests I asked you. It was really hard for me to reproduce it. The strange fact is that I updated Chrome today though, just when I began to try to reproduce your issue. 

I think was able to find the cause of the bug. I need to do more tests but it looks like it's a (big) regression in Chrome. Generally speaking, SingleFile can detect when a page is reloaded by receiving an event from Chrome. In such cases, it cancels the current download (i.e. if you refresh a page when SingleFile is processing it, the download will be cancelled). The regression is that Chrome sends an event to SingleFile to indicate the tab was reloaded whereas it's simply not true. Consequently, SingleFile cancels the save in progress.

**Comment by doplu** [comment] 2019-11-23 18:14
My pleasure. Thank you for your explanations. ;) Fingers crossed. ;)

**Comment by gildas-lormeau** [comment] 2019-11-23 18:24
Since your title was clearly indicating it, do you confirm this issue appeared just after you updated Chrome?

**Comment by gildas-lormeau** [comment] 2019-11-23 18:27
Here is the bug on the tracker of Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1014850

**Comment by gildas-lormeau** [comment] 2019-11-23 19:52
I think I fixed the issue in SingleFile and SingleFileZ. Unfortunately, publishing updates on the store of Chrome is now very painful. The quickfix won't be available on the store at least before 10 days. I pinged the only guy that could help to make things faster with the most efficient channel to contact a guy at Google: Twitter, cf. https://twitter.com/check_ca/status/1198324954867150850.

You have 3 options to benefit from the update asap:
 - switch to Firefox and install the signed extension (xpi file) from the homepage here because, well, it's complicated with the store of Mozilla these last days... I highly recommend this solution though
 - install manually the extension by using the zip of the master branch of the project https://github.com/gildas-lormeau/SingleFile/archive/master.zip. You'll get an annoying popup telling you that you installed an extension in the Dev mode each time you will start the browser.
 - connect to twitter and convince @DotProto the developer advocate of Google for extensions to publish more quickly the bugfix for the regression they introduced in production this week-end. That's the second time in a row that I report a regression in Chrome affecting SingleFile during a week-end. I can't wait for the third one the 24th December!

**Comment by gildas-lormeau** [comment] 2019-11-27 14:52
I just uploaded the new version on the store of Chrome. I hope it will be available soon for download. Usually, the delay to wait is approximately 7 days.

**Comment by joepsend** [comment] 2019-11-27 19:28
This may not be related, but I just want to let you know that I have been having problems saving multiple-tabs in Firefox for few weeks. The maximum that would be saved at one time was 16 tabs and the rest would be listed as pending. After updating to 1.13.23, the problem was solved and I am once again able to save all tabs. (BTW, thank you for providing the instructions on how to update SingleFile manually!)
 
SingleFile is such a brilliant extension! I used to use similar extension for many years called UnMHT but that is no longer maintained and I actually stopped updating Firefox just to keep the extension working. That extension was more important to me than the browser itself. A friend pointed me to SIngleFile and the rest is history. Thank you so much for creating this.

**Comment by gildas-lormeau** [comment] 2019-11-27 19:44
@joepsend Thank you also for the feedback! Actually, these two issues were not directly related. The "pending saves" view I implemented introduced a regression in Firefox which was somewhat similar. I'm glad to hear the latest version solved definitely this issue (BTW, you can download it from the store now). It's indeed sad that UnMHT is not maintained anymore. I have not used it but I heard a lot of good things about it. Maintaining extensions for years is not always an easy task. I hope SingleFile will fulfill your needs and you'll be happy to use Firefox Quantum for the next few years :)

**Comment by gildas-lormeau** [comment] 2019-12-01 10:58
The version 1.13.28 which fixes this issue is now available for download on the store of Chrome.

**Closed by gildas-lormeau** 2019-12-01 10:58 UTC
Labels: chrome bug
