### ISSUE TITLE
script:resource://gre/modues/extensioncontent.jsm:1074

### ISSUE THREAD

**Issue by leela52452** [gildas-lormeau/SingleFile#416] opened 2020-05-17 03:08 UTC
singlefile: 1.17.14
fennec: 68.8.0
issue URL: https://en.m.wikipedia.org/wiki/Zoia_Ceau%C8%99escu

make sure all sections are NOT collapsed.

**Screenshots**
![Screenshot_2020-05-17-08-16-02](https://user-images.githubusercontent.com/52065244/82134832-9324e980-97eb-11ea-83df-58b968dadcf9.png)

**Comment by gildas-lormeau** [comment] 2020-05-17 09:39
Please see https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#singlefile-is-slow-on-my-computertabletphone-can-it-run-faster

**Comment by leela52452** [comment] 2020-05-17 10:11
> Please update the extension and also see https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#singlefile-is-slow-on-my-computertabletphone-can-it-run-faster

`The default configuration of SingleFile is optimized to produce small pages. `

so this is not a bug ;)

**Comment by gildas-lormeau** [comment] 2020-05-17 10:17
No, it's just a bit slow sometimes on mobile devices ;)

**Comment by gildas-lormeau** [comment] 2020-05-20 23:55
I'm closing this issue because it's not a bug and there's nothing more I can do than proposing you to disable these options. Feel free to reopen it if necessary.

**Closed** 2020-05-20 23:55 UTC
