### ISSUE TITLE
Two bugreports

### ISSUE THREAD

**Issue by AliM1988** [gildas-lormeau/SingleFile#97] opened 2018-11-20 22:31 UTC
Hi 
I faced two issues in this RUL: https://talachart.ir/4-types-of-gaps-in-the-market/

1) The images do not included in saved page.
2) To see the top header and the left bar, we must scroll up at first, then click save. Othervise (for example, if you scroll down to the middle of page) those bar is disappeared or incompleted.

OS: Win 8
Browser: Chrome v70.0.3538.102 (Official Build) (64-bit)
Tested browser for saved HTML file: Chrome , Firefox, IE

Thanks in advance
Regard

**Comment by gildas-lormeau** [comment] 2018-11-20 23:36
Hi,

Thanks for reporting the issues.
1. I cannot reproduce it. I did the test on Win 10 Pro, Chrome 70.0.3538.102 (Official Build) (64-bit) and 70.0.3538.110 (Official Build) (64-bit). This file [آشنایی با ۴ نوع از گپ_های بازار - طلاچارت (2018-11-20 12_26_27 AM).zip](https://github.com/gildas-lormeau/SingleFile/files/2601976/_.-.2018-11-20.12_26_27.AM.zip) is the saved page. I doubt the OS ot the version of Chrome is responsible of the issue. Did you change any option? Can you try to disable all other extensions to see if this fixes the issue?
2. It's a common issue on websites where the header resizes itself when scrolling down. I think I can implement something to circumvent this by faking a scroll to the top of the page. It will require a new option though because it will be based on a hack.

**Comment by AliM1988** [comment] 2018-11-21 16:18
Hi
Thank you for checking. 
About the file you sent, I did some tests:
- Opening in Chrome 70.0.3538.102 & Opera 56.0.3051.52:
It is OK but when you right-click on the images and select "Open image in new tab" , no image is displayed.

- Opening in FireFox v30 & IE v10:
No image is displayed in the webpage.

note1: I want to use the extension to archive many webpages and I want these open correctly in the all versions of all browsers (Like native method of saving file+folder)

note2: I checked some pages of the mentioned URL has not this problem. for example: https://talachart.ir/candlestick-patterns-part-1/

Regard

**Comment by gildas-lormeau** [comment] 2018-11-21 18:44
Hi,

The issue you described is fixed in the version 1.8.65. Actually, this issue is also related to the option "group duplicate images together". This option detects repeated images in the page and apply a transform in the page in order to store them one time only. There are 2 cons. This transform is compatible with modern browsers only and the repeated image cannot be saved as easily as a normal image with the context menu. Most of the time, this feature concerns avatars or minor graphical elements so it's not really an issue. If you think this could be an issue for you then I recommend to uncheck the option "group duplicate images together". This will also solves the compatibility issues with old browsers.

**Comment by AliM1988** [comment] 2018-11-21 20:19
In the mentioned URL unchecking option "group duplicate images together" cause a huge file size and the result file is not same as the main webpage.
However, The issue (no. 1) is solved in v1.8.65 completely and the result file works fine with other browsers. Thank you very much!

Regard

**Comment by gildas-lormeau** [comment] 2018-11-21 20:43
You're welcome. I confirm it can produce bigger files sometimes but not for the URLs for mentioned. On my end I get files weighting respectively 1MB for 1.7MB for the 2 URLs. Make sure "remove images for alternative screen resolutions" is checked.

**Comment by AliM1988** [comment] 2018-11-21 21:55
I found some other minor bugs. These don't bother me, but I report them for improvement in future and expressing my gratitude:

Test URL: https://talachart.ir/4-types-of-gaps-in-the-market/
Browser to create saved file: Chrome v70.0.3538.102 (Official Build) (64-bit)
Browsers to view saved file: Chrome v70, Opera v56, Firefox v30 & IE v10

The issues:
- issue (no. 2) in first post. The issue is not seen in similar extension "Page Saver". 
- If you change some options of extension, you must refresh already loaded webpage at first, then click the button to make HTML file.
- In the test URL, saved file has not some JavaScript abilities even option "remove scripts" is unchecked such as auto-hide header, being left bar always on top, search button, menu "دسته بندی" , ...
Note that this issue there is in another similar extension "Save Page WE", but it is not seen in extension "Page Saver". 
- In URL: https://talachart.ir/faq-coins/ , in saved file, the + buttons don't work to show hidden texts and the font is missing (even option "remove alternative fonts to woff/otf and unused fonts" is unchecked).
- If there is ZWNJ characters in Title of webpage, it convert them to "_" as file name. See "کندل‌ها" word in URL: https://talachart.ir/how-to-trade-candlestick-wicks/ .  It's better no conversion or convert to space.
- The infobar of saved file works on chrome only (option "Allow access to file URLs" is enabled)

Regard

**Comment by gildas-lormeau** [comment] 2018-11-21 22:41
Thank you. Regarding the issues, here are some responses:
 - I tried "Page Saver" with the URL you provided. I does not work at all on my end. The CPU goes to 100% and it never downloads the saved page.
 - The issue with the header, the left menu, the + button etc. are the same one. It's related to JavaScript. I'll do my best but I will never guarantee that JavaScript will work because most of the time it does not. That's why scripts are removed by default. I also consider it's much safer from a security point of view.
 - I cannot reproduce the issue related to invalid characters in filenames. I'm using Windows 10 Pro and I get as filename "چگونه سایه کندل_ها را ترید کنیم؟ - طلاچارت (2018-11-21 23_33_49).html". I did this test on the latest version of Chrome and Firefox.
 - The last issue is mentioned on main page of the project, see [Known Isssues](https://github.com/gildas-lormeau/SingleFile#known-issues)

**Comment by AliM1988** [comment] 2018-11-22 00:02
- You didn't response 2nd issue.
- About "Page Saver", I confirm that high CPU usage, but finally it make output. (see attachment)
- You didn't response 4th issue. In native save (file+folder) there isn't this issue.
- About my last issue, I enabled the option "Allow access to file URLs" and output file has infobar, but can be shown in Chrome only not Opera,Firefox,IE.

About location of infobar, I prefer it be the right but in auto-hide form (If it is possible). Othervise, it's better smaller.

**Comment by AliM1988** [comment] 2018-11-22 02:09
> Hi,
> 
> The issue you described is fixed in the version 1.8.65. Actually, this issue is also related to the option "group duplicate images together". This option detects repeated images in the page and apply a transform in the page in order to store them one time only. There are 2 cons. This transform is compatible with modern browsers only, and the repeated image cannot be saved as easily as a normal image with the context menu. Most of the time, this feature concerns ads, avatars or minor graphical elements so it's not really an issue. If you think this could be an issue for you then I recommend to uncheck the option "group duplicate images together". This will also solve the incompatibilities with old browsers.

Hi again
I faced same issue in 2 below URL. I think it's concern to SVG+XML image type.
- https://talachart.ir/methods-of-determining-the-profit-and-stop-loss-part-i/ (2 of 7 images have problem)
- https://talachart.ir/broke-confirmed-by-trading-volume/ (2 of 3 images have problem)

Regard

**Comment by gildas-lormeau** [comment] 2018-11-22 14:45
The JavaScript issue is fixed, see https://github.com/gildas-lormeau/SingleFile/issues/98.

**Comment by gildas-lormeau** [comment] 2018-11-22 14:49
The last issue you described is a feature. I already explained the pros and cons [here](https://github.com/gildas-lormeau/SingleFile/issues/97#issuecomment-440771302). Please unckeck "group duplicate images together."

**Comment by gildas-lormeau** [comment] 2018-11-22 14:55
I'm not able to reproduce the issue related to invalid characters. On my end, if I set "test/{page-title} ({date-iso} {time-locale}).html" as template, I don't see any "_" for the characters you mentioned in the filename. Please file a separated new issue describing more precisely how to reproduce the issue.

**Comment by gildas-lormeau** [comment] 2018-11-22 14:56
To display the infobar on Firefox, install the extension first. The infobar will be displayed only when the extension is installed.

**Comment by gildas-lormeau** [comment] 2018-11-22 14:58
Please file a bug describing what kind of behavior you would like to see for the infobar. My question was more about the fact that you write from right to left. I was wondering if it would make more sense to display it in the left part of the page. It looks like this is not the case. If I'm wrong, please file a separated issue.

**Comment by gildas-lormeau** [comment] 2018-11-22 14:59
I'm closing this issue. Feel free to create new ones for each issues, as suggested in my previous responses.

**Closed by gildas-lormeau** 2018-11-22 14:59 UTC

**Comment by gildas-lormeau** [comment] 2019-04-16 22:31
@AliM1988 I just saw your comment on ghacks and I remembered I fixed recently the issue "If you change some options of extension, you must refresh already loaded webpage at first, then click the button to make HTML file."

By the way, note that you can now easily change your settings with using the side pane.
