### ISSUE TITLE
Image not included in html file

### ISSUE THREAD

**Issue by streetwolf** [gildas-lormeau/SingleFile#255] opened 2019-08-19 13:52 UTC
**Describe the bug**
Image not included in html file.

**To Reproduce**
1. Go to https://www.msn.com/en-us/money/realestate/how-much-house-dollar200k-can-buy-you-in-30-major-cities/ss-BBOX1FN?li=BBnbfcN&fullscreen=true#image=1

2. Invoke SingleFile for the page.

**Expected behavior**
Image should be displayed

**Environment**
 - OS: Win10 Pro 
 - Browser: Firefox Fx70 Nightly
 - Version: 64

**Comment by gildas-lormeau** [comment] 2019-08-19 15:13
On my end, Firefox (Dev edition) refuses to display the image. I did a test in Chrome and it was okay. I need to investigate more on this strange issue...

**Comment by gildas-lormeau** [comment] 2019-08-19 21:10
I can't reproduce your issue with SingleFile. I did the test in Firefox and Firefox Developer Edition and in both cases, the saved page contains the image. However, I see this problem with SingleFileZ. Were you referring to the latter?

**Comment by streetwolf** [comment] 2019-08-19 21:13
I’m using SingleFile NOT SingleFileZ.  Also I do not get the usual text that is displayed as the site is being SingleFilenized.


--- Gary

________________________________

**Comment by gildas-lormeau** [comment] 2019-08-19 21:17
You seem upset with my answer. I'm sorry about that. SingleFile and SingleFileZ are two personal projects that I decided to share in open source. I also do my best to fix bugs. 
Could you please attach the saved page?

**Comment by streetwolf** [comment] 2019-08-19 21:47
I'm not upset.  I just wanted to make sure you knew which add-on I was using since the names are identical except for the 'Z' at the end of one.

As fate would have it I am now getting the image.  I have no idea what has changed when I saved the file the first time and now.  Go figure.

The text in the bottom left corner still doesn't appear.  Is this normal or a problem?

**Comment by gildas-lormeau** [comment] 2019-08-19 22:41
I know the Z is important. Coincidentally, the bug you described exists (it's fixed now but not published yet) in SingleFileZ so I wanted to make sure that there was no misunderstanding.

Here is what I see in my browser. There is no text at the bottom left corner on my side.
![image](https://user-images.githubusercontent.com/396787/63304312-d7c63780-c2e2-11e9-9f55-a682d5f27f1f.png)

**Comment by gildas-lormeau** [comment] 2019-08-23 16:32
@streetwolf any news?

**Comment by streetwolf** [comment] 2019-08-23 16:33
I am now getting images.


--- Gary

________________________________

**Comment by gildas-lormeau** [comment] 2019-08-23 16:35
And the text?

**Comment by streetwolf** [comment] 2019-08-23 16:36
I am getting the text from the web site but not the text on the bottom left from your add-on as it saves things.


--- Gary

________________________________

**Comment by gildas-lormeau** [comment] 2019-08-23 16:42
Too bad I cannot display this text at all on my end, cf. my screenshot in my previous answer https://github.com/gildas-lormeau/SingleFile/issues/255#issuecomment-522781445. If you can, please give me more details, otherwise I won't be able to fix this bug.

**Comment by streetwolf** [comment] 2019-08-23 16:45
There is no more info I can supply.  You know what text I am talking about?  Your add-ons text.  If you aren’t getting it then you are in the same boat as me and you shouldn’t need my help.


--- Gary

________________________________

**Comment by gildas-lormeau** [comment] 2019-08-23 16:53
I am sorry. I did not understand you were talking about what I call the "logs window". I cannot reproduce this bug though, cf. the screenshot below.

![image](https://user-images.githubusercontent.com/396787/63609078-af865380-c5d6-11e9-8d8b-9df8ea9f38a4.png)

Can you please confirm that if you export your settings via the options page and open the saved file in a text editor, you can find the content '"logsEnabled": true,' and not `"logsEnabled": false,`?

**Comment by streetwolf** [comment] 2019-08-23 16:55
It was set to false.  I changed it to true and all is fine now.


--- Gary

________________________________

**Comment by gildas-lormeau** [comment] 2019-08-23 16:56
Great! I'm a bit surprised it was set to `false` though. Did you change it or use the "import" feature in the past?

**Closed** 2019-08-23 17:17 UTC

**Comment by gildas-lormeau** [comment] 2019-08-23 17:33
I close the issue because it's fixed actually. Thank you for having reported it because it allowed me to identify a similar issue in SingleFileZ.
