### ISSUE TITLE
The Extension creates only cryptical File Names like "3f6b9e42-6e6c-4f5..."

### ISSUE THREAD

**Issue by Blackdos** [gildas-lormeau/SingleFile#148] opened 2019-02-03 12:39 UTC
Hello,

sadly SingleFile stopped working with Version 1.9.50 and Chrome Version 72 as normaly. 
1. The Extension creates only cryptical File Names like "3f6b9e42-6e6c-4f5..:"
2. It saves Pages only in normal mode, but not in incognito Mode like bevor, even with the same url
3. It takes about 15 seconds after closing the save dialog till the save operation runs

**To Reproduce**
Go to "https://www.heise.de/select/ct/2017/06/1489333575587058#zsdb-article-links"
Press save After Delay, the Page is saved
Open same Page in Incognito mode, press Save
Save Dialog appears, cryptic Filename, but no File is saved

Same URL's in Firefox
Filenames will be genered as expected with Titletag in normal an InPrivate Mode and file will be saved

Generell behaviour dosn't change with or without Save Dialog active

**Expected behavior**
As bevor with < 1.9.50 after pressing Save, the small Dialog appears for the Filename and then the file is saved...
In Firefox it's not possible to change the filename bevor saving the file.

**Environment**
 - OS: [win10 Pro 64bit
 - Chrome Version 72.0.3626.81 (Official Build) (64-bit)
 - Firefox Quantum 65.0 (64-Bit)

Settings:
{
  "profiles": {
    "__Default_Settings__": {
      "autoSaveDelay": 1,
      "autoSaveLoad": false,
      "autoSaveLoadOrUnload": true,
      "autoSaveUnload": false,
      "backgroundSave": true,
      "compressCSS": true,
      "compressHTML": true,
      "confirmFilename": true,
      "confirmInfobarContent": false,
      "contextMenuEnabled": true,
      "displayInfobar": false,
      "displayStats": false,
      "filenameConflictAction": "prompt",
      "filenameTemplate": "{page-title}.html",
      "groupDuplicateImages": true,
      "infobarTemplate": "",
      "loadDeferredImages": true,
      "loadDeferredImagesMaxIdleTime": 1500,
      "maxResourceSize": 10,
      "maxResourceSizeEnabled": false,
      "removeAlternativeFonts": true,
      "removeAlternativeImages": true,
      "removeAlternativeMedias": true,
      "removeAudioSrc": true,
      "removeFrames": false,
      "removeHiddenElements": true,
      "removeImports": true,
      "removeScripts": true,
      "removeUnusedFonts": true,
      "removeUnusedStyles": true,
      "removeVideoSrc": true,
      "saveRawPage": false,
      "shadowEnabled": true
    }
  },
  "rules": []
}

**Comment by gildas-lormeau** [comment] 2019-02-03 14:09
Hi, thanks for reporting the issue. It looks like you're suffering from this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=892133.

Today, the only solution I can propose you is to disable teh option "Misc. > Save pages in background".

**Comment by Blackdos** [comment] 2019-02-03 14:19
Hi,

thanks for the fast response. Background Save was one of the options I forgot to change for playing with the error. If I disable Background Save, all my problems vanish, so I'm fine again. Thanks for the fast response.

**Comment by gildas-lormeau** [comment] 2019-02-03 14:58
@Blackdos Actually, I recommend you to read the troubleshooting section in the README first. The workaround for this issue was already documented ;)

**Comment by gildas-lormeau** [comment] 2019-02-03 16:04
I was able to reproduce this issue. I was able to fix it by re-installing Chrome.

**Comment by gildas-lormeau** [comment] 2019-02-03 18:45
Previous issues similar to this one:
- https://github.com/gildas-lormeau/SingleFile/issues/58
- https://github.com/gildas-lormeau/SingleFile/issues/130

**Comment by gildas-lormeau** [comment] 2019-02-18 20:31
I don't know if it's related but I would be interested to know if the procedure described here https://www.ghacks.net/2019/02/18/fix-chrome-72-extensions-not-working-correctly-e-g-adblockers/ fixes the issue.

**Comment by gildas-lormeau** [comment] 2019-03-08 15:53
I think this issue is fixed with #172. Feel free to re-open this issue if you think this is not the case.

**Closed by gildas-lormeau** 2019-03-08 15:53 UTC
Labels: chrome bug, unknown issue
