### ISSUE TITLE
Today's update of Firefox extension changed something - not working properly, timing out

### ISSUE THREAD

**Issue by activebiz1** [gildas-lormeau/SingleFile#511] opened 2020-10-09 16:28 UTC
**Describe the bug**
Since I use this extension daily, a lot, I have never experienced a problem, even with intense content pages. It saves everything perfectly. Until ca. 3 hours ago: I see that the latest update to this extension took place just about 3 hrs ago CST [US].
Suddenly Firefox throws withing the first 5 seconds the top bar that this extension needs to be disabled because it times out, takes to long.

I tried it with different pages [that normally saved within a few seconds without a hitch] and now I get the same popup from firefox v.81.0.1
It has definitely something to dowith the last update from today October 9th, 2020.
I also tried by disabling save video, audio etc, but it did not make any difference. Since this occures now on pages I had previously [last night] saved with no problem - I know get the time-out bar every time, literally within the first few seconds.

Also closed the firefox browser, start a new window, but same results.
I rebooted my pc, still the same problem.
 Maybe a re-upload of your latest update might help?

I appreciate your work. And hope this can be resolved.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - OS: [e.g. Win10 Pro, Ubuntu 18.04.1, Android 7.1.2]
 - Browser: [e.g. Chrome, Firefox]
 - Version: [e.g. 64]

**Additional context**

**Comment by activebiz1** [comment] 2020-10-09 16:38
snapshot:
![2020-10-09_firefox_singlePage](https://user-images.githubusercontent.com/29712853/95609131-de9e9500-0a23-11eb-9c2d-8c68e209fadc.jpg)

**Comment by gildas-lormeau** [comment] 2020-10-09 17:09
Unfornately, I cannot reproduce the issue you described. Moreover, the update I published is very minor and related to the annotation editor only (this version actually reverts a bad fix in that I introduced in version 1.18.14). Does installing a previous version (e.g 1.18.12) fix the issue? see https://addons.mozilla.org/en-US/firefox/addon/single-file/versions/

**Comment by gildas-lormeau** [comment] 2020-10-11 22:36
@activebiz1 I published some versions meanwhile, any news?

**Comment by gildas-lormeau** [comment] 2020-10-14 10:25
I'm closing this issue since I cannot reproduce it and I do not have enough info to understand its cause. Feel free to comment it or reopen it though.

**Closed by gildas-lormeau** 2020-10-14 10:25 UTC
