### ISSUE TITLE
Auto save on tab removal

### ISSUE THREAD

**Issue by sanjeevApple** [gildas-lormeau/SingleFile#1457] opened 2024-05-14 22:46 UTC
For questions, please create or update a thread here: 
https://github.com/gildas-lormeau/SingleFile/discussions

Please ensure that you do not find an answer before reporting the issue:
 - in the FAQ: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md
 - in the list of known issues: https://github.com/gildas-lormeau/SingleFile#known-issues
 - in the help page embedded in the extension

**Describe the bug**
1) Trying to see how to simulate this through puppeteer. Load the page, scroll to the bottom, close the page to save it automatically.
2) By default auto save is disabled, so made changes in the code locally and rebuild the extension to enable auto-save this tab.
3) I also changed the default settings so auto save on tab removal option is on by default.
4)  Now the issue is that this still doesn't save the page on tab close, unless auto save radio button is toggled manually. It seems that there might be a list of tabs with auto save option on, which is missing, and turning auto save this tab on by default doesn't add it to that list.

Any help would be greatly appreciated, thanks...

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - OS: [e.g. Win10 Pro, Ubuntu 18.04.1, Android 7.1.2]
 - Browser: [e.g. Chrome, Firefox]
 - Version: [e.g. 64]

**Additional context**

**Comment by gildas-lormeau** [comment] 2024-05-27 19:18
What changes did you apply in SingleFile (related to this issue)?

**Comment by sanjeevApple** [comment] 2024-05-30 21:51
Sorry for the delay. I made changes in src/ui/bg/ui-menus.js to turn on MENU_ID_AUTO_SAVE_TAB to true. I also made changes in src/core/bg/config.js to enable autoSaveUnload: true. I think the issue was may be rebuilding the chromium zip file, because I was making the changes in the exploded directory directly and loading the extension through puppeteer. But these changes were being picked from lib, so rebuilding solved the issue.

Now it has been working really well, which helped solve the problem of saving long and content rich pages through singlefile cli. But from time to time, autosave on page unload does not save the file. 

Here are the steps:
1) Auto save this tab is the default in my set up and auto save on unload is true.
2) I load the extension through puppeteer, go to the page www.apple.com/apple-vision-pro, simulate scroll to the bottom, and then call goBack to basically unload the page. This normally works for most pages, but from time to time fails for apple vision pro.
3) You can easily simulate this in normal set up. Open chrome, get the singlefile extension, turn autosave on unload, open a tab, and turn on auto save this tab, and load the Url. Press on back arrow, and no file is saved. Use another Url like www.apple.com or www.apple.com/watch, everything works fine.

I think for some reason the save message is not coming through for some pages, in case they are heavy in content. I tried giving it time before I go back in that tab or before I close the browser, but it just does not produce a file.

**Comment by gildas-lormeau** [comment] 2024-06-03 13:22
Thank you for the feedback. I'm glad to hear that you were able to find the cause the problem. I tried to reproduce the bug as described in the step 3 but I cannot reproduce it. Every time I do the test with www.apple.com/apple-vision-pro, the page is downloaded as expected after pressing the back button. Do you have other extensions installed?

**Comment by gildas-lormeau** [comment] 2024-07-22 22:12
I'm closing the issue. Feel free to comment it if you have more info though.

**Closed by gildas-lormeau** 2024-07-22 22:12 UTC
