### ISSUE TITLE
how could SingleFile save "several parts" of a webpage in one file with one time?

### ISSUE THREAD

**Issue by qinggonghui** [gildas-lormeau/SingleFile#134] opened 2019-01-17 03:14 UTC
**Describe the solution you'd like**
SingleFile could sure save selection of a webpage. But how could it save "several parts" of a webpage in one file with one time?

e.g., as the attachment, if I want to save area A and area B without area C, it seems like SingleFile can't get it.(only could select A or A+B+C)
Example webpage add:
https://www.rfidjournal.com/articles/view?2481

So I suggest if SingleFile could let me select more then one area when meeting this condition.

Think you :)

![2019-0117_104446](https://user-images.githubusercontent.com/46115881/51293941-cc104b00-1a4b-11e9-99df-28540376dc9b.png)

**Comment by gildas-lormeau** [comment] 2019-01-17 10:35
I agree, this would be a nice feature to have. I'm wondering how to implement this from a user interface/experience point of view. Today, when the user clicks with the left button, the zone is selected and immediately saved. With this proposal, the user would need an additional step to save the page. Do you have an idea on how to present this to the user? I have some ideas, I just want to get your point of view since you opened the issue :)

**Comment by qinggonghui** [comment] 2019-01-18 04:06
Before useing SingleFile, My idea is : 1- clicking and holding the left button and selecting the contents which I want to save; 2-clicking the button of SingleFile to complete the saving.(Meanwhile, clicking the button of SingleFile with no selection action goes to the default-- saving the whole page)

But I found SingleFile needs users to select a "frame" of webpage first. And the "frame" includes contents which users need(Not my area, so I'm not sure if the word "frame" is correct). I guess selecting a "frame" makes the saved webpage keep its original format or typesetting(A highlighting of SingleFile， like this function very much ). 

Since SingleFile ask users to right click and "save selection" to trigger the "frame" selecting, the next step perhaps is letting users select several "frame" by holding Ctrl(releasing Ctrl will let users to select again, same as microsoft app's operation ). And then clicking the SingleFile button to complete the saving.

My area is electric and electronic. So I'm not sure if the suggestion is available :)

**Comment by gildas-lormeau** [comment] 2019-01-18 21:42
Your first proposition is almost implemented today actually. With SingleFile, there are 2 selection modes. The one you cited should work but only for 1 selected content because your OS/browser does not allow multi-select. If this was allowed, it would be quite trivial for me to add the missing code to support multi-select. Maybe there are extensions that enable multi-select though... I need to investigate more on this.

I really like you proposition regarding the second selection mode because it does not involve adding UI elements in the page. I was completely forgetting that it could be managed with key/mouse click combinations. So, I think I'll implement it soon if it is technically possible (I have a minor doubt). Thank you very much!

**Comment by gildas-lormeau** [comment] 2019-01-18 22:01
Update: I discovered that Ctrl allowed to do a multi-select... It's never too late! So I'll implement at least your first proposal since it should the easiest implementation.

**Comment by qinggonghui** [comment] 2019-01-19 11:42
With the first proposal, I'm just not sure if SingleFile could keep webpages' original format and typesetting when saving a multi-select page. 

Anyway, I’m a outsider in  web programming. Maybe that's not a problem. Looking forward to this new function. Good luck : )

**Comment by gildas-lormeau** [comment] 2019-01-21 21:32
Hi @qinggonghui, I implemented the first proposal in the version 1.9.36. It will not work in Chrome because it does not support non-continuous selections natively (i.e. Ctrl + Select doe not work). Please let me know what you think about it.

**Comment by qinggonghui** [comment] 2019-01-22 09:12
Firstly, thank you very much. You are so effective : )

Still the previous webpage,it could be saved by holding left click and dragging the area to select as the figure 1&2 in attachment shows. Even the button which can't select highlights in the red ellipse in figure 1 could also saved by SingleFile.

But sometimes the SingleFile may not work. The example selecting (realized by both "holding left click and dragging to select" and "shift + left click to select") shows in figure 3 while the result in figure 4 gives an undesirable comes.

SignleFile could sitll keep webpages' original format and typesetting when save selection part of a web so far. I'll save some other webpages and report if there are other bugs. 

![2019-0122_134344](https://user-images.githubusercontent.com/46115881/51524246-9e227080-1e68-11e9-964c-639dd519fca8.png)

**Comment by gildas-lormeau** [comment] 2019-01-22 13:53
I fixed the issue shown in figure 3 & 4 and the missing image in my saved page in the version 1.9.37. Note that the whole text will be saved (it won't end at "she says.") because it is contained into a single SPAN element and SingleFile cannot split the text in such case today.

**Comment by qinggonghui** [comment] 2019-01-23 10:01
That's make sense and I'll keep testing.

I found that choosing the "save selection" at right click context menu without selecting anything will auto execute saving and give a blank .html file. 

I'm not sure the logic of "save selection". If selecting nothing and only choosing the  "save selection" at right click context menu, Will the "frame" appear and let user to select a part of a webpage(like the previous version shows)?

**Comment by gildas-lormeau** [comment] 2019-01-23 12:33
Regarding the save selection issue you described, it is a regression. I published the version 1.9.38 to fix it.

**Comment by gildas-lormeau** [comment] 2019-01-23 23:39
@qinggonghui, the version 1.9.39 adds the support of the Ctrl key when selecting "frames". You must press Ctrl while left-clicking to select a "frame", When you're finished, do the last selection without pressing Ctrl.

**Comment by gildas-lormeau** [comment] 2019-01-23 23:54
"Minor" note: it works only with Firefox.

**Comment by gildas-lormeau** [comment] 2019-01-24 14:44
I just deployed the version 1.9.40 which fixes the previous issue.

**Comment by qinggonghui** [comment] 2019-01-25 04:07
Yes, the save selection function works well now!

I just want to report the bug and find you already fixed it. Think you very much :+1:

**Comment by gildas-lormeau** [comment] 2019-01-25 08:40
You're welcome! I'm closing this issue. Please feel free to re-open it if you think the current implementation has still issues.

**Closed by gildas-lormeau** 2019-01-25 08:40 UTC
Labels: feature request
