### ISSUE TITLE
SingleFile does not work on Android Microsoft Edge at all

### ISSUE THREAD

**Issue by NilsHoyer** [gildas-lormeau/SingleFile#1470] opened 2024-06-07 14:38 UTC
I've installed "Edge Canary" on my Android device. Inside the settings, "Information about Edge" I taped several times to the version information, until the "Developer" features are enabled.

Now, inside the Settings, there was a new entry at the bottom: "Developer options", which allows to "Install Extensions by Id". On this way, I installed SingleFile.

After this, nothing happens, if I select the SingleFile extension inside the Extension menu of Edge.

... indeed, I don't know if this is a problem of SingleFile or of Edge Canary, which is a preview with the new feature to use extension at all.

**Comment by gildas-lormeau** [comment] 2024-06-10 14:32
I didn't know Microsoft was working on extension support for Edge on Android. That's great news :). 

I can confirm, however, that I'm reproducing the problem you described. I did a debugging session with the Android emulator on my machine. It seems that clicking on the SingleFile entry in Edge doesn't trigger the corresponding code which is an unexpected behavior. Maybe it's a temporary bug in Edge.

**Comment by NilsHoyer** [comment] 2024-06-11 05:59
... or Microsoft don't know about this issue and would be happy if you report it?

**Comment by gildas-lormeau** [comment] 2024-06-11 07:32
I can't say with 100% certainty that the bug is in Edge. For that, I'd have to code a test extension isolating the bug.

**Comment by gildas-lormeau** [comment] 2024-06-18 18:36
For the record, the same issue has been reported here: https://www.reddit.com/r/Android/comments/1bp429e/comment/l4zbvh6.

**Comment by gildas-lormeau** [comment] 2024-09-09 21:46
I'm closing this issue because it's not a bug in SingleFile. Feel free to comment it if needed though.

**Closed by gildas-lormeau** 2024-09-09 21:46 UTC
Labels: edge bug

**Comment by NilsHoyer** [comment] 2024-09-11 07:29
@gildas-lormeau: Thanks a lot for this hint. Now I can open this files on my desktop computer and I'm happy about that. 😀

**Comment by gildas-lormeau** [comment] 2024-09-11 09:52
@NilsHoyer You're welcome

**Comment by childlikx** [comment] 2025-02-19 14:20
SingleFile is now working properly in Android Edge Canary, but due to an issue with Edge, I can't access the extension options. I used an extension called [Extension Manager](https://github.com/JasonGrass/auto-extension-manager) to solve this problem.
