### ISSUE TITLE
Can't save https://www.androidauthority.com/best-android-emulators-for-pc-655308/

### ISSUE THREAD

**Issue by iG8R** [gildas-lormeau/SingleFile#205] opened 2019-05-05 16:25 UTC
**Describe the bug**
Can't save [https://www.androidauthority.com/best-android-emulators-for-pc-655308/](https://www.androidauthority.com/best-android-emulators-for-pc-655308/)
Only the shaded page with the following error is displayed:
```
A script on this page may be busy, or it may have stopped responding.
You can stop the script now, open the script in the debugger, or let the script continue.
Script: resource://gre/modules/ExtensionContent.jsm:881
```

**To Reproduce**
1. Go to [https://www.androidauthority.com/best-android-emulators-for-pc-655308/](https://www.androidauthority.com/best-android-emulators-for-pc-655308/)
2. Try saving page with SingleFile

**Environment**
 - OS: Win10 Pro
 - Browser: Waterfox
 - Version: 56.2.9 (64-bit)

**Comment by gildas-lormeau** [comment] 2019-05-05 22:06
Thanks for reporting the issue. I was able to reproduce it and the issue is fixed in the version 1.10.49 which is available for Chrome. For Firefox, it's another story. Right now, we cannot publish extensions... Meanwhile, unchecking "compress CSS content" should fix the issue temporarily.

**Comment by iG8R** [comment] 2019-05-05 22:11
Thank you.

**Comment by gildas-lormeau** [comment] 2019-05-05 22:12
You're welcome. I prefer to close the issue when it will be available on the Addon store ;).

**Closed** 2019-05-06 19:08 UTC
