### ISSUE TITLE
Network timeouts make the processing time long (~2 minutes)

### ISSUE THREAD

**Issue by abolibibelot1980** [gildas-lormeau/SingleFile#444] opened 2020-07-11 00:50 UTC
**Describe the bug**
When trying to save this page :
http://www.dvdclassik.com/forum/viewtopic.php?t=34510&start=105
SingleFile freezes at step 2, and one of Firefox's processes reaches 13% CPU usage (maxing out one virtual core on a 4C/8T CPU). Tried again after reloading, same behaviour.
Before launching SingleFile, I noticed that the page took an abnormally long time to stop loading (the little "bubble" at the top of the tab – is there a name for that ? – goes left and right for 10-15 seconds before the logo appears), considering that it's a simple forum page with no overly complex elements as far as I can see. So it may caused by some element(s) being no longer online. In which case SingleFile should stop trying to get the missing resource after a few seconds and save the page as it is.

EDIT : I tried again, this time it didn't cause a high CPU usage, and the page could finally be saved after about 2 minutes (which is obviously impractical).

**Environment**
 - Windows 7 Pro SP1
 - Firefox 78.0.2

**Additional context**
Current options :
[singlefile-settings 20200711.json.txt](https://github.com/gildas-lormeau/SingleFile/files/4905978/singlefile-settings.20200711.json.txt)

**Comment by gildas-lormeau** [comment] 2020-07-12 23:52
This issue is due to the fact that when trying to download the following resources, the server accepts the connection but never send any data. This should not cause a high CPU usage.
 - http://img11.hostingpics.net/pics/573236funnyWillFerrellquote.jpg
 - http://img11.hostingpics.net/pics/874227Openseason03.jpg
 - http://img11.hostingpics.net/pics/580574avatarDVDclassikAW.jpg

A way to circumvent the issue is to disconnect the PC from internet when SingleFile is stuck. I might add an option like a maximum delay for network responses.

**Comment by gildas-lormeau** [comment] 2020-11-14 21:10
For the record, another example of website suffering from this issue: https://mbsquad.clicforum.com/index.php

**Comment by gildas-lormeau** [comment] 2021-08-12 22:16
I'm closing this issue because:
- it is very rare
- it does not prevent the page to be saved properly

I also consider this issue is not a bug but a feature. Waiting for responses without any timeout is useful in a train with an intermittent connection for example.

**Closed by gildas-lormeau** 2021-08-12 22:16 UTC
Labels: feature request, bug
