### ISSUE TITLE
Local file useage

### ISSUE THREAD

**Issue by vojtechruz** [gildas-lormeau/SingleFile#21] opened 2014-03-23 14:19 UTC
Hello,
why is it not possible to process locally stored html files? Do you plan to add this feature? It would be ideal use case as a lot of other programs allow html export of content, but images and styles are as separate files and not contained in one file. Thank you.

**Comment by sunk818** [comment] 2016-03-28 18:02
This is a duplicate of https://github.com/gildas-lormeau/SingleFile/issues/7

**Comment by ampheta** [comment] 2016-03-29 06:22
OK

**Closed as completed** 2018-07-04 13:27 UTC
