### ISSUE TITLE
Saved page layout messed up 1.10.36

### ISSUE THREAD

**Issue by beefdrifter** [gildas-lormeau/SingleFile#191] opened 2019-04-21 17:19 UTC
**Describe the bug**
The saved layout of this page gets messed up
https://www.bleepingcomputer.com/news/software/mozilla-makes-it-easier-to-hide-tabs-in-firefox-and-unclutter-your-tab-bar/

**To Reproduce**
1. Go to 'https://www.bleepingcomputer.com/news/software/mozilla-makes-it-easier-to-hide-tabs-in-firefox-and-unclutter-your-tab-bar/'
2. Save page
3. Inspect saved file

**Screenshots**
1st screenshot is the original page
2nd screenshot is the saved page
https://imgur.com/a/5HsTVfs

**Environment**
 - OS: Win10 Pro
 - Browser: Firefox 65.0
 - Version: SingleFile 1.10.36

**Comment by gildas-lormeau** [comment] 2019-04-21 17:49
I tried to save the page and I cannot reproduce the issue you showed. On my end, the saved page is ok. Did you change any settings?

**Comment by beefdrifter** [comment] 2019-04-21 18:02
I did have different settings when I encountered the issue actually, so my apologies!
But after both resetting the settings and disabling all my other extensions, I'm still getting the same results. Is there anything else I can try?

**Comment by gildas-lormeau** [comment] 2019-04-21 18:11
No problem. I deleted my previous comment because I can reproduce the issue actually. I need to do more tests to see what's wrong. At a first sight, it looks like the issue could come from the HTML markup which could be invalid.

**Comment by beefdrifter** [comment] 2019-04-21 18:34
Ah, that's good to know. Thank you very much!

Also, is there somewhere I could go to ask general how-tos? For example, is it possible to exclude actual videos like an embedded youtube video, but still show the player with the thumbnail, so I at least know what video was in that spot when I come back to it later?

**Comment by gildas-lormeau** [comment] 2019-04-21 18:51
I confirm the issue is related to invalid markup. There are `<cnx>` tags into `<a>` tags in the page (cf. "TOP ARTICLES" box). The problem is that this is not allowed by the HTML specification. So the browser moves the `<cnx>` tags after the `<a>` tags to make the markup compliant and the layout gets messed up. I tried to save the page in MHTML with Chrome and I got the same result. The only way to solve this issue is to remove the "TOP ARTICLES" box before saving the page.

There aren't really other places where to ask general how-tos. You can send me an email if you prefer. Note that I started recently to write a [FAQ](https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md).

You should have thumbnails (and links) in Youtube videos. For example, if I go to https://www.youtube.com/ and save the page, thumbnails are present in the saved page.

**Comment by beefdrifter** [comment] 2019-04-21 19:22
Ah, thank you very much for the explanation! And yes I got the video thumbnails back after unchecking the remove frames option, which I ticked in hopes of a smaller file.

Cheers, and please do keep up the great work :)

**Comment by gildas-lormeau** [comment] 2019-04-21 19:53
Thanks! I'm closing this bus as "won't fix" because this is an issue in the page itself and I cannot really fix it on my end.

**Closed by gildas-lormeau** 2019-04-21 19:53 UTC
