### ISSUE TITLE
extension cant save Persian file name

### ISSUE THREAD

**Issue by behrouz1** [gildas-lormeau/SingleFile#1039] opened 2022-10-16 09:50 UTC
hi. Extension cant save Persian file name. Persian file name save like this (_ - _ _)
this screenshot show 2 file. first save with othr extension and secend save with single file
 please fix this bug
![si](https://user-images.githubusercontent.com/61052332/196028852-c2e405d5-7911-4feb-a4d4-9c60c5093bf8.png)

**Comment by gildas-lormeau** [comment] 2022-10-16 14:51
I cannot reproduce the bug. For example, if I try to save this page https://www.instagram.com/__taylorswift._.fanpage__/?hl=en, the name of the saved page is "بهترین پیج برای سوییفتی ایرانی (@__taylorswift._.fanpage__) • Instagram photos and videos (10_16_2022 4_50_35 PM)", as expected.

**Comment by gildas-lormeau** [comment] 2022-10-23 01:17
@behrouz1 Do you know how I can reproduce your issue?

**Comment by gildas-lormeau** [comment] 2022-11-02 21:27
@behrouz1 any news?

**Comment by gildas-lormeau** [comment] 2022-11-03 22:36
I'm closing this issue since I was not able to reproduce it.

**Comment by gildas-lormeau** [comment] 2022-11-13 12:27
@behrouz1 Note that you can reopen the issue *but* you need to provide more details please.

**Comment by behrouz1** [comment] 2022-11-14 09:18
tanks. what kind of details ? I found out sometime save correctly and sometimes save incorrectly!
page link:
https://merida.blogsky.com/1399/09/23/post-3/
https://www.bbc.com/persian/world-features-38626372

**Comment by behrouz1** [comment] 2022-11-14 09:52
sorry for delay I uploaded incorrect file here
https://www.mediafire.com/folder/7gez58b0rebvc/html

**Comment by gildas-lormeau** [comment] 2022-11-14 11:29
Thank you, I confirm I can reproduce the issue with https://www.bbc.com/persian/world-features-38626372, I'll take a loot a it.

**Comment by gildas-lormeau** [comment] 2022-11-14 19:24
I was able to identify the cause of the problem. It's due to the presence of zero-width non-joiners, see https://en.wikipedia.org/wiki/Zero-width_non-joiner. SingleFile will replace this character with "_" if it causes an error when saving the file. The fix will be available in the next version.

**Comment by behrouz1** [comment] 2022-11-17 23:35
tanks. I'm waiting for next version

**Comment by gildas-lormeau** [comment] 2022-11-20 23:19
FYI, the new version has been published.

**Comment by gildas-lormeau** [comment] 2022-11-23 16:24
Please make sure the extension is up to date (version 1.21.28). On my end, if I save https://www.bbc.com/persian/world-features-38626372, I get `میراث متنوع اوباما در سیاست خارجی_ از نوبل تا پهپاد، از 'بی_عملی' تا دیپلماسی - BBC News فارسی (23_11_2022 17_22_07).html` as filename.

**Comment by gildas-lormeau** [comment] 2022-11-23 16:27
Soory, I confirm the issue still exists on https://merida.blogsky.com/1399/09/23/post-3/, I'll try to see what's wrong. It's another issue.

**Comment by behrouz1** [comment] 2022-11-23 19:36
the extension is up to date (version 1.21.28)
 

> Please make sure the extension is up to date (version 1.21.28). On my end, if I save [https://www.bbc.com/_persian_/world-features-38626372](https://www.bbc.com/persian/world-features-38626372), I get `میراث متنوع اوباما در سیاست خارجی_ از نوبل تا پهپاد، از 'بی_عملی' تا دیپلماسی - BBC News فارسی (23_11_2022 17_22_07).html` as filename.

**Comment by gildas-lormeau** [comment] 2022-11-23 21:02
Sorry, I edited my message meanwhile.

**Closed** 2022-11-23 21:18 UTC

**Comment by gildas-lormeau** [comment] 2022-11-23 22:02
It's fixed in the version 1.21.29.

**Comment by behrouz1** [comment] 2022-11-24 23:07
problem is solved. thank you .I suggest don't close this topicfor if I see page has a problem i can report it to you

**Comment by gildas-lormeau** [comment] 2022-11-24 23:10
You're welcome! Don't worry, I receive notifications even if the issue is closed :)
