### ISSUE TITLE
The `white-space` attr will be removed after saving in Safari

### ISSUE THREAD

**Issue by tianzhich** [gildas-lormeau/SingleFile#1462] opened 2024-05-23 02:59 UTC
**Describe the bug**
Some websites saved in Safari may have styling issues because the `white-space` attribute in the saved stylesheet is removed. This problem does not occur in Chrome but does in Safari. For example, it happens on [this website](https://deriveit.org/coding/big-o-insights-106).

**To Reproduce**
1. Go to the website in Safari
2. Click on SingleFile icon and save the page
3. Open the page

**Expected behavior**
The page should display correctly without style issues caused by missing `white-space`.

**Screenshots**
**Saved in Chrome:**
<img width="1511" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/33218310/07d3a5a1-2536-4de7-8781-c9ab34391f32">

**Saved in Safari:**
<img width="1511" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/33218310/0ce6cd10-93c7-4bb9-94fc-46ed3bd1ed41">

**Environment**
 - OS: [MacOS 14.1 (23B74)]
 - Browser
     - Chrome 124.0.6367.208 (Official Build) (arm64)
     - Safari 17.1 (19616.2.9.11.7)

**Comment by gildas-lormeau** [comment] 2024-05-27 13:29
Thank you for the report. Unfortunately, I cannot reproduce it. Here is a screenshot of the saved page displayed in Safari below. I've also attached the saved page in the zip file.

<img width="1357" alt="image" src="https://github.com/gildas-lormeau/SingleFile/assets/396787/d00cfbe3-6df6-4ab3-ae83-12cf432b95ed">

[Big O Insights - DeriveIt (27_05_2024 15_26_23).html.zip](https://github.com/gildas-lormeau/SingleFile/files/15456499/Big.O.Insights.-.DeriveIt.27_05_2024.15_26_23.html.zip)

**Comment by tianzhich** [comment] 2024-05-28 03:57
This is so strange, what are your Safari version and MacOS version?

**Comment by gildas-lormeau** [comment] 2024-05-28 12:45
I'm using Safari 17.4.1 on macOS 14.4.1.

**Comment by gildas-lormeau** [comment] 2024-07-22 22:11
I am closing the issue. Feel free to comment it if you have more info though.

**Closed by gildas-lormeau** 2024-07-22 22:11 UTC
