### ISSUE TITLE
SingleFile Login API - Official (CLI)

### ISSUE THREAD

**Issue by captaindavepdx** [gildas-lormeau/SingleFile#206] opened 2019-05-07 00:38 UTC
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The ability to log into websites before saving it without executing hacky code.

**Describe alternatives you've considered (optional)**
Write custom javascript for each site - very thankful for the ability to execute js!

**Additional context (optional)**
It seems possible with puppeteer. 
https://github.com/checkly/puppeteer-examples/tree/master/3.%20login

**Comment by gildas-lormeau** [comment] 2019-05-07 11:37
The problem is that there are no standard ways to fill and validate a login form. That's why sometimes password managers can't fill them.

**Comment by captaindavepdx** [comment] 2019-05-07 15:47
Interesting, ok.

What about using puppeteer to login, referencing a 'login' js file, before executing the javascript file and downloading the website?

I've got a working script that logs into a website and takes a screenshot. Could we integrate some of it into SingleFile?

https://github.com/captaindavepdx/Login-Feature

**Comment by gildas-lormeau** [comment] 2019-05-07 19:47
I understand your needs. However I consider that it is out of scope of SingleFile which is first and foremost a Web Extension. The command line tool serves 2 purposes:
 - prove that SingleFile may run outside the context of Web extensions (this is the most important purpose)
 - automate simple captures

Moreover, there are currently 4 implementations to maintain: selenium chrome, selenium firefox, puppeteer and jsdom, cf. https://github.com/gildas-lormeau/SingleFile/tree/master/cli/back-ends and the maff conversion tool implementation based on an older version of Selenium, cf. https://github.com/gildas-lormeau/SingleFile/blob/master/maff2html/back-ends/webdriver-gecko.js. It means the changes should be applied to all of them.

From my point of view, you want a "super" CLI tool that should be a separate project (based on the library of SingleFile, i.e. the `lib` directory).

**Comment by captaindavepdx** [comment] 2019-05-07 20:23
Wow, I didn't realize a single feature could require so much additional work.

I understand, thank you for all of your help and suggestions!

**Comment by gildas-lormeau** [comment] 2019-05-07 20:25
No problem. I keep the issue open so that people can make comments about this feature request.

**Comment by captaindavepdx** [comment] 2019-05-07 20:30
Cool. I'll send you the puppeteer file once I get it working. 

Hopefully, it can be useful to SingleFile's community! =]

**Comment by captaindavepdx** [comment] 2019-06-11 02:13
Hi @gildas-lormeau, saw your new demo video, instructions, and examples. The updates you've made look great!

Since my last comment, I've built the foundation for my internal MacOS app. Now, I'm ready to customize a version of single-file to include website login.

General direction would be really helpful. And I'm happy to share my code with your community afterwards, if that's helpful. Is there a way we can chat privately?

**Comment by captaindavepdx** [comment] 2019-06-11 21:37
Hi @gildas-lormeau. Noticed the new demo gif, installation instructions, and cli examples. The updates look great!

**Update:**
Since my last comment, I've built the foundation for my macos app. Now, I'm ready to build a custom version of SingleFile for website login - as suggested.

**Problem:** 
I don't know where to begin in the SingleFile js files. 

**Request:**
General direction would be really helpful, and save a lot of time. And I'm happy to share finished script with the community! Would that be ok?

**Comment by gildas-lormeau** [comment] 2019-06-12 20:45
@captaindavepdx I would recommend you to fork the project and modify https://github.com/gildas-lormeau/SingleFile/blob/master/cli/back-ends/puppeteer.js to familiarize yourself with puppeteer.

**Comment by captaindavepdx** [comment] 2019-06-12 21:26
Sweet, thanks @gildas-lormeau! i didn't know that's what forking was. That's so cool! 

Would it be ok to ask you for suggestions if I get stuck?

**Comment by gildas-lormeau** [comment] 2019-06-12 22:20
> Would it be ok to ask you for suggestions if I get stuck?

It's ok if it's related to SingleFile ;)

**Comment by BiatuAutMiahn** [comment] 2019-06-12 22:21
I used puppeteer with python to automate logging into, and scraping billing information for my bills awhile ago. Basically I had an array, and with each, a list of commands to execute, ie; Nav to URL, wait for element id or class for login fields, submit, etc. For each site I had to manually grab the IDs/Classes for the username/password/submit. I'd consider using a database with this information, and internally...scrape the site every few hours or so to see if those element handles have been invalidated.

**Comment by BiatuAutMiahn** [comment] 2019-06-12 22:23
@gildas-lormeau Do you have a discord by chance?

**Comment by captaindavepdx** [comment] 2019-06-13 04:08
Cool, thanks @gildas-lormeau! And thanks @BiatuAutMiahn, I'll keep that in mind.

**Comment by gildas-lormeau** [comment] 2019-06-13 15:14
@BiatuAutMiahn Nope, I don't have any discord. From my point of view, implementing this feature is not really hard. It's just it does not fit my roadmap. The hardest thing to do is to propose a clean "plugin API" able to adapt to any website requiring a login/password. It's not necessarily easy from my point of view because for example, some websites (e.g. Google websites) will make you type your login and your password into 2 separate pages.

**Comment by captaindavepdx** [comment] 2019-06-21 16:10
Hi @gildas-lormeau, I've been building a custom solution based on SingleFile, as suggested. I've gotten the login, auto scroll, and html download features work, but some websites save the layout incorrectly. 

However, SingleFile is able to download the layout correctly for the same site.

Could you please help provide direction for how you were able to solve this?

### **Method: Without Removing Scripts**
<img width="1280" alt="Screen Shot 2019-06-21 at 8 51 36 AM" src="https://user-images.githubusercontent.com/30560737/59935507-cfe13880-9402-11e9-8e66-054013908b4f.png">

### **Method: After Removing Scripts:** ###
<img width="1280" alt="Screen Shot 2019-06-21 at 9 01 44 AM" src="https://user-images.githubusercontent.com/30560737/59935705-3e25fb00-9403-11e9-9786-652c6966ed9a.png">

### **Method: SingleFile:** ###
<img width="1280" alt="Screen Shot 2019-06-21 at 9 09 17 AM" src="https://user-images.githubusercontent.com/30560737/59936217-50ecff80-9404-11e9-9f94-351f9aba0de1.png">

**Comment by gildas-lormeau** [comment] 2019-08-23 21:50
I'm closing this issue because I don't think providing an API for this is really feasible and/or the right approach. I think the best solution is to write custom puppeteer/selenium/etc. scripts. Feel free to re-open it if necessary.

**Closed by gildas-lormeau** 2019-08-23 21:50 UTC
Labels: CLI, feature request
