### ISSUE TITLE
Not saving correctly

### ISSUE THREAD

**Issue by sj365** [gildas-lormeau/SingleFile#332] opened 2020-01-04 14:25 UTC
1. Singlefile is taking extra long time to save this and other pages with message - A script in the extension Singlefile is causing Firefox to slow down.  Also saved images in SingleFile saved file are coming out very blurry.

https://www.washingtonpost.com/technology/2019/12/24/colleges-are-turning-students-phones-into-surveillance-machines-tracking-locations-hundreds-thousands/

[sf example Colleges are turning students’ phones into surveillance machines - The Washington Post (2020-01-04 8_22_01 AM).zip](https://github.com/gildas-lormeau/SingleFile/files/4021988/sf.example.Colleges.are.turning.students.phones.into.surveillance.machines.-.The.Washington.Post.2020-01-04.8_22_01.AM.zip)

rename zip to html

2. SingleFile is not capturing two images in this page under heading - How we did it

https://graphics.reuters.com/ENVIRONMENT-PLASTIC/0100B4TF2MQ/index.html?utm_source=twitter&utm_medium=Social

same page saved with savepage web will show both images in chrome and firefox

**Environment**
Win10 Pro,  - Browser: [e.g. Chrome 79, Firefox 71]

**Comment by gildas-lormeau** [comment] 2020-01-06 23:09
1. I cannot reproduce the issue with the first URL. Here is a GIF of the capture in real-time (wait for the GIF being fully loaded) on my machine (core i7 8550U). What is your CPU? Were you saving multiple tabs in parallel?

![capture](https://user-images.githubusercontent.com/396787/71855383-2bde8680-30e1-11ea-9cca-e746b3e79c31.gif)

2. These are videos. To save them, disable "Other resources > remove video sources".

**Comment by gildas-lormeau** [comment] 2020-01-16 22:38
I'm closing this issue because I cannot reproduce it. Feel free to reopen it if necessary.

**Closed by gildas-lormeau** 2020-01-16 22:38 UTC
