### ISSUE TITLE
How to save the effects of other extensions e.g. RES, Tampermonkey, Stylus, etc. with the desired webpage?

### ISSUE THREAD

**Issue by Droyk** [gildas-lormeau/SingleFile#1033] opened 2022-09-01 21:59 UTC
Hey there, 
I use RES and tampermonkey on Reddit 
I tried to save the webpage but the extension couldn't save the effects **COMPLETELY** created via both of these extensions 
is there any way to do this?
if there isn't would it be possible to implement it?  

**Snapshot of webpage with both of these extensions enabled**

![Web capture_2-9-2022_395_www reddit com1](https://user-images.githubusercontent.com/15848350/188020118-397c0849-b793-453e-84d5-087e1ceff4f5.jpeg)

**Snapshot after saving the webpage via your extension**

![Web capture_2-9-2022_31045_](https://user-images.githubusercontent.com/15848350/188020132-24d94853-94db-4ead-8165-f74b38a9e930.jpeg)

**Comment by gildas-lormeau** [comment] 2022-09-28 20:55
Sorry for the late answer, what do you mean by "effects"?

**Comment by Droyk** [comment] 2022-09-30 21:53
effects mean the css/ javascript styles the extensions apply or a particular user script extension applies.

for e.g. the first image represents all the user styles correctly applied the 2nd image shows some styles are missing!

**Comment by gildas-lormeau** [comment] 2022-10-01 19:52
If you're using Firefox, this is normal. Extensions can inject a "private" stylesheet which is not visible to other extensions and the page where it is injected.

**Comment by gildas-lormeau** [comment] 2022-10-23 01:19
@Droyk Do you confirm you're using Firefox or a browser based on Firefox ?

**Comment by gildas-lormeau** [comment] 2023-07-23 21:18
Stylesheets injected by third-party extensions should be supported in Chrome. Please provide a way to reproduce the issue so that I can debug it.

**Comment by gildas-lormeau** [comment] 2023-08-03 20:52
I'm closing the issue because it should already work. Feel free to reopen it if you can provide a way to reproduce the bug.

**Closed by gildas-lormeau** 2023-08-03 20:52 UTC

**Comment by Droyk** [comment] 2023-08-04 02:32
Hi, Forgive me for not replying was busy doing something else! 

So what do you mean by 
>Stylesheets injected by third-party extensions should be supported in Chrome. Please provide a way to reproduce the issue so that I can debug it.

Are you talking about extensions working on Stylesheet extension working on local files?
If so, that's not what exactly I want! I want your extension to capture those stylesheets of other extension so that I can read them anywhere comfortably. without thinking that I need some kind of theme injection to make it possible, I feel very sad when I open those pages coz they don't look the way I want! 
It's hard to install the userscript on every other computer (I work w/lots of PC's & I'm in a situation where I don't know what PC I'm to get to do the work.) so it would be fantastic if you can add a way to capture the style sheets of the current page added by d/f user extensions!

**Comment by Droyk** [comment] 2023-08-05 17:12
@gildas-lormeau !

**Comment by gildas-lormeau** [comment] 2023-08-05 17:38
Tell me exactly what your problem is and I'll tell you if I can fix it or not. 

Here is below the template you can use to give me the information I need.

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment**
 - OS: [e.g. Win10 Pro, Ubuntu 18.04.1, Android 7.1.2]
 - Browser: [e.g. Chrome, Firefox]
 - Version: [e.g. 64]

**Additional context**
Add any other context about the problem here.
