### ISSUE TITLE
Minor bug where space for videos appears to be allocated twice

### ISSUE THREAD

**Issue by russellyoung** [gildas-lormeau/SingleFile#793] opened 2021-10-06 17:18 UTC
**Describe the bug**
This is a minor bug, the web page does render properly, but with extra blank space at several spaces. I just submit it FYI.
A page that shows the issue is https://mp.weixin.qq.com/s/kGT_dmZo8Pn3uNXCWv_eoQ. Before each video there is a vertical white space the size of the video
**To Reproduce**
1: go to https://mp.weixin.qq.com/s/kGT_dmZo8Pn3uNXCWv_eoQ
2: After it renders use singlefile to save a copy
3: display the copy
4: scroll down past the first image to the second, which is a video. There is a vertical whitespace the height of the video in the saved version that is not there in the original

**Expected behavior**
there should not be the extra whitespace

**Screenshots**
Original page screenshot:
![orig-image](https://user-images.githubusercontent.com/6629632/136251332-82cf5c1f-a6c8-4949-90ea-37831a0073cd.png)
Copy page screenshot:
![copy-image](https://user-images.githubusercontent.com/6629632/136251318-498e1d7f-b33e-4bcd-af51-495886fbf69d.png)
Original page DOM:
<img width="645" alt="orig-dom" src="https://user-images.githubusercontent.com/6629632/136251327-8a36536d-e420-4f13-a410-3feaae68468b.png">
Copy page DOM:
<img width="578" alt="copy-dom" src="https://user-images.githubusercontent.com/6629632/136251299-076a4b15-e2e0-4b86-9b00-39818518b8c9.png">

**Environment**
 - OS: MacOS 10.14.6 (18G9323)
 - Browser: Brave
 - Version: Version 1.29.79 Chromium: 93.0.4577.63 (Official Build) (x86_64)

**Additional context**
In the DOM screenshot you can see there is an extra element (div id="page-content") in the copy. The video image appears in that div, while the above (p) image, which is the video on the original, is the same size as the video but blank

**Comment by gildas-lormeau** [comment] 2022-05-09 23:14
I'm closing this issue as a duplicate of https://github.com/gildas-lormeau/SingleFile/issues/931. The latter issue explains more clearly the problem and why it cannot be (easily) fixed.

**Closed by gildas-lormeau** 2022-05-09 23:14 UTC
