### ISSUE TITLE
Error occurs with cli

### ISSUE THREAD

**Issue by Jerry-Chow** [gildas-lormeau/SingleFile#460] opened 2020-08-05 02:51 UTC
Hello ,

Any help with the error shows below 

>single-file.bat "https://spring.io/guides/gs/batch-processing/" springBatchTutorial.html
internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (D:\Test\SingleFile-master\cli\node_modules\extract-zip\index.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Test\SingleFile-master\cli\node_modules\puppeteer-core\lib\BrowserFetcher.js:26:20)

**Comment by gildas-lormeau** [comment] 2020-08-05 12:35
I cannot reproduce the issue. On my end the command `single-file.bat "https://spring.io/guides/gs/batch-processing/" springBatchTutorial.html` runs fine and generates the saved page as expected.

The error seems to be related to Puppeteer. Please make sure your dependencies are up to date by running `npm update`.

**Comment by gildas-lormeau** [comment] 2020-08-11 16:28
@Jerry-Chow any news?

**Comment by gildas-lormeau** [comment] 2020-08-13 00:35
I'm closing this issue since I cannot reproduce it. Feel free to comment it, or reopen it if necessary.

**Closed by gildas-lormeau** 2020-08-13 00:35 UTC
