### ISSUE TITLE
ive got problems with cli saving files by itself

### ISSUE THREAD

**Issue by warichnict** [gildas-lormeau/SingleFile#582] opened 2021-01-05 21:41 UTC
hi,

i  (using debian) would like to build a script that saves every parameter in a file into the current working dir ( . / $PWD) to a file with a reasonable auto generated name (like that one generated by the browser extension)
so i build a little bash script, just containing 

``
docker run singlefile "$@"
``

and called it just singlefile to begin with, my goal is to call it as in 

``
$ singlefile http://example.org
``
and get something called like Example - DateTime - example.org.html file in the current working dir...

````
/tmp $ singlefile --help | grep template
  --filename-template                     Template used to generate the output filename (see help page of the extension for more info)  [string] [default: "{page-title} ({date-iso} {time-locale}).html"]
/tmp $ singlefile http://wikipedia.de/ "{page-title} ({date-iso} {time-locale}).html"
URL: http://wikipedia.de/
Stack: Error: EACCES: permission denied, mkdir '/out'
    at Object.mkdirSync (fs.js:987:3)
    at capturePage (/usr/src/app/node_modules/single-file/cli/single-file-cli-api.js:257:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runNextTask (/usr/src/app/node_modules/single-file/cli/single-file-cli-api.js:167:20)
    at async Promise.all (index 0)
    at async capture (/usr/src/app/node_modules/single-file/cli/single-file-cli-api.js:118:2)
    at async run (/usr/src/app/node_modules/single-file/cli/single-file:53:2)

/tmp $ singlefile http://wikipedia.de/ wikipedia_startseite.html
URL: http://wikipedia.de/
Stack: Error: EACCES: permission denied, mkdir '/out'
    at Object.mkdirSync (fs.js:987:3)
    at capturePage (/usr/src/app/node_modules/single-file/cli/single-file-cli-api.js:257:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runNextTask (/usr/src/app/node_modules/single-file/cli/single-file-cli-api.js:167:20)
    at async Promise.all (index 0)
    at async capture (/usr/src/app/node_modules/single-file/cli/single-file-cli-api.js:118:2)
    at async run (/usr/src/app/node_modules/single-file/cli/single-file:53:2)

/tmp $ singlefile http://wikipedia.de/ > wikipedia_startseite.html
/tmp # worked but not how i like it...
```` 

Problem is that i cant get it to work to save anything, only way i can get it is redirecting standart output like > xyz.html, so what to do to have it right?

 thanks for any help in advance and keep up the good work!

**Comment by gildas-lormeau** [comment] 2021-01-09 17:04
I guess the issue is related to the fact that the output folder in the image is not in the user directory. I just updated the Dockerfile, can you tell me if it fixes the issue on your end?

**Comment by gildas-lormeau** [comment] 2021-01-19 22:14
@warichnict any news?

**Comment by gildas-lormeau** [comment] 2021-01-25 21:44
Closed as "no news"

**Closed by gildas-lormeau** 2021-01-25 21:44 UTC
