### ISSUE TITLE
SingleFile Unable to process DailyBeast and similar technology style pages

### ISSUE THREAD

**Issue by sj365** [gildas-lormeau/SingleFile#595] opened 2021-01-21 12:18 UTC
SingleFile v1.18.62
Chrome Version 88.0.4324.96 (Official Build) (64-bit)

Try to save page of DailyBeast web article, page will turn blank/white, Singlefile saves a blank page.  This issue exitsted in prior versions of Singlefile but was fixed.  Now has returned in current version.

Windows 10 Education
20H2
19042.746
Windows Feature Experience Pack 120.2212.551.0

Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.81 GHz
32.0 GB Ram
64-bit operating system, x64-based processor

**Incorrect SingleFile Save**
https://www.thedailybeast.com/samuel-fisher-conspiracy-addled-nyc-pickup-artist-arrested-in-capitol-riots?ref=home

[Samuel Fisher, Conspiracy-Addled NYC Pickup Artist, Arrested in Capitol Riots.zip](https://github.com/gildas-lormeau/SingleFile/files/5849150/Samuel.Fisher.Conspiracy-Addled.NYC.Pickup.Artist.Arrested.in.Capitol.Riots.zip)

**Correct SingleFile Save**
https://www.businessinsider.com/video-fox-news-reeducation-camps-conspiracy-theory-harris-faulkner-2021-1

[Video_ Fox News pushes conspiracy theory about 'reeducation camps' - Business Insider (2).zip](https://github.com/gildas-lormeau/SingleFile/files/5849176/Video_.Fox.News.pushes.conspiracy.theory.about.reeducation.camps.-.Business.Insider.2.zip)

**Comment by gildas-lormeau** [comment] 2021-01-21 21:57
I cannot reproduce this issue on Chrome 88.0.4324.104. Did you change any setting in SingleFile?

**Comment by sj365** [comment] 2021-01-22 20:46
No changes, and I use the same settings to capture all other sites/pages.

 singlefile Video_2021-01-22_154141.wmv
<https://drive.google.com/file/d/1DpAmoIfAwYMG_W7b3irOfhGSBCIewBTU/view?usp=drive_web>

**Comment by sj365** [comment] 2021-01-25 08:45
Another site same issue

https://abcnews.go.com/Politics/wireStory/capitol-attack-reflects-us-extremist-evolution-decades-75445234

The page does save correctly using webscrapbook

**Comment by gildas-lormeau** [comment] 2021-01-31 23:13
@sj365 any news?

**Comment by gildas-lormeau** [comment] 2021-02-12 00:49
I'm closing the issue because I was not able to reproduce it. Feel free to reopen it if necessary.

**Closed by gildas-lormeau** 2021-02-12 00:49 UTC
