### ISSUE TITLE
Problem saving www.aftonbladet.se

### ISSUE THREAD

**Issue by labyrinth-to-solve** [gildas-lormeau/SingleFile#370] opened 2020-03-03 12:33 UTC
To reproduce reopen the saved page.
SingleFile 1.17.4, Firefox 73.0 (64 bit), Ubuntu 18.04.4

**Comment by gildas-lormeau** [comment] 2020-03-03 16:59
I did a test and the saved page is fine on my end. Maybe you should make sure the extension is up to date. I fixed some bugs and regressions since the version 1.17.4.

Here is the saved page in a zip file: [Nyheter från Sveriges största nyhetssajt _ Aftonbladet (2020-03-03 5_57_06 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/4282551/Nyheter.fran.Sveriges.storsta.nyhetssajt._.Aftonbladet.2020-03-03.5_57_06.PM.zip)

**Comment by gildas-lormeau** [comment] 2020-03-06 14:36
@labyrinth-to-solve any news?

**Comment by labyrinth-to-solve** [comment] 2020-03-06 19:51
Sorry, I am really busy these days. I have to create a clean Forefox profile and test the SingleFile while adding my addons one after one. I hope this weekend ...

**Comment by gildas-lormeau** [comment] 2020-03-06 23:14
No problem :) Thank you for the update

**Comment by labyrinth-to-solve** [comment] 2020-03-11 18:21
Sorry I am late. The problem goes away when I have only following add-ons:
NoScript
Sidebery
Singlefile
uBlock Origin
I have 13 more add-ons to test.
Another problem: sometimes downloading hangs. Then I have to find the tab which is responsible for that. It has a yellow band on the top with text "A web page is slowing your browser. What would you like to do?   Stop it    Wait" When I choose "Stop it" the tab is saved as usual and the downloading goes on. Shall I start a new issue for it?

**Comment by gildas-lormeau** [comment] 2020-03-11 18:59
Thank you for the update. Regarding the downloading issue, do you know a URL that causes this issue each time you want to save it? What step is displayed at the bottom left of the page?

**Comment by labyrinth-to-solve** [comment] 2020-03-11 19:18
Deferred images

**Comment by gildas-lormeau** [comment] 2020-03-11 19:35
Thank you. By the way, I'm realizing I don't know what the current issue is... What happens when you save www.aftonbladet.se?

Regarding the downloading issue, you could also do the test I propose here to gain time: https://github.com/gildas-lormeau/SingleFile/issues/376#issuecomment-596217285. You would just have to enable all your addons and see which custom builds work.

**Comment by labyrinth-to-solve** [comment] 2020-03-11 19:41
As I wrote: it works when I use a clean profile with the named four add-ons. I have 13 more add-ons to test to find the culprit.

**Comment by labyrinth-to-solve** [comment] 2020-03-11 20:23
Five more add-ons tested without problems with saving of aftonbladet.se:
Disconnect
Dormancy
Json Beautifier & Editor
Bukubrow
Tab Session Manager
Six more add-ons to test ...

**Comment by gildas-lormeau** [comment] 2020-03-11 20:30
Hang in there :)

**Comment by gildas-lormeau** [comment] 2020-03-14 01:52
I think I might have been able to reproduce your issue with https://www.the-tls.co.uk. I removed from SingleFile the related code because it's obsolete actually. This fix will be available in the next version I'll publish. Meanwhile you can install the extension manually if you want to test the fix.

**Comment by labyrinth-to-solve** [comment] 2020-03-16 21:08
Sorry I am late again. Now I have tested the rest of active add-ons:
Bypass Paywalls Clean
CleanURLs
Cookie Remover
Json Lite
Session Sync
Everything works OK on that clean profile I created for these tests, problem in the old profile.
I can see two possibility:
1. The problem can depend on some parameters in add-ons on the old profile. On the clean profile I just installed add-ons without any tweaking. 
2. The old profile works with many tabs, sometimes more than 2000. The clean profile used for testing has only a few tabs.
Any idea?
I tested https://www.the-tls.co.uk/ as you proposed. It works without problems in both profiles :(
In the future I will use the new profile. Possibly it brakes down again when I change add-ons parameters. I will inform you then.

**Comment by gildas-lormeau** [comment] 2020-03-16 22:54
Are you sure you did your final tests with the previous version of SingleFile? The new one was published today and I suspect it might help to fix your issue.

**Comment by gildas-lormeau** [comment] 2020-03-25 18:13
@labyrinth-to-solve Do you think I can close this issue?

**Comment by gildas-lormeau** [comment] 2020-04-09 22:54
I'm closing it because it is probably due to a corrupt profile, as you explained. Feel free to reopen it if necessary.

**Closed by gildas-lormeau** 2020-04-09 22:54 UTC

**Comment by labyrinth-to-solve** [comment] 2020-08-05 15:22
Sorry I stopped answering your questions. I was given other priorities due to the pandemic and completely forgot about the case. In any case, the problem is solved.

**Comment by gildas-lormeau** [comment] 2020-08-05 16:44
No problem ;)
