### ISSUE TITLE
Save to Evernote 

### ISSUE THREAD

**Issue by ruanima** [gildas-lormeau/SingleFile#571] opened 2020-12-20 08:45 UTC
it is possible or not to save to evertnote? 
evernote web clipper can not access local file.

thanks for your work!!!

**Comment by gildas-lormeau** [comment] 2020-12-20 15:19
Thank you for the suggestion. I did not do the test but if you're using Chrome, maybe enabling the setting "Allow access to file URLs" in the extension page of Evernote here chrome://extensions/?id=pioclpoplcdbaefihamjohnefbikjilc could fix this issue.

**Comment by ruanima** [comment] 2020-12-21 15:07
"Allow access to file URLs"  not work edge browser.

**Comment by gildas-lormeau** [comment] 2020-12-21 15:20
I disagree. Generally speaking, this option works in Edge otherwise the infobar of SingleFile wouldn't be displayed when viewing a saved page.

**Comment by ruanima** [comment] 2020-12-21 16:06
![image](https://user-images.githubusercontent.com/14031394/102795465-cfef3980-43e7-11eb-9890-b6f8ffdbfd95.png)
![image](https://user-images.githubusercontent.com/14031394/102795500-dbdafb80-43e7-11eb-9783-8ad7e111111a.png)

Maybe I didn’t describe the problem correctly. 

Sometimes Evernote cannot save web pages containing dynamic content correctly. 
Finally I found SingleFile, which perfectly solves this problem by saving as a single html file.
When I opened the saved html file and try to save it to evernote, I ran into the problem described at the beginning.
Can it directly save web pages to evernote, just like saving to Google cloud？

**Comment by gildas-lormeau** [comment] 2020-12-21 16:33
Thank you for the info. I don't understand why the Evernote extension cannot process files stored on the filesystem with Edge (maybe it's the same in all browsers). This is not technically justified (i.e. it's a bug).

I understand your feature request. The problem is that Evernote supports only a small subset of HTML, see https://dev.evernote.com/doc/articles/enml.php. However, SingleFile's job is to do exactly the opposite, i.e. to produce a page as faithful as possible to the one displayed. This is also what justifies 90% of the extension's code. To be honest, it bothers me to offer a feature that would hardly rely on what SingleFile is supposed to do. Also, it makes me feel like I'm doing the work for Evernote's employees. From my point of view, what you describe is a(nother) bug in the Evernote's extension.

To fix this issue, you could run an HTTP server and open saved pages in HTTP (instead of file:/// URI) in order to circumvent the limitation of Evernote's extension. However, I totally understand that you find this solution tedious.

**Comment by ruanima** [comment] 2020-12-22 06:34
@gildas-lormeau  
I understand, it is indeed a problem of Evernote.
The most direct method is to copy the saved webpage to Evernote.

**Comment by gildas-lormeau** [comment] 2020-12-22 14:07
Indeed, note that there is an option for that in SingleFile. However since SingleFile will copy the HTML of the processed page, I doubt this will work with Evernote.

**Comment by gildas-lormeau** [comment] 2021-01-09 17:06
I'm closing the issue. I hope Evernote will offer a way to upload complete HTML pages someday!

**Closed by gildas-lormeau** 2021-01-09 17:06 UTC
