### ISSUE TITLE
expect to see the downloaded webpage's file name is ORDERed per the tab's order itself

### ISSUE THREAD

**Issue by roger125** [gildas-lormeau/SingleFile#135] opened 2019-01-17 12:11 UTC
Hi Team,
=============================Scenario=============================
open the beneath urls one by one ORDERed in each tab:
http://google.com/?page=1
http://google.com/?page=2
http://google.com/?page=3
http://google.com/?page=4
http://google.com/?page=5
http://google.com/?page=6
click the extension icon->Save tabs->Save all tabs, 
so each url/page can be downloaded into the beneath files:
google.html
google(1).html
google(2).html
google(3).html
google(4).html
google(5).html

=============================current version(1.9.34) issue=============================
the downloaded file name can't represent the corresponding url/page, or as i can see, randomly, i don't see if there's any patten here.
e.g.:
google.html represents http://google.com/?page=3
google(5).html represents http://google.com/?page=2
google(3).html represents http://google.com/?page=1
...
...
=============================while what expect here=============================
google.html represents http://google.com/?page=1
google(1).html represents http://google.com/?page=2
google(2).html represents http://google.com/?page=3
google(3).html represents http://google.com/?page=4
google(4).html represents http://google.com/?page=5

=============================the purpose here is=============================
we can know which url it represents once seeing the downloaded file name(because each url's content is different as mostly of the time);

=============================so working solution here=============================
since we can organise/order the url from left to right, then, what i expect from this extension is: just download from left to right(or right to left, just don't be randomly).

can it be done?

thanks for the consideration.

**Comment by gildas-lormeau** [comment] 2019-01-18 21:58
Hi @roger125, I am the team :)

Unfortunately, it cannot be done easily. To do this, I would have to introduce a big sacrifice in performances by saving and downloading pages one by one whereas on most computers (i.e. multi-core CPUs), it's more efficient to do this task in parallel. The problem is that when it's done in parallel, I cannot guarantee any order at all. 
There is maybe another solution to your issue though. I would have to offer a way to retrieve one particular query parameter from the URL and use its value in the filename with a variable which would be named for example "{url-query-parameter-page}" to retrieve the value of the query parameter named "page". Unfortunately, this would have to be configured site by site because the query parameter used for pagination varies very often. For example, on Google the URL query parameter concerned is "start=xxx" (so the variable would be "{url-query-parameter-start}") but on Bing it's "first=xxx" (the variable would be "{url-query-parameter-first}").

**Comment by roger125** [comment] 2019-01-19 03:07
Hi @gildas-lormeau , thanks for the detailed explanation reply.

yup, i understand the "in parallel" method is purposed to be more quick to finish the task.

and i'm quite pleased to see you can carry out another solution which is out of what i thought.
and for your reference, "Internet Download Manager" has this kind of solution, in their->Tasks->Add batch download, maybe it can share you some insights also, while it's quite ok to config site by site, since it's not a big task to do, and no many sites to finish this task(at the end of the day, it's just that certain sites that i personally want to download).

thanks for making it possible, it makes this extension more useful practically for the "last mile" scenario.

**Comment by gregsskyles** [comment] 2019-01-19 05:42
When you dispatch the threads to download each tab/page, can't you tell each thread the name to use for the file? Granted page three might finish first, but that thread should "know" to save the file under the name with "(3)" if you've told it ahead of time.

**Comment by gildas-lormeau** [comment] 2019-01-20 21:57
In the case of web-extensions, the " (1)"," (2)", etc. appended to the filename is handled by the browser or the OS (I don't really know). On my end, I delegate this naming issue to the [`download.download()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download) function. More precisely, it's the `conflictAction` parameter which tells what to do when a conflict happens.  Users of SingleFile can change this parameter through the option "file name conflict resolution".

I need to do tests because I don't know, today, if calling download.download() multiple times, in a short period of time, guarantees the files will be saved in the same order since it's an asynchronous operation. I don't really want to re-invent the wheel, i.e. I would like to keep delegating naming conflicts issues to the `download.download()` function

**Comment by gregsskyles** [comment] 2019-01-21 03:04
Aha, thanks for that explanation; makes sense. I was assuming things about your implementation and maybe should have stuck my nose into the code first.

You might get lucky and the Mozilla implementation (or the OS downstream) will implicitly serialize your requests, but since it's an async call, a guarantee might be hard to come by. I've seen the reverse happen; a quick series of async calls ends up being executed in exactly the opposite order, because the underlying implementation uses a stack or FILO queue.

**Comment by gildas-lormeau** [comment] 2019-01-29 21:37
@roger125 With the latest version of SingleFile, you can now use the template variable ` {url-search-start}` to fix this issue on Google. You can also create a rule to automatically assign a profile using this variable in the filename template to the domain "google.com" for example.

**Comment by gildas-lormeau** [comment] 2019-01-30 10:39
As I said, fixing this bug is not trivial. I did what I could to help you. I am sorry if it does not but coding a working solution for this issue is simply overkill for me.

**Comment by gildas-lormeau** [comment] 2019-02-01 00:17
@roger125 I re-read your message and I realize there is indeed a misunderstanding. I'm sorry for that. "start" is the name of the query parameter used on Google: it does use "page", e.g. https://www.google.com/search?q=test&start=10. That's why I'm talking about `{url-search-start}`. However you can use `{url-search-page}` in your examples (https://www.google.com/?page=1). The syntax is `{url-search-` + name of the query parameter + `}`. You can even use `{url-search-page} {url-search-start} {url-search-first}` since the value will be "" when the query parameter does not exist.

**Comment by gildas-lormeau** [comment] 2019-02-01 20:23
@roger125 Hi, You're welcome! I'm glad you're satisfied with the workaround I proposed. I won't close the issue because it's not fixed actually. I mean that your saved pages are now correctly ordered but it does not depend on the order of the tabs at all ;)

**Comment by roger125** [comment] 2019-02-02 02:07
hi, @gildas-lormeau , ok, i understand your concern as the logic you described it.

and i think current workaround is 100% perfect, really! i said it with reason: it makes the solution interchangeable, no matter the 1st page i keep it in the leftmost or rightmost, it can be the (1) style as the file name, and this is beyond my expectation when i open this issue actually! it means the extension can give me the correct file name even when i open the tabs randomly. isn't that better? :-)

on the other hand, the "secondary" solution originally(depend on the order of the tabs) concerns though it can be a good idea to consider if you got enough time and energy, then add it as an option also.

all in all, you make it super powerful now!

**Comment by gildas-lormeau** [comment] 2019-02-02 15:45
I agree with you.

**Closed** 2019-03-14 20:33 UTC
Labels: feature request

**Comment by gildas-lormeau** [comment] 2019-03-14 20:35
I added a new variable named `tab-index` which returns the index of the tab in the window. Using this variable in the file name template fixes this issue. It will be available in the version 1.9.87.

**Comment by roger125** [comment] 2019-03-16 13:30
thanks for making it farther as initially, really.
