### ISSUE TITLE
Freeze on a Japanese website

### ISSUE THREAD

**Issue by notuntoward** [gildas-lormeau/SingleFile#1480] opened 2024-06-14 04:06 UTC
This site is one of the very rare cases I've found where SingleFile freezes, and eventually prints an error message (screenshot).  It's a dual english/japanese site, if that's relevant.  I'm just clicking on the SingleFile icon.

**Screenshots**
![image](https://github.com/gildas-lormeau/SingleFile/assets/3851891/f7d44d3a-6493-4176-8d71-9cdb3cdfe320)

**Environment**
 - Windows 11
 - Brave Browser
 - Version: 1.22.49

**Comment by gildas-lormeau** [comment] 2024-06-16 19:31
I cannot reproduce the issue with Brave on Windows 11. Did you try this procedure? https://github.com/gildas-lormeau/SingleFile?tab=readme-ov-file#known-issues

**Comment by gildas-lormeau** [comment] 2024-07-10 22:16
I'm closing the issue because I didn't get any answer. Feel free to comment though.

**Closed by gildas-lormeau** 2024-07-10 22:16 UTC
