### ISSUE TITLE
how to download only svg files?

### ISSUE THREAD

**Issue by mr1pacman** [gildas-lormeau/SingleFile#375] opened 2020-03-05 14:13 UTC
If the web page is large, then there is a crash

**Comment by gildas-lormeau** [comment] 2020-03-05 14:17
Do you have an example of URL allowing me to reproduce the issue?

**Comment by mr1pacman** [comment] 2020-03-05 15:44
This is a closed electronic library.

The fact is that if the book contains about 300 pages, then the
process is successful, but if there is more, then the RAM is loaded
and crash occurs

[image: изображение.png]
[image: изображение.png]


чт, 5 мар. 2020 г. в 17:17, Gildas <notifications@github.com>:

**Comment by mr1pacman** [comment] 2020-03-05 15:46
If you understand Russian, I can send a username and password with a
link to a book 😀


чт, 5 мар. 2020 г. в 18:44, Linar Galiev <linar.galiev.97@gmail.com>:

**Comment by gildas-lormeau** [comment] 2020-03-06 14:34
Unfortunately, I do not understand Russian. In fact, I'm also unsure I can fix that issue to be honnest, because i don't know how to process a page if the whole page can't be stored into the RAM.

**Comment by mr1pacman** [comment] 2020-03-06 17:53
and if a new option, downloading only the image (png/svg)?


пт, 6 мар. 2020 г., 17:34 Gildas <notifications@github.com>:

**Comment by gildas-lormeau** [comment] 2020-03-07 00:11
Can't the image be saved by using "Save image as..." in the context menu?

**Comment by mr1pacman** [comment] 2020-03-07 13:07
no, it downloads in png format, but there is an empty picture.
Moreover, a page can have up to 900 images (svg format). If you do
everything manually, it takes a very long time


сб, 7 мар. 2020 г. в 03:11, Gildas <notifications@github.com>:

**Comment by gildas-lormeau** [comment] 2020-03-07 13:28
Out of curiosity, did you do a test with SingleFileZ?

**Comment by mr1pacman** [comment] 2020-03-07 14:52
both with SingleFileZ and SingleFile (but it is very difficult to work
with it, the files are large (more than 200 mb) and opening them is
accompanied by system load)


сб, 7 мар. 2020 г. в 16:28, Gildas <notifications@github.com>:

**Comment by mr1pacman** [comment] 2020-03-07 14:53
besides if I use SingleFile - I can not export svg files


сб, 7 мар. 2020 г. в 14:52, Linar Galiev <linar.galiev.97@gmail.com>:

**Comment by gildas-lormeau** [comment] 2020-03-09 16:13
Could you please tell me what step is displayed at the bottom left of the page when the crash happens?

**Comment by gildas-lormeau** [comment] 2020-04-19 12:47
I'm closing this issue because I won't add an option or a feature to download svg files only.

**Closed by gildas-lormeau** 2020-04-19 12:47 UTC
