### ISSUE TITLE
some elements whose type is <g> in HTML can not be download completely. 

### ISSUE THREAD

**Issue by wangxiaolei21** [gildas-lormeau/SingleFile#857] opened 2022-01-09 10:20 UTC
it can not download some elements, whose type is <g> in a HTML in some special urls
there is a page:
https://mp.weixin.qq.com/s/qQryZZXdD6G441QSww2s_g
a lot of expression can not be downloaded completely.
 #[![7kEncd.md.png](https://s4.ax1x.com/2022/01/09/7kEncd.md.png)](htt
![edi](https://user-images.githubusercontent.com/77225404/148678169-b9d17e72-6527-49bf-9ffe-feaa7e93e686.png)
ps://imgtu.com/i/7kEncd)
I need your help...

**Comment by gildas-lormeau** [comment] 2022-01-10 14:30
I did a test with Firefox and it worked fine for me with the default settings of SingleFile. I attached the saved page in the zip file below
[RANEDDI：用于药物-药物相互作用预测的关系感知网络嵌入 (1_10_2022 3_28_55 PM).zip](https://github.com/gildas-lormeau/SingleFile/files/7839509/RANEDDI.-.1_10_2022.3_28_55.PM.zip)
.

**Comment by gildas-lormeau** [comment] 2022-02-17 13:36
I'm closing this issue because I cannot reproduce it. Feel free to comment it or reopen it though.

**Closed by gildas-lormeau** 2022-02-17 13:36 UTC
