### ISSUE TITLE
Fails to save MathJax items on Edx.org

### ISSUE THREAD

**Issue by daspri** [gildas-lormeau/SingleFile#764] opened 2021-08-31 03:34 UTC
**Describe the bug**

The original page is on the left, the SingleFile saved html is on the right. 
The MathJax items are missing.

![image](https://user-images.githubusercontent.com/4674343/131436750-599530e6-527e-46e7-ae43-ab351d94e9dc.png)

**To Reproduce**

Noticed this on Edx.org
Edx.org needs free signup
Try sample course:
https://learning.edx.org/course/course-v1:MITx+5.01x+3T2020/home
Module 0 - General Science Material - Post Test (item 9/9)
Enter answer, click "Show answer" and save the page with SingleFile

**Expected behavior**
Save the math formulas so they are visible.

**Environment**
Firefox 91.0.2 Windows
SingleFile 1.18.100

**Comment by gildas-lormeau** [comment] 2021-08-31 22:22
I'll create an account to see what could be wrong. However, this issue is maybe specific to this website.

For example, I can save this page https://www.cs.odu.edu/~zeil/cs390/latest/Public/texmath/demo.html without any particular issue. Do you confirm this example works fine on your side?

**Comment by daspri** [comment] 2021-08-31 22:34
> I'll create an account to see what could be wrong. However, this issue is maybe specific to this website.
> 
> For example, I can save this page https://www.cs.odu.edu/~zeil/cs390/latest/Public/texmath/demo.html without any particular issue. Do you confirm this example works fine on your side?

That example works fine.  
The edx.org links do not work.

**Comment by gildas-lormeau** [comment] 2021-08-31 22:50
This issue seems related to the SVG renderer. To circumvent it, you can right click on a formula and select "Math settings > Math renderer > Common HTML".

**Comment by daspri** [comment] 2021-08-31 23:06
Yes, that is a temp workaround, thank you.
But the demo link you posted above was also rendered in SVG and was saved correctly.

**Comment by gildas-lormeau** [comment] 2021-08-31 23:25
Yes, because this issue is specific to edx.org.

**Comment by gildas-lormeau** [comment] 2021-08-31 23:32
This issue will be fixed in the next version **but** only on learning.edx.org. It means you will have to save https://courses.edx.org/xblock/block-v1:MITx+5.01x+3T2020+type@vertical+block@3ea5a23494fd4f14a0bebd1643de1d11?show_title=0&show_bookmark_button=0&recheck_access=1&view=student_view instead of https://learning.edx.org/course/course-v1:MITx+5.01x+3T2020/block-v1:MITx+5.01x+3T2020+type@sequential+block@03dd388ee4454dcc978482c90b76d3bb/block-v1:MITx+5.01x+3T2020+type@vertical+block@3ea5a23494fd4f14a0bebd1643de1d11 if you really want to use the SVG renderer.

**Comment by gildas-lormeau** [comment] 2021-09-01 00:11
- https://learning.edx.org/course/course-v1:MITx+5.01x+3T2020/block-v1:MITx+5.01x+3T2020+type@sequential+block@03dd388ee4454dcc978482c90b76d3bb/block-v1:MITx+5.01x+3T2020+type@vertical+block@3ea5a23494fd4f14a0bebd1643de1d11 uses `<use>` tags to import SVG sprites displayed in formulas, i.e. `<g ...><use xlink:href="..."></use>` 
- https://courses.edx.org/xblock/block-v1:MITx+5.01x+3T2020+type@vertical+block@3ea5a23494fd4f14a0bebd1643de1d11?show_title=0&show_bookmark_button=0&recheck_access=1&view=student_view#MJMAIN-31 is an example of URL found as `xlink:href` in these `<use>` tag
- This URL returns an HTML page (instead of a SVG image) which contains the tag `<svg><defs id="MathJax_SVG_glyphs"><path stroke-width="1" id="MJMAIN-31"...>`
- The problem is that the `<svg>` tag is created dynamically with JavaScript, and SingleFile cannot execute JavaScript in SVG images (or HTML pages used as SVG images)

Unfortunately, I don't think this bug can be fixed. This is a really twisted case though.

**Comment by daspri** [comment] 2021-09-01 00:15
I don't think someone would load that iframe by itself normally.
Is there a bug on edx? Is there no way to get it to work by default?

**Comment by gildas-lormeau** [comment] 2021-09-01 00:35
My bad, I did not see the iframe. The bug should be fixable.

**Closed** 2021-09-01 00:51 UTC
Labels: technical limitation

**Comment by gildas-lormeau** [comment] 2021-09-01 00:58
The issue will be fixed in the version 1.19.2.

**Comment by daspri** [comment] 2021-09-03 16:59
1.19.4 just showed up on addons.mozilla, and the boxes are no longer blank, but some of the characters in the SVG overwrite others.  
See the "hr" in the first one, the parens and numbers in the second.
Any idea why that happens?  Screenshots:  Left is original, right is SingleFile


![e1](https://user-images.githubusercontent.com/4674343/132041596-88e37f3d-702a-4c3b-8999-576cd5891409.jpg)


![e2](https://user-images.githubusercontent.com/4674343/132041641-856c23ab-a31e-4452-ae30-4d44ffebfa10.jpg)

**Comment by gildas-lormeau** [comment] 2021-09-03 21:15
Thank you, I was able to reproduce and fix the issue. The fix will be available in the version 1.19.5+.
