### ISSUE TITLE
green OK in Firefox, but no file is saved. ok, then error in Chrome

### ISSUE THREAD

**Issue by AdKiller** [gildas-lormeau/SingleFile#190] opened 2019-04-18 10:15 UTC
**Describe the bug**
(Firefox) When I click SingleFile, I get the progress bar and green ok but nothing is saved.
(Chrome) When I click SingleFile, I get the progress bar and green ok, followed by error.

**To Reproduce**
1. Go to ' (Private site)'
2. Click on 'Bookmarks'
3. Click SingleFile
4. green ok. There is no error in Firefox / green ok followed immediately by Error in Chrome.

**Expected behavior**
save the page or produce a detailed error message.

**Environment**
 - OS: Windows 10 Pro 1803
 - Browser: Firefox 66.03 64bit
Google Chrome 73.0.3683.103 32bit
 - Version: Single File 1.10.34

**Comment by gildas-lormeau** [comment] 2019-04-18 12:00
@AdKiller Thanks for reporting the issue. Since I do not have any URL to test, I need more details about the error. When this error happens, could you please press F12 and tell me if you see an error (i.e. messages in red) in the console? (cf. "Console" tab).

If you can't see any error, please follow this procedure (in Firefox):
- go to about:debugging#addons,
- click the checkbox "Enable add-on debugging" at the top left,
- find SingleFile in the list of installed extension and click the "Debug" link,
- it will open a new window and a confirmation dialog box, click on "OK" in the confirmation dialog box,
- in the new opened window, please tell me if you see errors in the "Console" tab.

**Comment by AdKiller** [comment] 2019-04-18 12:59
from console, after enabling debug:

Could not map contract ID '@mozilla.org/widget/printdialog-service;1' to CID {06beec76-a183-4d9f-85dd-085f26da565a} because no implementation of the CID is registered.
cookies is undefined cookies.js:105
Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. vapi-background.js:695
Error: Missing host permission for the tab, and any iframes
undefined
Error: Frame not found, or missing host permission
undefined
Error: Unmanaged tab id: 34 tab.js:444:15
Error: Unmanaged tab id: 35 tab.js:444:15
Error: Frame not found, or missing host permission
undefined
Error: Missing host permission for the tab
undefined
Error: Unmanaged tab id: 39 tab.js:444:15
Error: Missing host permission for the tab undefined
Error: Frame not found, or missing host permission
undefined
TypeError: Argument 1 of PrecompiledScript.executeInGlobal is not an object.[Learn More] ExtensionContent.jsm:490:18
Error: Missing host permission for the tab


from F12:

Request to access cookie or storage on “https://ptpimg.me/...” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.
___________________

Turned off content blocking in Firefox >> no change
SingleFile successfully saves other pages of this website, and has this problem only with one page.

**Comment by gildas-lormeau** [comment] 2019-04-18 13:11
That's really weird. I don't find in these logs any interesting info coming from SingleFile. Can you tell me what is the title of the page you're trying to save? You can get the exact value by pressing F12 and typing in input field at the bottom of the console: `document.title`.

**Comment by AdKiller** [comment] 2019-04-18 13:45
I tried again in fresh Firefox profile.

both Developer Console & Debug Console are empty before and after clicking SingleFile

This page is very long and has a lot of embedded images. When I click the camera button in Developer console "take a screenshot of the entire page", the produced image has 1894 x 18882 dimensions and a little bit of the page is cut off in the screenshot. So maybe it is a Firefox bug.

**Comment by gildas-lormeau** [comment] 2019-04-18 13:52
Thanks for the info. This could also be related to invalid characters in the filename. That's why I would like to know the title of the page. Disabling "Misc > Save pages in background" could also help to circumvent the issue and prove that the filename is the cause of the issue.

**Comment by AdKiller** [comment] 2019-04-18 13:58
disabled  Save pages in background and it works fine!

the only thing in the document title that could be problematic is this  :: 

Thanks

**Comment by gildas-lormeau** [comment] 2019-04-18 14:05
Can't you give me the title of the page please? I would like to reproduce and fix this issue properly...

**Comment by AdKiller** [comment] 2019-04-18 14:07
"Your bookmarked torrent groups :: Redacted"

**Comment by gildas-lormeau** [comment] 2019-04-18 14:09
I can't reproduce the issue with this title. Are you sure there are not any special character in the "Redacted" part?

**Comment by AdKiller** [comment] 2019-04-18 14:13
I copy pasted the whole output of document.title from console. "Redacted" is actually part of the site name. I did not remove anything.

Yes there is a "_" instead of "::" in the downloaded file.

**Comment by gildas-lormeau** [comment] 2019-04-18 14:15
That's really weird... Do you confirm you use the default template (i.e. "{page-title} ({date-iso} {time-locale}).html") for the filename in your settings?

**Comment by AdKiller** [comment] 2019-04-18 14:16
confirming every setting is at default

**Comment by gildas-lormeau** [comment] 2019-04-18 14:19
Thanks. Could you please do this last test? Type `encodeURIComponent(document.title)` in the developer console and paste the value of the title here. It would allow me to see if there are any non-visible characters.

**Comment by AdKiller** [comment] 2019-04-18 14:20
"Your%20bookmarked%20torrent%20groups%20%3A%3A%20Redacted"

**Comment by gildas-lormeau** [comment] 2019-04-18 14:37
Thanks again. This confirms the title contains no other special characters. I tried to reproduce your issue by typing in the console `document.title = "Your bookmarked torrent groups :: Redacted"` just before saving any page but I cannot. Right now, I am 99.99% sure the problem comes from the generated filename but I have absolutely no idea what is the cause. I'm also doing my tests on Win 10 Pro.

**Comment by AdKiller** [comment] 2019-04-18 14:44
Good thing there is a workaround.

sorry for going off topic here: 
when I save webpage, complete in Firefox, the resulting folder and html file are about 67MB. but the file that SingleFile saves is 88MB. Why is that? Is there any way to reduce the size?

**Comment by gildas-lormeau** [comment] 2019-04-18 14:55
Yes, the workaround is welcome but it's also very frustrating to know the issue exists but I reproduce fix it...

Regarding the filesize, this is indeed the main drawback of SingleFile. Every binary resources (e.g. images) are encoded in [Base64](https://en.wikipedia.org/wiki/Base64). Thus, the actual length of the binary data is about 137% of the original data length.

**Comment by AdKiller** [comment] 2019-04-18 15:02
I can send you the folder+html

**Comment by gildas-lormeau** [comment] 2019-04-18 15:10
@AdKiller I'm currently testing titles with special chars and I can somewhat reproduce your issue, maybe. It means that I am still able to generate title that produce invalid filenames and the error you described. I'm going fix this issue and when it will be fixed, I'll ping you to see if I fixed yours too in the process.

**Comment by gildas-lormeau** [comment] 2019-04-18 20:47
@AdKiller Please let me know if the verision 1.10.35 fixes this issue.

**Comment by AdKiller** [comment] 2019-04-18 20:50
Just updated. unfortunately not. Save pages in background does not work.

**Comment by gildas-lormeau** [comment] 2019-04-18 21:04
Thanks you very much for your swift response. Maybe you're right actually. I need to do some tests to verify if the size of the saved page could cause this issue.

**Comment by gildas-lormeau** [comment] 2019-04-18 21:42
@AdKiller I think I fixed the issue. I mean that I found one issue that is very similar to yours. Please let me know if the version 1.10.36 fixes it.

**Comment by AdKiller** [comment] 2019-04-18 21:49
Save pages in background works now. Great job!

**Comment by gildas-lormeau** [comment] 2019-04-18 21:54
Great! Thank you very much for your tests :)

**Closed by gildas-lormeau** 2019-04-18 21:54 UTC

**Comment by AdKiller** [comment] 2019-06-07 08:30
I have similar problem with SingleFileZ on the same site as above.
The save progress stays stuck at 100%.

**Comment by gildas-lormeau** [comment] 2019-06-07 08:44
@AdKiller I guess that's because the "Save in background" is enabled by default and cannot be changed. Without the URL of the website, I cannot help you.

**Comment by AdKiller** [comment] 2019-06-07 09:20
The site is private behind a login. 
I think the problem SingleFileZ is the very large file size of the page, that is around 180 MB saved with SingleFile. (it works by default settings and there is no need to disable save in background).

**Comment by gildas-lormeau** [comment] 2019-06-07 21:38
Indeed, this could be related... I'll try to do some tests.
