### ISSUE TITLE
No way to 'select multiple links' in order to 'Save selected links'

### ISSUE THREAD

**Issue by noto10** [gildas-lormeau/SingleFile#660] opened 2021-04-19 09:38 UTC
**Is your feature request related to a problem? Please describe.**

Yes. Singlefile's 'Save selected links' does a wonderful job at saving multiple links. However, there is no easy way to select multiple, _**SEPARATE**_ links which is often the case in reality.

For example, in the following screenshot of a web page, there is no way to select the highlighted links (in yellow) so that they can be saved using 'Save selected links'. This defeats the purpose of the feature.

![2021-04-19_singlefile](https://user-images.githubusercontent.com/13828004/115214208-dfcc1f80-a134-11eb-9a91-dbc93201e6ff.jpg)

The above scenario is extremely commonplace to many scenarios to which "Save selected links' apply.

**Describe the solution you'd like**

A method to select multiple, non-contiguous links for use with 'Save selected links'.

**Comment by gildas-lormeau** [comment] 2021-04-19 13:54
There is a way to solve this issue. Use Firefox and select the text with the Ctrl key pressed, as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/396787/115247376-084d1d00-a127-11eb-9f29-37913d43faa2.png)

**Comment by noto10** [comment] 2021-04-19 15:15
I have tried doing this. The links can be selected but 'Save selected links' either only save one link (the link on which I right-click to 'Save selected link') or if I right-click on a non-link area, nothing gets saved.

**Comment by gildas-lormeau** [comment] 2021-04-23 20:53
I cannot reproduce the issue then. On my machine, 'Save selected links' saves all the links that are selected even if I used Ctrl to select multiple contents.

**Comment by gildas-lormeau** [comment] 2021-08-12 00:17
I'm closing this issue because I was not able to reproduce it. Feel free to reopen it if necessary.

**Closed by gildas-lormeau** 2021-08-12 00:17 UTC
