### ISSUE TITLE
Support for Mac

### ISSUE THREAD

**Issue by ivanfei-1** [gildas-lormeau/SingleFile#569] opened 2020-12-17 03:31 UTC
This app is so good and helpful！ But the SingleFileMacOS isn't working on Mac OS now. plz add an Safari Extension orz.
<img width="1162" alt="截屏2020-12-17 上午11 29 29" src="https://user-images.githubusercontent.com/67986259/102440402-23b1f980-405b-11eb-9376-fba22fe7ec26.png">

**Comment by gildas-lormeau** [comment] 2020-12-17 10:38
I understand your frustration. I would also like to be able to port SingleFile to Safari. The problem is that Apple requires me to have a Mac and I pay $100/year to do so. On top of that, there is also the amount of work time needed to test, debug and adapt the code. Indeed, the support of Web extensions on Safari is far from being 100% compatible with the [specification](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions).
Today, these conditions are quite unacceptable from my point of view. As far as I know, many developers share my opinion, see https://twitter.com/jensimmons/status/1338558758025367553.

**Comment by warichnict** [comment] 2021-01-05 21:47
just use opera, firefox or swr iron, safari is not a browser for a pro but for a fancy user ;)

pro users want to use pro products, pro products are most times free (cause paid is most time outdated bloatware), so if your system dosnt support free software anymore (apple lost interest after osx 10.6 or so, lion was the first killer for any free exchange) but just creating a garden for the rich but dumb folks...

**Comment by ogirginc** [comment] 2021-02-26 12:26
> I would also like to be able to port SingleFile to Safari. The problem is that Apple requires me to have a Mac and I pay $100/year to do so. On top of that, there is also the amount of work time needed to test, debug and adapt the code.

@gildas-lormeau would you consider found raising? For example, I have contributed to https://github.com/sindresorhus/refined-github/issues/3686. I can't say how many are willing to pay for this, but you can count me in. :)

**Comment by gildas-lormeau** [comment] 2021-02-28 13:56
@ogirginc Thank you for your support! In fact, I'm already accepting donations for people who want to support SingleFile. I might agree to the principle of paying the annual fee through these donations. However, it doesn't solve the Mac problem. I still have a little trouble accepting that Apple forces me to buy one to develop a Web Extension, which is supposed to be portable. It's not a problem of money but a matter of principle.

**Comment by unphased** [comment] 2022-03-10 07:50
I think that it would be possible to make a Safari extension that does something super simple which is to export the visited URL plus cookie state that pushes to either a local process or server which in turn runs SingleFile to generate the output.

I suppose this only probably seems like a reasonable approach for me, because I'm looking to use this library in a pretty specific way: I want to auto save/record all visited pages as a kind of maximally comprehensive browsing history. My plan is to build more layers on top of this big pile of data, such as filtering it down for textual content only, and then making that available for indexing for search. 

As part of the effort to cover browsing across all devices in this web browsing dragnet, I must include Safari (and in particular iOS Mobile Safari) as a lot of my time browsing is spent on apple devices. Since they are for the most part mobile devices I would prefer to avoid the added energy impact of doing the exporting work locally. I will make a new topic soon once I reach a specific roadblock that I need help with.

**Comment by gildas-lormeau** [comment] 2022-11-05 00:29
Hello Safari users. I wanted to keep you informed about this. Thanks to donations, I'll be able to buy a Mac and port SingleFile to Safari. I'm going to buy it in the next few days, I hope I'll have some good news soon!

**Comment by gildas-lormeau** [comment] 2022-11-05 23:07
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/396787/200144237-684f69d3-508c-4908-aa37-102939be0faf.png">

I have a Mac! It's a Macbook Pro M2 with 16GB of RAM. I must admit it runs well and is also very quiet. 

Regarding SingleFile. I have some good and bad news. 

The bad news is that the Manifest V3 version of SingleFile does not work at all. It's also impossible to debug it right now. The Manifest V3 support seems very poor in Safari currently. 

However, the good news is that the Manifest V2 version of SingleFile runs almost as is. Although, the major problem is that Safari does not offer to extensions any API to download files (see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download). I didn't know it and that's extremely regrettable, maybe I should have read the doc before buying this nice Mac... SingleFile has an option to download pages in "foreground" that can be used to circumvent this kind of issue. It somewhat helps but an annoying popup forces the user to confirm the download every time a page is saved. 

I suppose I'll need to learn how to code in Swift in order to circumvent the lack of the `downloads` API in Safari. It will be more complicated than expected...

**Comment by unphased** [comment] 2022-11-07 07:36
Awesome! Enjoy your new machine. Thanks for looking into this.

**Comment by gildas-lormeau** [comment] 2022-11-08 23:03
I released on GitHub the code of the extension for Safari here: https://github.com/gildas-lormeau/SingleFile-Safari. You can test it if you want/can. Any feedback is appreciated :).

You have to follow this procedure to install the extension:
1. Install [Xcode](https://apps.apple.com/us/app/xcode/id497799835?mt=12)
2. Download the Xcode project as a [zip file](https://github.com/gildas-lormeau/SingleFile-Safari/archive/refs/heads/main.zip) and unzip it somewhere on your machine
3. Launch Xcode and open the folder where you unzipped the Xcode project
4. Press the Play button at the top left of the XCode window to build and install the extension in Safari
5. Allow Safari to run unsigned extensions by following this procedure: https://developer.apple.com/documentation/safariservices/safari_app_extensions/building_a_safari_app_extension#2957925

**Comment by gildas-lormeau** [comment] 2022-11-10 21:35
The extension is now available for download on the store, see https://apps.apple.com/us/app/singlefile-for-safari/id6444322545

**Comment by gildas-lormeau** [comment] 2022-11-10 21:53
I'm closing the issue because it's fixed. Note that you can still post comments though, I will be notified.

**Closed by gildas-lormeau** 2022-11-10 21:53 UTC

**Comment by gildas-lormeau** [comment] 2022-11-12 18:35
Update: Hopefully and if the review goes well, SingleFile should be available on iOS as well in the coming days.

**Comment by gildas-lormeau** [comment] 2022-11-13 12:34
It's published for iOS :)

**Comment by Wildphinn** [comment] 2022-12-06 03:36
Just wanted to say thanks for releasing SingleFile on Safari. It's been the biggest thing I had been missing on that browser. Now I can use it perfectly content!
