### ISSUE TITLE
Large amount of font files in the saved page

### ISSUE THREAD

**Issue by abappl** [gildas-lormeau/SingleFile#1140] opened 2023-03-14 01:57 UTC
**Describe the bug**
When I run it on the site below, it does not proceed in the 3rd step.
or No Responspage message popup in the 2nd step.
  https://forums.oracle.com/ords/apexds/post/how-to-add-default-roles-to-an-user-schema-4638

The same thing happens with every post on the site below.
 https://forums.oracle.com/ords/apexds/domain/dev-community

**To Reproduce**
1. Go to site
  https://forums.oracle.com/ords/apexds/post/how-to-add-default-roles-to-an-user-schema-4638
2. Click on "save page with SingleFile" icon with default setting on chrome

**Expected behavior**
download the page

**Screenshots**
![image](https://user-images.githubusercontent.com/127807627/224872196-982f1ed0-b837-483c-8253-fa5e75edd33e.png)

**Environment**
 - OS:  Win10 Pro
 - Browser: Chrome

**Comment by gildas-lormeau** [comment] 2023-04-04 19:51
Thank you for the report. I confirm I can reproduce it in Chrome. This is due to large amount of font files (approx. 200) declared in the page which makes the browser crash. It can be circumvented by blocking the fonts in the options page of SingleFile, see `Network > Blocked resources > fonts`. I'll try to see if I can improve the detection of the unused fonts in SingleFile because I think there is probably something wrong there.

**Comment by abappl** [comment] 2023-04-04 23:11
> Thank you. It works!

**Comment by gildas-lormeau** [comment] 2023-07-21 22:04
I'm closing the issue because it's (now) a duplicate of an existing one.

**Closed by gildas-lormeau** 2023-07-21 22:04 UTC
