### ISSUE TITLE
Can't save chrome extension's page or content injected by extension

### ISSUE THREAD

**Issue by VikramTiwari** [gildas-lormeau/SingleFile#482] opened 2020-08-31 19:36 UTC
**Describe the bug**
I was trying to save the popup page from Honey extension but the extension shows the disabled icon. Is there any reason for that?

**To Reproduce**

1. Ensure that you have Honey extension installed
2. Go to chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/popover/popover.html
3. Click on extension to save the page.
4. Extension icons says disabled

**Expected behavior**
The page to get saved properly

**Screenshots**
<img width="1524" alt="Screen Shot 2020-08-31 at 12 32 19 PM" src="https://user-images.githubusercontent.com/1330677/91759143-07f71600-eb86-11ea-9316-8f7a970f8753.png">

**Environment**
 - OS: OSX 10.15
 - Browser: Chrome
 - Version: 84

**Additional context**
I also saw that if an extension injects some content in the page, that isn't saved/re-rendered properly as well.

Original page:
<img width="417" alt="Screen Shot 2020-08-31 at 12 35 11 PM" src="https://user-images.githubusercontent.com/1330677/91759452-818f0400-eb86-11ea-831b-e0c7b46e7a27.png">

Saved page: 
<img width="417" alt="Screen Shot 2020-08-31 at 12 35 22 PM" src="https://user-images.githubusercontent.com/1330677/91759471-85228b00-eb86-11ea-8740-b776baf651c1.png">
Honey icon is not present.

**Comment by gildas-lormeau** [comment] 2020-08-31 20:04
Unfortunately, this is normal. An extension cannot run in a page belonging to another extension. This concerns URLs starting with "chrome-extension://" in Chrome or "moz-extension://" in Firefox.

**Comment by VikramTiwari** [comment] 2020-08-31 20:06
Ah! That makes sense @gildas-lormeau! Is the reason same for content that's injected in the page?

Regardless, good job on this extension!

**Comment by VikramTiwari** [comment] 2020-08-31 20:11
Another example of content that's injected in the page by extension:

zoominfo extension's iframe's body has content in original page:
<img width="1518" alt="Screen Shot 2020-08-31 at 1 09 49 PM" src="https://user-images.githubusercontent.com/1330677/91764026-6a064a00-eb8b-11ea-8509-deb7c546794b.png">

zomminfo extension's iframe's body doesn't have any content in saved page:
<img width="1520" alt="Screen Shot 2020-08-31 at 1 10 01 PM" src="https://user-images.githubusercontent.com/1330677/91764066-7e4a4700-eb8b-11ea-814b-8f4a3fd0fc1d.png">

**Comment by gildas-lormeau** [comment] 2020-08-31 20:22
I reproduced the issue with Honey on Amazon. Actually, Honey is using a web component (https://developer.mozilla.org/docs/Web/Web_Components) to inject the content in the page but the shadow root is "closed", see below.
![image](https://user-images.githubusercontent.com/396787/91764493-af506900-ebd7-11ea-9099-cc3d8bab1b73.png)

Today, SingleFile can't save closed shadow roots because it requires a little hack that I would prefer to avoid.

The iframe issue is indeed probably due to the fact that the content comes from another extension. I did not test zoominfo though.

**Comment by VikramTiwari** [comment] 2020-08-31 20:40
That's interesting and makes sense. Thanks for looking into it!

For the iframe issue, is there some hack to get the content of other extensions as well (even though you might not wanna do it in the code).

**Comment by gildas-lormeau** [comment] 2020-08-31 20:46
Can you tell me how to reproduce the iframe issue? I'll take a look at it. Who knows, it's maybe a bug in SingleFile.

**Comment by VikramTiwari** [comment] 2020-08-31 20:55
Sure! Here are the repro steps:

- Install zoominfo plugin: https://chrome.google.com/webstore/detail/zoominfo-plugin/gmmgalbbpgdijgoahnnlklhekpkfheih
- Go to google.com and you should see the icons on right size of the page to open the side panel
<img width="249" alt="Screen Shot 2020-08-31 at 1 51 54 PM" src="https://user-images.githubusercontent.com/1330677/91767687-670e5800-eb91-11ea-9b1c-66034cf1524b.png">

- Click on the second icon to open the extension.
<img width="780" alt="Screen Shot 2020-08-31 at 1 53 33 PM" src="https://user-images.githubusercontent.com/1330677/91767712-71305680-eb91-11ea-96fd-045996f0b51d.png">

- Save the page using SingleFile
- Open the page and you will see that the contents inside the zoominfo sidebar are missing.
<img width="665" alt="Screen Shot 2020-08-31 at 1 54 43 PM" src="https://user-images.githubusercontent.com/1330677/91767765-8b6a3480-eb91-11ea-8d0d-518c615e57f5.png">

**Comment by gildas-lormeau** [comment] 2020-09-01 11:00
Thank you very much! I've traced the SingleFile execution and I think I can confirm that this is related to the fact that iframes are injected by ZoomInfo Plugin. I see that SingleFile is trying to communicate with the iframes but is not succeeding. The reason is not clear to me because these iframes have no `src` attribute. However, I don't see today how to solve/circumvent the problem.

Debugging this problem helped me to fix 2 minor unrelated bugs. This is still good news!

**Comment by VikramTiwari** [comment] 2020-09-01 13:52
That's was some good news for sure haha

Do you think the communication is not working because those frames are of [out of process iframes](https://www.chromium.org/developers/design-documents/oop-iframes)? And if so, is there any way around it?

**Comment by gildas-lormeau** [comment] 2020-09-01 14:18
I'm not sure this is related. The problem is that the messages sent with `postMessage` are not received by content scripts injected into iframes. However, according to the documentation, the calls to `postMessage` should work.

**Comment by gildas-lormeau** [comment] 2020-09-01 15:14
Launching Chrome with the option `--disable-features=IsolateOrigins,site-per-process` does not fix the issue either.

**Comment by VikramTiwari** [comment] 2020-09-01 16:40
Hey @gildas-lormeau I want to confirm a few things:
- I see that you are using `browser.runTime.sendMessage` mostly everywhere possible, and most importantly when asking to save page [here](https://github.com/gildas-lormeau/SingleFile/blob/953ce220165a4acfb620a1a1186bd627702270b1/extension/core/content/content-bootstrap.js#L178).
- Is [this](https://github.com/gildas-lormeau/SingleFile/blob/1608e37ec46b9ef869b0244d61a19052bf8f5b67/lib/single-file/processors/frame-tree/content/content-frame-tree.js#L328) the `postMessage` call you are talking about? If so, as I understand it, the code is trying to send the content of the iframe to parent and then from top frame you are trying to send it back to the extension. Am I correct?

Do you have any suspects that I can help track down? The project is massive and I am trying to get a handle on where can I look to get started on helping fix this problem.

**Comment by gildas-lormeau** [comment] 2020-09-01 17:02
@VikramTiwari I just did some tests which do not rely on `postMesssage` at all (the line you highlighted is the correct one). I use `postMessage` to assign to the corresponding window an id representing the position of the frame in the tree. For example the windowId `0.2.1` means that the current window is the second frame (`1`) of the third frame (`2`) of the page (always `0`). I found this clever response on SO https://stackoverflow.com/questions/26010355/is-there-a-way-to-uniquely-identify-an-iframe-that-the-content-script-runs-in-fo/ showing that the windowId value could be computed without needing to call `postMesssage`. I tested this approach because I was very promising regarding the current issue. The good news is that I confirm that the computed `windowId` is correct with this approach.

However, I actually see that when the background page sends a message to all the frames of the page (by using `browser.tabs.sendMessage`), the 2 content scripts that are injected in the 2 main iframes in the panel never receive that message. It means that the extension API cannot be used to communicate with these frames either. I think we're coming to a dead end...

**Comment by gildas-lormeau** [comment] 2020-09-01 17:12
Actually, I'm a bit wrong. Bidirectional communication does not work. It means `browser.tabs.sendMessage` does not work *but* `browser.runTime.sendMessage` works. It means that if I can refactor the code to avoid any bidirectional communications, there's is maybe a way to fix this issue.

**Comment by VikramTiwari** [comment] 2020-09-01 17:21
That's fantastic! It should make the internal communication more effective.

Let me know if I can help with refactor or if there's some canary build that you would like me to check to confirm.

**Comment by gildas-lormeau** [comment] 2020-09-01 17:53
I think that should be okay. I'll start to take a look at this tonight (in France). It requires some work because the CLI, as it exists today, will still rely on `postMessage`.

**Comment by VikramTiwari** [comment] 2020-09-01 17:58
Thanks for all the help in debugging this and making the fix. 💯

**Comment by gildas-lormeau** [comment] 2020-09-01 19:51
I did some additional tests and I have some bad news. 

The problem is that if the communication is not bidirectional and SingleFile wants to retrieve the data of frames when the user saves the page, then I have to use `browser.tabs.executeScript` to call a content-script function with the option `allFrames: true`. Unfortunately, this does not work. Again, the function call is not executed in the two main iframes of the panel. 

So, the only way to solve this issue would be to execute the script as soon as it is injected into the document via the `manifest.json` file. That would mean that each time a frame is dispalyed, SingleFile would get its content whereas the user didn't even save the page. This can be expensive in terms of CPU, depending on the number and the complexity of frames. For this reason and because it only concerns contents injected by other extensions, I'm afraid I can't fix this problem.

**Comment by VikramTiwari** [comment] 2020-09-01 20:07
Ah! That's not a good news, though understandable.

Do you think it's worth making it as a UI option where user can manually enable this CPU intensive mode? Or maybe another way to do this would be to show user that there are some frames which did not respond and if user can reload the page, they might get captured.

**Comment by gildas-lormeau** [comment] 2020-09-01 20:44
Technically, it's impossible to implement an option for this In Chrome because there are no APIs to add content scripts on the fly. In Firefox, this would be possible with `browser.contentScripts.register` (https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts). On the other hand, it is a lot of effort for a very special case.

**Comment by VikramTiwari** [comment] 2020-09-01 20:59
I didn't realize the blocker part of injecting on the fly. That makes sense. Thanks for explaining the issue and these details. I would love to see this fixed but I understand that it's a very edge case and thus the reluctance to work on it.

**Comment by gildas-lormeau** [comment] 2020-09-01 21:18
I'm sorry that I couldn't find a way to circumvent this issue. I'm still wondering if it's a bug or a feature though. I am keeping the issue open.

**Comment by gilles-yvetot** [comment] 2020-09-01 22:15
Hey @gildas-lormeau, I went ahead and created a small [POC](https://github.com/OmniLabsInc/poc-single-file) which inject code on the fly and show some bi-directional messaging.
It is injecting a red button on the main frame. When you click on it, it sends a message to the background that will inject code in every frame to turn their input in green and then send a message back to the background script.
I have tested on google.com with the zoomInfo plugin open.
Let me know if it helps and if I understood the problem correctly ;)

**Comment by gildas-lormeau** [comment] 2020-09-01 22:35
Hey @gilles-yvetot !

I think you understood the problem well. It's my fault because I missed some details. 

The problem is that the code you inject in the background page is not executed in all the frames. I added the functions from SO in your background code to log the window ID. 

```
function messageHandler(message, sender, sendResponse) {
  console.log('message', message, sender)
  if (message.type === `MESSAGE_FROM_MAIN_FRAME`) {
    chrome.tabs.executeScript(sender.tab.id, {
      code: `
console.log(iframeFullIndex());
for (const input of document.getElementsByTagName('input')) {
  Object.assign(input.style, { background: 'green' })
}
chrome.runtime.sendMessage({ type: 'MESSAGE_FROM_ALL_FRAMES' })


function iframeIndex(win) {
  win = win || window; // Assume self by default
  if (win.parent != win) {
    for (var i = 0; i < win.parent.frames.length; i++) {
      if (win.parent.frames[i] == win) { return i; }
    }
    throw Error("In a frame, but could not find myself");
  } else {
    return -1;
  }
}

function iframeFullIndex(win) {
  win = win || window; // Assume self by default
  if (iframeIndex(win) < 0) {
    return "";
  } else {
    return iframeFullIndex(win.parent) + "." + iframeIndex(win);
  }
}
      `,
      allFrames: true,
    })
  }
}
chrome.runtime.onMessage.addListener(messageHandler)
```

When you'll click on the button, you'll see in the logs that the frames ".1.0" and ".1.0.0" execute the code but not ".0" and ".1".

**Comment by gildas-lormeau** [comment] 2020-09-01 22:46
Whereas if you add the same in `inject.js` and add in the `content_scripts` entry of the manifest.json file `"all_frames": true, "match_about_blank": true`, you'll see the expected logs.

**Comment by gilles-yvetot** [comment] 2020-09-01 22:52
When using `chrome.runtime.executeScript`, how do you inject the 2 functions `iframeFullIndex` and `iframeIndex` into all the frames? Do you put them as a string right before `console.log(iframeFullIndex())` ?
I am surprised `win.parent.frames` works when inside a cross-origin frame

**Comment by gildas-lormeau** [comment] 2020-09-01 22:57
The 2 functions are injected at the end of the code in my example. The code is not executed in all the frames, that was the point actually. I was also surprised to learn that `win.parent.frames` worked but it makes sense.

**Comment by gildas-lormeau** [comment] 2020-09-01 23:22
FYI, here is the POC modified. In the logs of the background page, you'll also see a suspicious "message {type: "MESSAGE_FROM_ALL_FRAMES", index: "", location: "https://www.google.com/..."}". The `index` is empty but it's a frame.

[poc-single-file-master.zip](https://github.com/gildas-lormeau/SingleFile/files/5159237/poc-single-file-master.zip)

**Comment by gilles-yvetot** [comment] 2020-09-01 23:35
So we have encountered a couple of issues with Chrome itself with OOPIFs. Essentially not always printing to the console so it might be the reason. I have made 2 videos to illustrate that. I am printing `window.location.href` in every frame when clicking on the red button

1) On the first video, you can see only 2 frames print something (Google Translate extension frames). BUT the code is actually ran correctly in all frames (including the zoom info ones) and you can see the inputs are green 
https://www.loom.com/share/da6b7e2271b049e384a15bc229fede10
2) Second video, doing the same thing. Location are correctly printed and the inputs are green as well
https://www.loom.com/share/ac428c9f5ed643379cfe47702aeef243

To reproduce this chrome bug, I think you need to open your devtools before opening the zoom info frame

**Comment by gildas-lormeau** [comment] 2020-09-01 23:42
The iframes I'm talking about *do not contain any inputs* and their src is empty.

**Comment by gildas-lormeau** [comment] 2020-09-02 10:31
In the end, I think it's not a bug but a feature. I tried to call `chrome.webNavigation.getAllFrames` from the background page in your POC and I get the same results. Only 2 frames are returned by the API whereas there are actually 4 frames in the document.

**Comment by gilles-yvetot** [comment] 2020-09-02 16:47
Yeah we have seen the same behavior when working on other problems. The frames the extension API is giving us are always the ones that matter to us. Frames with content and usually navigation. The empty frames or frames just wrapping other frames are usually not there.

**Comment by gilles-yvetot** [comment] 2020-09-02 19:54
I opened a [ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=1124399) on crbug mentioning the bug about not having all the frames

**Comment by gildas-lormeau** [comment] 2020-09-02 22:39
On my end, I tested a POC (see attached file) to see if it would be possible to get the frame contents by relying only on the scripts injected by the manifest.json file. It shows that it's possible to receive a message from all the frames in the background page *but* there are 2 issues:
 - the HTML content of the 2 iframes that can't receive messages from the background page is almost empty.
 - the script is based on a timeout to detect DOM changes and delay the sending of the message to the background page. The delay is 150ms. If I increase it to 200ms, the timeout is cancelled.

[poc-single-file-master.zip](https://github.com/gildas-lormeau/SingleFile/files/5165141/poc-single-file-master.zip)

**Comment by gildas-lormeau** [comment] 2020-09-08 23:24
I'm commenting my last post which did not seem to be interesting... I guess all the logs are displayed because the 2 iframes are initialized with "about:blank" and then zoominfo loads internal pages where content scripts cannot run. The ticket on crbug.com confirms it is working as expected, as I explained https://github.com/gildas-lormeau/SingleFile/issues/482#issuecomment-684008133. By the way, it works the same in Firefox.

I'm also closing his issue because it's technically impossible to implement this feature. Feel free to comment it or reopen it if necessary.

**Closed by gildas-lormeau** 2020-09-08 23:24 UTC
Labels: feature request

**Comment by VikramTiwari** [comment] 2020-09-08 23:28
That sounds good @gildas-lormeau. Thanks for all the help in debugging this :)
