### ISSUE TITLE
Race Condition with Userscript integration

### ISSUE THREAD

**Issue by damoclark** [gildas-lormeau/SingleFile#326] opened 2019-12-22 05:43 UTC
**Describe the bug**
A race condition exists with the current userscript integration.  

Consider the following adapted example from the website:

```js
// ==UserScript==
// @name         Convert title to kebab-case
// @namespace    https://github.com/gildas-lormeau/SingleFile
// @version      1.0
// @description  [SingleFile] Convert title to kebab-case
// @author       Gildas Lormeau
// @match        *://*/*
// @noframes
// @grant        none
// ==/UserScript==


(() => {

  let title;

  window.setTimeout(() => {
    dispatchEvent(new CustomEvent("single-file-user-script-init"));
  },6000) ;

  addEventListener("single-file-on-before-capture-request", () => {
    title = document.title;
    document.title = document.title
      .replace(/[^a-z0-9-\s]/gi, "")
      .replace(/[-\s]+/g, "-")
      .toLowerCase();
  });

  addEventListener("single-file-on-after-capture-request", () => {
    document.title = title;
  });

})();
```

**To Reproduce**
1. Set the autosave option on and the delay to be shorter than 6seconds as set in the settimeout call above
2. Implement the above userscript
3. Load a page

The `single-file-user-script-init` event is not received by singlefile before it attempts to save the page. Thus singlefile doesn't know to send the events to the userscript.

In the real world, the problem manifests when you use session managers and reload a session with many tabs.  The userscript often doesn't execute before singlefile's delay expires.

While changing the delay to be higher can help, it's an arbitrary guess and doesn't really solve the race condition, especially when wanting to save pages on load.

**Environment**
 - OS: macOS 10.13
 - Browser: Firefox
 - Version: 71

**Comment by gildas-lormeau** [comment] 2019-12-27 00:05
Wouldn't the key `@run-at document-start` fix the issue?

**Comment by damoclark** [comment] 2019-12-29 11:10
> Wouldn't the key @run-at document-start fix the issue?

Unfortunately it doesn't.  

> In the real world, the problem manifests when you use session managers and reload a session with many tabs. The userscript often doesn't execute before singlefile's delay expires.

It was one of the first things I tried when restoring a saved session.  From what I can ascertain, there isn't currently a deterministic way of synchronising the events as currently implemented in the singlefile API.

**Comment by gildas-lormeau** [comment] 2019-12-29 14:30
From my point of view, I consider the bug is the lack of `@run-at document-start` key (or `@run-at document-end` which should work too) in my examples. I expect the userscript to be run ASAP because the event `single-file-user-script-init` *must* be dispatched before the document is loaded, it's a requirement. If the userscript is not run before the document is loaded whereas the `@run-at document-start` key is present then I'm tempting to think it's a bug in the extension you're using to run userscripts.

**Comment by damoclark** [comment] 2020-01-01 03:20
Thanks @gildas-lormeau for engaging with me on this.

I should note that if you are able to crack #327 , then this becomes much less of an issue. i.e. solving #327 obviates this ticket.  The following is in response to your previous message.

I did do quite a few tests using `@run-at document-start` using [this advice](https://wiki.greasespot.net/Metadata_Block#.40run-at) from Greasemonkey author Anthony Lieuallen and was able to confirm that the script was being initiated at document start. **But all that is guaranteed is when the script is starting.** I suspect the problem is the standard concurrent programming issue of synchronicity.  

> I expect the userscript to be run ASAP

Does the DOM continue to load (concurrently) before all event handlers of the document-start event are finished?

Again, quite a few gaps in my knowledge here.  Please correct me if any of the following is incorrect.  But based on what I know of event handling in JS, event handlers are called in sequence, based on a queue.  How handlers are added to the queue is opportunistic (not deterministic), and the timing of any blocking of handlers and other events on the event loop can influence the execution sequence of handlers.

My experimentation showed that if I opened many concurrent tabs, using a session manager, at a certain point, some would send the `single-file-user-script-init` before the delay period had expired for the page, while some wouldn't.  This is pretty consistent with a race condition in concurrent programming.

**Comment by gildas-lormeau** [comment] 2020-01-06 21:18
Actually, I expect the code in SingleFile which listens to the `single-file-user-script-init` event (see below) to be the first to be run. 
https://github.com/gildas-lormeau/SingleFile/blob/47952f171fad1a5c73dd45918da7c1c0bb1e6981/lib/single-file/single-file-helper.js#L57
This is always true compared to the scripts of the page. However I'm wondering if sometimes the userscript is not executed *before* the code in SingleFile. That would lead to the issue you're describing *but* the `setTimeout` call would help to fix it though. 
If that's the cause of the issue then using `@run-at document-end` should fix it. Can you confirm or infirm that fixes the issue?

**Comment by damoclark** [comment] 2020-01-08 04:46
> It means the event single-file-user-script-init would be dispatched by the userscript before SingleFile would listen to it. That would lead to the issue you're describing but the setTimeout function call would help to fix it though (with a moderate delay). I hope I'm clear :p.

I think the issue might be the other way around.  I suspect that by the time the userscript sends the `single-file-user-script-init` event to singlefile, singlefile's 'delay' has already expired and it has started to save the page already.  Because it didn't receive the 'init' event first, it does not know to send the save started event to the userscript.  The userscript never knows about the save.  This is especially likely if singlefile initiates very early in the loading of the page - it's delay counter also starts early.

I also suspect this occurs due to CPU contention, when there are many tabs opened simultaneously as is the case with a session manager, and there are so many tasks on the JS event loop, that some are delayed longer than normal before their execute.

Hope that makes sense.

D.

**Comment by gildas-lormeau** [comment] 2020-01-08 14:11
> > It means the event single-file-user-script-init would be dispatched by the userscript before SingleFile would listen to it. That would lead to the issue you're describing but the setTimeout function call would help to fix it though (with a moderate delay). I hope I'm clear :p.
> 
> I think the issue might be the other way around. I suspect that by the time the userscript sends the `single-file-user-script-init` event to singlefile, singlefile's 'delay' has already expired and it has started to save the page already. 
Such delay does not exist in SingleFile. That's why I'm not sure I can fix this bug actually. You can dispatch "single-file-user-script-init" later but, as I said, it has to be dispatched before the document is fully loaded + `n` seconds.
Can you please confirm using `@run-at document-end` does not work for you?

> I also suspect this occurs due to CPU contention, when there are many tabs opened simultaneously as is the case with a session manager, and there are so many tasks on the JS event loop, that some are delayed longer than normal before their execute.
> 
> Hope that makes sense.
> 
> D.
That might be a cause of this issue indeed.

I will post in this thread a custom build of SingleFile which will remove the need to dispatch the `single-file-user-script-init` event. If that's okay for you, I would like that you install it and tell me if it fixes your issue.

**Comment by gildas-lormeau** [comment] 2020-01-08 14:29
Here is the custom build. As I said, you do not need to dispatch `single-file-user-script-init` event with this version (it will be ignored by SingleFile). So this custom build is supposed to fix your issue. Can you please confirm it? To install it, unzip it somewhere on your disk and follow this procedure: https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/. Note that this custom build be automatically uninstalled when restarting Firefox.


[singlefile-extension-firefox.zip](https://github.com/gildas-lormeau/SingleFile/files/4035701/singlefile-extension-firefox.zip)

**Comment by damoclark** [comment] 2020-01-12 11:15
Hey @gildas-lormeau 

Thanks.  I'll test it and get back to you.

D.

**Comment by damoclark** [comment] 2020-01-21 04:30
Hey sorry I haven't had a chance to test this for you as I've been very busy.  And I have to undo some work arounds to recreate the settings to test with.

**Comment by gildas-lormeau** [comment] 2020-01-21 15:12
Okay, thank you for the update @damoclark.

**Comment by gildas-lormeau** [comment] 2020-01-30 22:12
@damoclark any news?

**Comment by gildas-lormeau** [comment] 2020-02-03 15:03
I'm closing this issue (and the other one you opened) because I did not get any answer from you actually. Feel free to test the build I made especially for this issue and give me some feedback if you are still interested in this issue.

**Closed by gildas-lormeau** 2020-02-03 15:03 UTC

**Comment by damoclark** [comment] 2020-02-23 10:52
Hi @gildas-lormeau 

> I'm closing this issue (and the other one you opened) because I did not get any answer from you actually. 

I'm sorry I havent tested the custom build.  Like you, open source is a hobby, but my paying job must take priority and it has been very busy of late.

After initially reporting the issue, I put into place a workaround.  To recreate the original circumstances that led to reporting the issue in the first place is very time consuming.

As I mentioned before, if you can implement something for issue #327 it solves the problem with #326.  Have you considered implementing a solution that allows a userscript to initiate a save?  That is something I can test for you very easily.  

Regards,
Damien.

**Comment by gildas-lormeau** [comment] 2020-02-23 11:15
Hi @damoclark,

Thank you for the feedback. Genraly speaking, I'm not against fixing issues *but* I need to understand what I'm fixing. If you cannot do the tests anymore, would it be possible to describe how to reproduce the issue reliably? Thus, I'll be able to see what's wrong exactly and know what to do to fix the issue.

**Comment by damoclark** [comment] 2020-02-28 10:04
Did you try the my [initial instructions](#issue-541411287)?  

Alternatively, create a firefox session with many tabs (50+) and using, Tab Session Manager extension, save it.  Make sure your TSM settings will reopen all tabs on loading up the session (turn off the delay option in their settings).

Then restart, reload the session through TSM.  Your userscript will only execute in some tabs.  

Let me know if you are able to reproduce with this approach.

D.

**Comment by gildas-lormeau** [comment] 2020-02-28 20:28
I will try to follow your procedure *but* I won't include the `window.setTimeout(() => {})` function call, because the code `dispatchEvent(new CustomEvent("single-file-user-script-init"))` is obsolete with the custom build I wanted you to test. In these conditions, I guess it will be hard for me to reproduce this random issue...
