### ISSUE TITLE
Proper handling of webpages with unavailable resources

### ISSUE THREAD

**Issue by pchemguy** [gildas-lormeau/SingleFile#873] opened 2022-02-14 21:53 UTC
**Describe the bug**
Sometimes, web pages include references to resources, which may not be available. I cannot see such resources anyway and, sure thing, if I want to save a webpage, I do not care about what I do not see anyway.

**To Reproduce**
1. Go to 'https://www.spacedventures.com/offers/infinite-composites-inc/pitch'
2. Try saving
3. See failure (scrollbar freezes close to the end, as the number of timed-out resources varies from time to time)

**Expected behavior**
Set a certain timeout and display a warning in case certain resources cannot be loaded, providing the option to ignore such resources.

**Screenshots**
Screenshots of *Save Page WE* handling unavailable resources
![Save Page WE handles unavailable resources](https://user-images.githubusercontent.com/39730837/153950526-f77e94d5-934a-48e0-99ff-844911df241f.jpg)
(https://www.compositesworld.com/articles/nasa-institute-developing-carbon-nanotube-based-composites-for-mars-spacecraft)
![Save Page WE handles unavailable resources2](https://user-images.githubusercontent.com/39730837/153951865-843475ee-9b75-4cfb-8d4b-7c185c095883.jpg)
(https://www.spacedventures.com/offers/infinite-composites-inc/pitch)

**Environment**
 - OS: Win10 LTSC
 - Browser: Chromium, Chrome, Firefox
 - Version: 88 (Chromium)

**Additional context**

**Comment by gildas-lormeau** [comment] 2022-02-14 22:37
I'm very hesitant to implement such a feature exactly for the reason you mentioned. There is no failure on the web page you mentioned. There is just a very large GIF that takes (very long) time to save. The bug might be that the progress bar does not show it. 
The problem of the timeout setting is that it's actually hard to set it to a correct value. That's exactly why Save Page WE failed to save the page in your example.

**Comment by pchemguy** [comment] 2022-02-16 08:07
You got it wrong. It is Save Page WE that let me ignore those resources and saved the pages, which I could not save with SingleFile. I only click to save a page when I can see what I want to save. Basically, at this point, the extension should ideally only save resources already in the browser cache and load them from the browser cache. No resources should be downloaded from the Internet. Again, once I want to save the page, I DO NOT care about any resources not in the browser cache.

**Comment by gildas-lormeau** [comment] 2022-02-16 12:24
I'm sorry but I'm not wrong. Do the test again and compare the saved pages. SingleFile does not freeze and saves all the GIFs while Save Page WE does not.

**Comment by pchemguy** [comment] 2022-02-16 17:07
Do not be and, yes you are wrong. If you check out my account, you will probably see that I have sufficient IT skills to figure out that I need to try multiple times. I do not know how you use Save Page WE, but SingleFile freezes every time around 90-95% on both links. What Save Page WE does is on the screenshots, it DOES save those pages. It is not as interactive as SingleFile, I give you that. But it still works, as opposed to SingleFile.

**Comment by gildas-lormeau** [comment] 2022-02-16 17:24
Then, I'm sorry but I cannot reproduce your issue. On my end, the time to save the page is long but it works.

**Comment by pchemguy** [comment] 2022-02-16 19:05
Ok, it's a bit weird design decision. I suppose it is not very common, but still.

Save Page WE does not provide an option to continue saving the heavy resource. After the timeout, the only option is to save without those resources.

I tried SigleFile again. After more than 40 minutes still no result. When I use the standard save feature, it saves just fine, though it does take longer than for a normal page (not super long though).

It is not clear what the problem is, as SignleFile does not really provide any feedback. And I suppose these are kind of pathological cases. I wished SignleFile worked for me here though.

**Comment by gildas-lormeau** [comment] 2022-02-16 19:14
You found a bug. That's why SingleFile did not provide any feedback. This bug will be fixed soon, I'm currently fixing it...

**Closed** 2022-02-16 21:41 UTC

**Comment by gildas-lormeau** [comment] 2022-02-16 21:43
The bug is fixed in the version 1.19.30 which should available for download in the coming hours. Note that it takes almost 5 minutes to save the page because the servers hosting the GIFs are a bit slow.

**Comment by pchemguy** [comment] 2022-02-18 11:52
What about "save webpage complete"? It took me probably half a minute, a minute max.

**Comment by gildas-lormeau** [comment] 2022-02-18 13:47
Is the page "complete"? It's supposed to weight  approx. 160 MB

**Comment by pchemguy** [comment] 2022-02-19 09:34
I mean save with Chrome "webpage complete". It saves the heavy gif just fine. Takes 0.5-1 min as mentioned.

**Comment by gildas-lormeau** [comment] 2022-02-19 23:13
I guess it's because the browser is allowed to download the resource from the cache. Unfortunately, extensions don't have this privilege with resources downloaded from third-party servers with CORS.

**Comment by gildas-lormeau** [comment] 2022-04-27 19:31
@pchemguy FYI I added an hidden option called `networkTimeout` in the last version, see here for more info how to set it: https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options

**Comment by pchemguy** [comment] 2022-04-28 10:19
@gildas-lormeau I will check it out.
