### ISSUE TITLE
Implement "Save link with SingleFile"

### ISSUE THREAD

**Issue by eixan** [gildas-lormeau/SingleFile#262] opened 2019-08-30 16:15 UTC
**Describe the bug**
This probably effects other sites as well however it's pain to check cause of browser redirects. Reddit links are in clear text.

**To Reproduce**
https://drive.google.com/file/d/1FEKqEIZGxTOqS0xsTYEofUNTEvMHx7vc/view?usp=sharing

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Windows 10 pro OS Build:18362.295 Version:1903
 - Browser:  Version 76.0.3809.100 (Official Build) (64-bit) but I also tested it with the most recent version of chrome via protable apps but for some reason they only have a 32bit version
 - Version: [e.g. 64]

**Additional context**

**Comment by gildas-lormeau** [comment] 2019-08-30 18:29
In fact, the feature you are requesting does not exist today. The menu entry allows you to save the current page even if you click on a link. 

Unfortunately, it is not easy to implement what you want. The problem is that SingleFile only saves pages already displayed in the browser. This means that SingleFile should create a new tab and load the page inside this tab and maybe close it automatically afterwards. I'm not sure this behavior will be pleasant from a user experience point of view.

**Comment by alivefromupstairs** [comment] 2019-09-06 13:40
@gildas-lormeau So, it's not currently possible to save something like https://google.github.io/eng-practices/review/reviewer/ that has multiple ends that contributre to the same article? you could put each one in a tab and save them independently, but you wouldn't have them linking to each other out of the box, right? could you implement something like "smart anchors" where the href would be replaced with a relative one if you have that href waiting to be downloaded as well?

**Comment by gildas-lormeau** [comment] 2019-09-06 13:46
@alivefromupstairs This feature ("samrt anchors') is not possible to implement in SingleFile. However, it's technically possible in SingleFileZ. The corresponding issue is this one: https://github.com/gildas-lormeau/SingleFileZ/issues/20

**Comment by alivefromupstairs** [comment] 2019-09-06 13:58
@gildas-lormeau is the self extracting capabilities of SingleFileZ the only difference between it and SingleFile?

**Comment by gildas-lormeau** [comment] 2019-09-06 14:22
@alivefromupstairs Currently, it's indeed the only difference. However, from a technical point of view, SingleFileZ offers more possibilities like the one we're discussing about that SingleFile cannot. In other words, the technical solution implemented in SingleFileZ would allow you to save several pages in a single (sel-extracting) file and allow you to navigate among these pages.

**Closed** 2019-09-15 00:45 UTC
Labels: feature request

**Comment by gildas-lormeau** [comment] 2019-09-15 00:47
This feature is implemented and will be available in the next version. Note that the linked page will be opened in a temporary tab in order to save it properly.

**Comment by gildas-lormeau** [comment] 2019-09-15 15:38
Its' available in the version 1.11.42 I've just published.
