### ISSUE TITLE
Exported HTML files very large in size despite minimal content on the page. 

### ISSUE THREAD

**Issue by SpeckOfDust2545** [gildas-lormeau/SingleFile#1532] opened 2024-08-07 10:15 UTC
**Describe the bug**
I download posts from social media (specifically Facebook, Instagram and Twitter) for use in legal cases. I find the extension extremely helpful but sometimes the exported HTML files are 20-30MB+. When downloading a batch of posts each day though this very quickly starts eating up a lot of hard drive space and ideally they're much smaller. 

In case it helps, for info if I then compress one of those files into a ZIP file, it reduces down to 7-9MB so does seem there is a lot of excess space being used? Perhaps there's a way to compress the exported HTML file so it uses less space? 

Also, just as a suggestion, perhaps it can reduce the resolution of any images (if that is what is using so much space) as is not like I'm going to later blow up the images to higher resolutions that what is already on the page. 

**Environment**
 - OS: Windows 2016 Server
 - Browser: Chrome
 - Version: 125.0.6422.76

**Comment by gildas-lormeau** [comment] 2024-08-07 10:39
I would recommend you to use the self-extracting format, see the setting `File format > format`in the options page of SingleFile.

**Comment by SpeckOfDust2545** [comment] 2024-08-10 09:40
Thanks and that definitely helped bring the total file size. On quite a few pages though I'm getting this error showing on an orange bar along the top:

SingleFile error: Error in invocation of runtime.sendMessage(optional string extensionId, any message, optional object options, optional function callback): Message length exceeded maximum allowed length.

**Comment by gildas-lormeau** [comment] 2024-08-10 11:09
Thank you for the feedback, I think I was able to identify the cause of the error you mentioned. It should be fixed in the next version.

**Comment by gildas-lormeau** [comment] 2024-08-13 21:49
I'm closing the issue because the error should not appear anymore in the last version. Feel free to post a comment if needed though.

**Closed by gildas-lormeau** 2024-08-13 21:49 UTC
