### ISSUE TITLE
Certain pages sometimes consume execssive resources on attempted save

### ISSUE THREAD

**Issue by LunarTulip** [gildas-lormeau/SingleFile#710] opened 2021-07-05 23:51 UTC
**Describe the bug**
Some web pages—I've unfortunately failed to compile a detailed list—will, upon attempted save in SingleFile, sometimes (not reliably) get stuck on step 3/3, start eating up ~80% of my CPU and quantities of memory starting at ~3GB and rising the longer I let them sit and wait, and generally lock up a dramatically-excessive pile of system resources until I kill the tab (or, if performance has already dwindled too much, the browser).

**To Reproduce**
Go to one of the pages on which the problem happens, attempt to download it with SingleFile, and then watch system resource consumption via your preferred tool for that. As I mentioned, it doesn't happen reliably; most of the time, if I try a second time with a page which caused the issue the first time, the issue won't repeat. But a page which caused the issue the first time I tried to save it, and which did the same for a friend when _she_ tried, is [here](https://thingofthings.wordpress.com/2015/05/06/why-i-dont-read-the-news-anymore/). (And several other posts on the same blog have given me the same issue, as well. As have various other pages on various other sites, but it seems particularly common on that blog for whatever reason.)

**Expected behavior**
SingleFile works and downloads the page as normal, without any unusual CPU-hogging or memory-leaking.

**Screenshots**
N/A

**Environment**
Windows 10 Home 64-bit, Firefox 89.0.2. The friend who replicated the bug did so in Firefox 89.0.2 on Ubuntu 20.04.2.

**Additional context**
N/A

**Comment by gildas-lormeau** [comment] 2021-07-23 00:05
I agree this issue can appear sometimes. Debugging it is hard since the browser can be completely frozen. I guess I have to add some logs and do some tests in order to identify which part(s) of the code are causing the issue.

**Comment by gildas-lormeau** [comment] 2021-09-18 00:42
@LunarTulip I fixed this issue https://github.com/gildas-lormeau/SingleFile/issues/780 which could be maybe fix this one as well. Please let me know if you can still reproduce this issue once the extension updated (version `1.19.9`)

**Comment by gildas-lormeau** [comment] 2021-10-01 22:52
I'm closing this issue because I think it should be fixed (cf. previous message). Feel free to reopen it if you think the issue is still present.

**Closed by gildas-lormeau** 2021-10-01 22:52 UTC
