### ISSUE TITLE
Add a settings or fix bug - can't save dynamic & complex sites Instagram, twitter, more..

### ISSUE THREAD

**Issue by nataleeonajourney** [gildas-lormeau/SingleFile#1511] opened 2024-07-23 14:30 UTC
Add a settings or fix bug - can't save dynamic & complex sites Instagram, twitter, more..

- add a feature to properly and fully save complex dynamic sites like Instagram, twitter, and more.. 
- increase the size limit upto 10 GB for the saved pages that are long scrolled, and large pages.

**Comment by gildas-lormeau** [comment] 2024-07-23 14:44
Regarding the first point, there is no generic and 100% reliable way to save dynamic content (generated with JavaScript). You can find some additional info here: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages.

The second point is a duplicate of #1438.

**Closed by gildas-lormeau** 2024-07-23 14:44 UTC
