### ISSUE TITLE
Can not download this page

### ISSUE THREAD

**Issue by ismlsmile** [gildas-lormeau/SingleFile#181] opened 2019-03-29 06:44 UTC
**Describe the bug**
I tried Firefox and Chrome, and they all can not download this page:
http://www.cnblogs.com/artech/p/how-to-cross-platform-01.html.

**To Reproduce**
1. Go to this page
2. Click on 'SingleFile' icon

**Expected behavior**
It shows complete, and do not report any error, but no file is created.

**Environment**
 - OS:  Win10 10.0.17134.648
 - Browser:  Chrome and Firefox
 - Version: x64

**Comment by gildas-lormeau** [comment] 2019-03-29 13:47
Thanks for reporting the issue. It is fixed in the version 1.10.11. This error was due to the fact that the filename of the page was beginning with ".". Windows does not allow this.

**Closed by gildas-lormeau** 2019-03-29 13:47 UTC

**Comment by gildas-lormeau** [comment] 2019-04-03 21:57
Sorry, a regression was introduced meanwhile on Firefox. The issue is fixed in version 1.10.16.
