### ISSUE TITLE
SingleFile error: OAuth2 request failed for Google Drive

### ISSUE THREAD

**Issue by Anebrithien** [gildas-lormeau/SingleFile#901] opened 2022-03-24 06:02 UTC
**Describe the bug**
Get an error when saving html file to Google Drive.

**To Reproduce**
1. Go to any website.
2. Click on extension icon.
3. Click OK when alert window popup to ask file location.

**Expected behavior**
File successfully saved to Google Drive.

**Screenshots**
<img width="1315" alt="error_msg" src="https://user-images.githubusercontent.com/5357409/159851010-2eaaf794-f4ed-409c-bdfc-2420516cd318.png">

**Environment**
 - OS: Win10 Pro, macOS 12.3
 - Browser: Chrome 99
 - Version: 1.19.34 
    > The version was copied from extension page chrome://extensions/?id=mpiodijhokgodhhofbcjdecpffjipkle

**Additional context**
It works good last month with the same configuration.

**Comment by gildas-lormeau** [comment] 2022-03-24 10:18
It looks like Google blocked me from using Google Cloud Platform. I think the only option I have is to remove Google Drive support.

**Comment by gildas-lormeau** [comment] 2022-03-24 10:48
I was able to reproduce it, that's a strange issue. You can it by selecting "Destinations > save to filesystem" and then select again "Destinations > upload to Google Drive".

**Comment by Anebrithien** [comment] 2022-03-24 15:07
I tried but got the same error. 

Steps:

1. Select "save to filesystem".
2. Go to any website, refresh and click extension icon.
3. Select "upload to Google Drive".
4. Repeat step 2.

What I got:

1. A html file was saved to `~/Downloads/...` in step 2.
2. The same error reproduced in step 4.

Background page screenshot:

<img width="1117" alt="console_log" src="https://user-images.githubusercontent.com/5357409/159940256-9578f73e-9692-4845-83b6-f4056dd9f26a.png">


Here is my configuration:

<details>
  <summary>Click to expand</summary>
 
```json
{
  "profiles": {
    "__Default_Settings__": {
      "acceptHeaders": {
        "document": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "font": "application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8",
        "image": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
        "script": "*/*",
        "stylesheet": "text/css,*/*;q=0.1"
      },
      "addProof": false,
      "allowedBookmarkFolders": [
        ""
      ],
      "applySystemTheme": true,
      "autoClose": false,
      "autoOpenEditor": false,
      "autoSaveDelay": 1,
      "autoSaveDiscard": false,
      "autoSaveExternalSave": false,
      "autoSaveLoad": false,
      "autoSaveLoadOrUnload": true,
      "autoSaveRemove": false,
      "autoSaveRepeat": false,
      "autoSaveRepeatDelay": 10,
      "autoSaveUnload": false,
      "backgroundSave": true,
      "blockMixedContent": false,
      "browserActionMenuEnabled": true,
      "compressCSS": false,
      "compressHTML": true,
      "confirmFilename": true,
      "confirmInfobarContent": false,
      "contextMenuEnabled": true,
      "defaultEditorMode": "normal",
      "displayInfobar": true,
      "displayStats": false,
      "extractAuthCode": true,
      "filenameConflictAction": "uniquify",
      "filenameMaxLength": "192",
      "filenameMaxLengthUnit": "bytes",
      "filenameReplacedCharacters": [
        "~",
        "+",
        "\\\\",
        "?",
        "%",
        "*",
        ":",
        "|",
        "\"",
        "<",
        ">",
        "\u0000-\u001f",
        ""
      ],
      "filenameReplacementCharacter": "_",
      "filenameTemplate": "offlineWebPages/{datetime-iso}_{page-title}.html",
      "forceWebAuthFlow": false,
      "githubBranch": "main",
      "githubRepository": "SingleFile-Archives",
      "githubToken": "",
      "githubUser": "",
      "groupDuplicateImages": true,
      "ignoredBookmarkFolders": [
        ""
      ],
      "includeBOM": false,
      "includeInfobar": false,
      "infobarTemplate": "",
      "insertMetaCSP": true,
      "insertMetaNoIndex": false,
      "insertSingleFileComment": true,
      "loadDeferredImages": true,
      "loadDeferredImagesBlockCookies": false,
      "loadDeferredImagesBlockStorage": false,
      "loadDeferredImagesKeepZoomLevel": false,
      "loadDeferredImagesMaxIdleTime": 1500,
      "logsEnabled": true,
      "maxResourceSize": 10,
      "maxResourceSizeEnabled": false,
      "moveStylesInHead": false,
      "openEditor": false,
      "openSavedPage": false,
      "passReferrerOnError": false,
      "progressBarEnabled": true,
      "removeAlternativeFonts": true,
      "removeAlternativeImages": true,
      "removeAlternativeMedias": true,
      "removeAudioSrc": true,
      "removeFrames": false,
      "removeHiddenElements": true,
      "removeImports": true,
      "removeScripts": true,
      "removeUnusedFonts": true,
      "removeUnusedStyles": true,
      "removeVideoSrc": true,
      "replaceBookmarkURL": false,
      "resolveFragmentIdentifierURLs": false,
      "saveCreatedBookmarks": false,
      "saveFavicon": true,
      "saveOriginalURLs": false,
      "saveRawPage": false,
      "saveToClipboard": false,
      "saveToGDrive": true,
      "saveToGitHub": false,
      "saveWithCompanion": false,
      "shadowEnabled": true,
      "tabMenuEnabled": true,
      "userScriptEnabled": false,
      "warnUnsavedPage": true,
      "woleetKey": ""
    }
  },
  "rules": [],
  "maxParallelWorkers": 8
}
```

</details>

I think the way to avoid this issue now is to save the files to the disk directory mounted by the Google Drive desktop app. 

Anyway, thank you very much for providing such a good and useful extension.

**Comment by gildas-lormeau** [comment] 2022-03-24 15:24
You're using the dev version of SingleFile, aren't you?

**Comment by Anebrithien** [comment] 2022-03-24 15:29
It was downloaded from Chrome webstore.

Steps to go to background page:

1. Go to `chrome://extensions/?id=mpiodijhokgodhhofbcjdecpffjipkle`
2. Click the link `src/extension/core/bg/background.html`

A `DevTool` window is there now.

**Comment by gildas-lormeau** [comment] 2022-03-24 15:42
Thank you for the additional information, I fixed the issue and uploaded the new version on the stores. It should be available for download in the coming hours.

**Comment by gildas-lormeau** [comment] 2022-03-24 16:11
FYI, it's published.

**Comment by Anebrithien** [comment] 2022-03-24 16:48
It works as usual. Thank you.

**Comment by Anebrithien** [comment] 2022-11-25 08:15
Caught this issue again today.
* Browser: Chrome 107.0.5304.110
* Version: 1.21.29

The same error message and log in console.
```
SingleFile error: OAuth2 request failed: Service responded with error: 'bad client id: XXXXX.apps.googleusercontent.com' (Google Drive)
```

@gildas-lormeau

**Comment by MaxAlphaChen** [comment] 2023-09-03 16:47
Caught this issue again today.

- Browser: Chrome 116.0.5845.141
- Version: 1.21.63

The same error message and log in console.
`SingleFile error: OAuth2 request failed: Service responded with error: 'bad client id: XXXXXXXXXX-XXXXXXXX.apps.googleusercontent.com' (Google Drive)
`
It was downloaded from Chrome webstore.This problem does not occur on Firefox.

**Comment by gildas-lormeau** [comment] 2023-09-03 18:40
@MaxAlphaChen I confirm the last version is broken, the client ID is the one used for development. This will be fixed in the next version.

**Closed** 2023-09-03 20:35 UTC
