### ISSUE TITLE
Ability to run SingleFile within a Playwright context

### ISSUE THREAD

**Issue by smithnanic** [gildas-lormeau/SingleFile#1463] opened 2024-05-27 05:23 UTC
I’m currently saving HTML pages in my Playwright project with a custom script that packages assets as data strings. But it doesn’t always work very well. 

I would love to be able to use the SingleFile abilities within a Playwright Page context. I could either pass a page object to SingleFile or load SingleFile scripts within the page context, then build the single file HTMl and save it. 

Without this, I just keep trying to recreate this package which feels like an unnecessary duplication of effort.

**Comment by gildas-lormeau** [comment] 2024-05-27 19:05
I'm closing this issue because it's a duplicate of https://github.com/gildas-lormeau/single-file-core/issues/4.

**Closed by gildas-lormeau** 2024-05-27 19:05 UTC
