### ISSUE TITLE
SingleFile fails to get the deferred images after scrolling to the bottom of the page (version 1.17.10)

### ISSUE THREAD

**Issue by DaveBlack** [gildas-lormeau/SingleFile#374] opened 2020-03-05 01:13 UTC
**Describe the bug**
Since recent SingleFile update (version 1.17.10), save page seems to fail on several websites.

**To Reproduce**
1. Had issues with the following (plus others)...
https://wiki.blender.org/wiki/Reference/Release_Notes/2.83/Cycles
https://github.com (on different pages)
https://www.shellenergy.co.uk
2. Click on 'Save page with SingleFile'
3. Page appears to freeze on `Deferred images` stage

**Expected behavior**
After a few moments, save process usually progresses through all stages, then saves the web-page.

**Environment**
 - OS: Linux Mint 19.3 Cinnamon
 - Browser: Firefox
 - Version: 1.17.10

**Additional context**
Tried preferences reset.
Also tested with all other add-ons disabled.
Reverting to version `1.17.8` allows above websites to save without issue. Disabled `Allow automatic updates` for now.

Thank you gildas for your wonderful add-on, for achieving Firefox 'Recommend' status, and for all your hard work!

**Comment by gildas-lormeau** [comment] 2020-03-05 09:10
Thank you for having reported the issue. Unfortunately, I cannot reproduce it in Firefox 73 and 75. I'm doing my tests on Windows. I just reverted the changes I made between these 2 versions in the code related to the lazy loading. These new changes will be available in the version 1.17.14 which is been reviewed. If you can, feel free to install the extension manually (see instructions here https://github.com/gildas-lormeau/SingleFile#install) and tell me if the issue is fixed.

**Comment by kramola-RU** [comment] 2020-03-05 14:08
Gildas, Hi !

SingleFile can`t save selected text at some sites until I scroll up to top.
For example @ http://forum.ru-board.com/topic.cgi?forum=5&topic=50187&start=2140#6

![123](https://user-images.githubusercontent.com/51376332/75989101-b38b1a80-5f03-11ea-9f2f-49b1edf451c6.jpg)

I use FF 70.01

**Comment by gildas-lormeau** [comment] 2020-03-05 14:12
@kramola-RU Thank you! I think you might have helped me to find the cause of the issue. If you press F12, do you see this message in the debugger console? "TypeError: "can't access property "then", lazyLoadPromise is undefined"

If that's the case, then I confirm the version currently being reviewed will fix the issue.

**Comment by kramola-RU** [comment] 2020-03-05 15:11
> @kramola-RU ....do you see this message in the debugger console?
> `TypeError: "can't access property "then", lazyLoadPromise is undefined`

I see:  **TypeError: "lazyLoadPromise is undefined"**

![333](https://user-images.githubusercontent.com/51376332/75994760-82631800-5f0c-11ea-9bb1-329b18155f6e.jpg)

**Comment by gildas-lormeau** [comment] 2020-03-05 15:50
Okay, I think it's the same bug. Let's hope Mozilla will publish the update soon.

**Comment by kramola-RU** [comment] 2020-03-05 15:58
> Let's hope Mozilla will publish the update soon

Mozilla ???
I use FF 70.01 and week(s) ago **SF** worked correctly (but I don`t remember which version it was).

**Comment by gildas-lormeau** [comment] 2020-03-05 16:20
Mozilla reviews the code manually since the extension is recommended, so I need to wait for them before the update is available for download.

**Comment by gildas-lormeau** [comment] 2020-03-05 16:24
Unfortunately, it looks like the update won't be published today. There's been 3 days I'm waiting for it...

**Comment by kramola-RU** [comment] 2020-03-05 16:29
Gildas, I got it  :)
Thank you very much!
I'll wait...

**Comment by gildas-lormeau** [comment] 2020-03-05 16:35
Meanwhile, you can install it the extension manually or use SingleFileZ which is already published.

**Comment by kramola-RU** [comment] 2020-03-05 17:13
**SF 1.17.14** -- works perfect !
No bug. Very fast saving.
**THANKS A LOT !!!**

**Comment by gildas-lormeau** [comment] 2020-03-05 18:30
You're welcome. Thank you very much for the feedback and sorry for the inconvenience.

**Comment by gildas-lormeau** [comment] 2020-03-06 17:45
The extension was not published today. I guess it will be published next week.

**Comment by gildas-lormeau** [comment] 2020-03-06 18:17
I have a better understanding of the bug now. To avoid it, you must not save the page if you scrolled down to the bottom of the page and the option "save deferred images" is checked.

**Comment by kramola-RU** [comment] 2020-03-06 18:34
OK
I see **1.17.16** build
Thank you for your hard work !

**Comment by DaveBlack** [comment] 2020-03-07 18:34
Apologies for my tardy reply.

Just tested 1.17.16 with virtual machines running Linux Mint 19.3 Cinnamon, and Kubuntu 20.04 (daily live), the issue indeed appears to be fixed. Great work!

Will keep using 1.17.8 until Mozilla have chance to check the new code diff, and replace their current 1.17.10 version.

**Comment by noto10** [comment] 2020-03-08 07:37
I'm experiencing this problem with 1.17.10. Can anyone tell me how to revert to 1.17.8?

**Comment by BlackGlory** [comment] 2020-03-08 13:07
I have same issue on Chrome's 1.17.14 extension. After debugging, I found that the problem line is

https://github.com/gildas-lormeau/SingleFile/blob/3cb39be3822c50b904e23c9a29c05530fa46eb0e/lib/single-file/processors/lazy/content/content-lazy-loader.js#L44

The expression is return false and the function returns undefined. I haven't tested 1.17.16, but the current source code still seems to cause this error.

The function calling it:
https://github.com/gildas-lormeau/SingleFile/blob/c615b206c247eb243e07b174c71805e6754b451e/extension/core/content/content-main.js#L129

**Comment by gildas-lormeau** [comment] 2020-03-08 15:13
@BlackGlory I confirm that the bug is the one you described and is not specific to Firefox. It has been fixed by this commit https://github.com/gildas-lormeau/SingleFile/commit/78aaac8736c66c5f5c6b0c9ecac566cea38f24f7. The latest version is currently being reviews by Google. I guess it should be available for download on the store of Chrome in 2 or 3 days.

**Comment by gildas-lormeau** [comment] 2020-03-09 10:07
The version 1.17.16 has been published on the store of Mozilla.

**Closed by gildas-lormeau** 2020-03-09 10:07 UTC
