### ISSUE TITLE
mathjax not saving in firefox

### ISSUE THREAD

**Issue by mak-bd** [gildas-lormeau/SingleFile#80] opened 2018-10-11 09:35 UTC
i saved >>https://squircleart.github.io/animation-nodes/procedural-bookshelves-in-animation-nodes.html<< every thing saved but mathjax equations are not saving.

**Comment by gildas-lormeau** [comment] 2018-10-15 12:07
I'm closing the issue  because I cannot reproduce it. Please re-open it if you can describe me how to reproduce it.

**Closed** 2018-10-15 12:06 UTC

**Comment by KrasnayaPloshchad** [comment] 2018-12-20 18:39
I suggest try Web ScrapBook instead if you need.

**Comment by gildas-lormeau** [comment] 2018-12-20 18:52
@KrasnayaPloshchad Could you give me more details about this issue? I do not understand it...

**Comment by KrasnayaPloshchad** [comment] 2018-12-20 18:58
Oh, I just found another extension that can be used to save a page, but uses another method, this extension can be available here:
https://addons.mozilla.org/en-US/firefox/addon/web-scrapbook/

**Comment by gildas-lormeau** [comment] 2018-12-20 19:02
Okay, but how does it help to fix this issue?
