### ISSUE TITLE
Some styles related to media queries are missing, causing the page to display incorrectly

### ISSUE THREAD

**Issue by tianzhich** [gildas-lormeau/SingleFile#1517] opened 2024-07-29 07:35 UTC
**Describe the bug**

When I save and open [this page](https://huggingface.co/blog/mlabonne/abliteration), the page style appears incorrectly (no overflows). I discovered that it was due to the missing of some styles.
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/a5b67a96-4433-4d67-94b8-b77c9fd9e313">

**To Reproduce**
1. Go to https://huggingface.co/blog/mlabonne/abliteration
2. Click on 'Save page with SingleFile'
3. Open the page

**Expected behavior**

The page should shows correctly and without overflow (The styles related to media query should be here, as the following screenshot).
<img width="1402" alt="image" src="https://github.com/user-attachments/assets/5e5153d8-8578-4313-9b93-26cf7f601d72">

**Screenshots**

I attached the screenshots above.

**Environment**
 - OS: MacOS 14.1
 - Browser: Chrome
 - Version: 126.0.6478.183 (Official Build) (arm64)

**Additional context**

I guess that might caused by [css-tree](https://github.com/csstree/csstree) in which the single-file-core is using.

**Comment by gildas-lormeau** [comment] 2024-07-29 13:32
Thank you, I was able to reproduce, identify the cause the issue and fix it. It will be fixed in the next version. Meanwhile you can disable the option `Stylesheets > remove stylesheets for alternative devices to screens` for your information.

**Closed** 2024-07-29 20:36 UTC
