### ISSUE TITLE
How to export images in html file into folder ?

### ISSUE THREAD

**Issue by wankio** [gildas-lormeau/SingleFile#153] opened 2019-02-11 03:06 UTC
This firefox extension worked pretty good but how i can export single html file into folder with images inside ? 
Thank

**Comment by gildas-lormeau** [comment] 2019-02-11 10:55
I guess you would have to use an extension that allows you to download images into a folder. I don't know if it exists but I confirm this is technically doable. From my point of view, I consider this feature out of scope for SingleFile. If you cannot find such extension, I may develop one since it wouldn't be very hard to do so.

**Comment by wankio** [comment] 2019-02-11 16:59
yeah, it would be great, download images in fully loaded webpage into folder, folder name set by page title and date_time. mht2html

**Comment by JohnnyWoong** [comment] 2019-02-21 01:25
maybe can add option for single file or split html,css,js and images

**Comment by gildas-lormeau** [comment] 2019-02-21 13:03
@JohnnyWoong Do you think that could be really interesting for users to save apart the CSS and JS files?

**Comment by JohnnyWoong** [comment] 2019-02-21 13:51
I think that will be a great app for developers

**Comment by gildas-lormeau** [comment] 2019-02-21 15:31
Why shouldn't they use the native "save as" feature which does exactly this (i.e. saving in a separate folder all the external resources)?

**Comment by JohnnyWoong** [comment] 2019-02-21 15:35
This way save page ofter miss something

**Comment by gildas-lormeau** [comment] 2019-02-21 16:18
The native "save as" may be indeed less reliable... The problem is that you're basically asking me to re-implement the "save as" feature because Google don't fix their bugs.  If I implemented it, I think I could not integrate this feature in SingleFile, because of its name. I'm pretty sure people would never expect it to save a page in several files...

**Comment by JohnnyWoong** [comment] 2019-02-22 00:27
Yeap,you are right (｀・ω・´)

**Comment by KrasnayaPloshchad** [comment] 2019-02-23 17:38
You can try Web ScrapBook to save page, then you will get a HTZ file, or MAFF file if you configured, then you extract it via 7-zip and similar app, and you will get it.

**Comment by JohnnyWoong** [comment] 2019-02-25 01:26
> You can try Web ScrapBook to save page, then you will get a HTZ file, or MAFF file if you configured, then you extract it via 7-zip and similar app, and you will get it.

ok, i will try that,thx : )

**Comment by wankio** [comment] 2019-02-27 07:35
mht2html can extract it. Singlefile is really great for archive page without redownload any files (it may have chance to failed,missing,corrupted if redownload files)

**Comment by gildas-lormeau** [comment] 2019-04-27 23:22
@JohnnyWoong Did you try this extension? https://chrome.google.com/webstore/detail/save-all-resources/abpdnfjocnmdomablahdcfnoggeeiedb

**Comment by JohnnyWoong** [comment] 2019-04-28 00:31
> @JohnnyWoong Did you try this extension? https://chrome.google.com/webstore/detail/save-all-resources/abpdnfjocnmdomablahdcfnoggeeiedb

thx,i will try that

**Comment by gildas-lormeau** [comment] 2019-05-01 19:56
@JohnnyWoong Did you try the extension? It looks like it's exactly what you need. Therefore, I would close this issue.

**Comment by JohnnyWoong** [comment] 2019-05-02 01:56
Yep,i already try that,that is what i want,thx :)

**Comment by gildas-lormeau** [comment] 2019-05-02 08:17
Great!

**Closed by gildas-lormeau** 2019-05-02 08:17 UTC
Labels: feature request, out of scope

**Comment by gildas-lormeau** [comment] 2019-05-19 22:22
@JohnnyWoong This may interest you: https://addons.mozilla.org/en-US/firefox/addon/singlefilez/

This fork of SingleFile creates HTML files that are also ZIP files which contain the page resources.

**Comment by JohnnyWoong** [comment] 2019-05-20 01:22
Thanks for info, but i am a chrome user 👍

**Comment by gildas-lormeau** [comment] 2019-05-20 04:01
@JohnnyWoong Too bad, you don't know what you're missing ;)

**Comment by gildas-lormeau** [comment] 2019-05-28 21:02
@wankio @JohnnyWoong This may interest you: https://chrome.google.com/webstore/detail/singlefilez/offkdfbbigofcgdokjemgjpdockaafjg

**Comment by JohnnyWoong** [comment] 2019-05-28 22:54
wow, thx :)

Gildas Lormeau <notifications@github.com> 于2019年5月29日周三 上午5:02写道：
